### ISSUE TITLE
oiiotool: --fullpixel data window handling difference: 1.4 vs 1.5

### ISSUE THREAD

**Issue by justinfx** [OpenImageIO/oiio#1068]
We just started using a 1.5 build a noticed a difference in oiiotool, in the handling of —fullpixel vs the behavior in 1.4. The results in 1.5 look completely wrong, and I was trying to search if anything had changed in the 1.5 branch that might have broken this behavior.

An example:

```
$ oiiotool -v --info source.exr
Reading source.exr
source.exr  : 3414 x 2198, 3 channel, half openexr
    channel list: R, G, B
    pixel data origin: x=-195, y-217
    full/display size: 3024 x 1764
    full/display origin: 0, 0
    ...
    PixelAspectRatio: 1
    screenWindowCenter: 0 0
    screenWindowWidth: 1
```

Then we run the identical command in both 1.4 and 1.5:

```
$ oiiotool -v source.exr --fullpixels -o out.jpg
```

In 1.4.14 we see what we expect, where the entire data window is retained in the output image.

In 1.5.11 we see strange mixture, where the top-left is aligned to the display window, and the bottom-right is the data window

Any ideas?

**Comment by lgritz** [comment]
This appears to be related to the fact that JPEG files cannot represent overscanned images, or in fact any notion of separate display and data windows or nonzero image origin.

So I think the question is: what is the best behavior when you have an overscan image (or a crop window -- let's try to make the same heuristic work for both) and try to output it to JPEG?

**Comment by lgritz** [comment]
--fullpixels means "set the full (i.e. display) window to be identical to the data window."

--croptofull means "trim or pad the data window to make it be identical to the display/full window"

--origin means "keep the *size* of the data window, but reposition it to the origin"

So if you want to save the full data window to JPEG, aware that you will lose any distinction between data and display windows and that the only origin for either that JPEG supports is (0,0), then try:

    oiiotool source.exr -origin +0+0 -fullpixels -o out.jpg

**Comment by lgritz** [comment]
I get confused by these, too, and have to look it up in the docs every time.

It looks like what is happening without the -origin command is, when saving to JPEG, it's "clipping" the negative-valued portions of the pixel data.  In other words, pixel (3,3) will stay where it always was, but pixel (-1,-1) will just not be saved as JPEG. The behavior you want, if I understand, is for the old pixel (3,3) to magically move to (195,217) by shifting the whole image so that no original data is lost.

I can see merit to both approaches. It seems wrong to lose data, but it also seems wrong to just shove it around the image plane without being told to do so.

    oiiotool in.exr -o out.exr
    oiiotool in.exr -o out.jpg

Do you expect pixel (a,b) in out.exr to match pixel (a,b) in out.jpg? All other things being equal, I would. So should that intuition change depending on the original windows of in.exr, or not?

**Comment by lgritz** [comment]
I am happy to entertain arguments that "-origin +0+0 -fullpixels" should automatically happen if you output to JPEG.

But again, my main counter is "are you sure you want to move the pixels around the image plane without being told explicitly to do so?"

**Comment by justinfx** [comment]
I will be honest. I am not sure exactly what I would expect to be the normal default behavior in this case. Only that the behavior had changed when running the same operation in 1.4 vs 1.5. Essentially the goal was to have the full data window written as the pixels to the jpeg output, and there was no expectation to try and maintain a data/window distinction. 

I defer to you, or others feedback, for deciding what is best in this case. Was really just curious if something did indeed change.

**Comment by justinfx** [comment]
I think the suggestion about using the `--origin` flag has solved the issue since it produces the same results now in 1.5 as we were getting in 1.4. So I'm going to go ahead and close this issue. I think the take away is that the behavior has changed from 1.4 to 1.5. 

Thanks!

**Comment by lgritz** [comment]
I'd need to go over the git records and/or release notes to try to figure out exactly how and why this changed, but I'm betting that we did it for a reason (for example, tightening up ambiguous or underspecified behavior in that case, and it ended up changing as a result).

My inclination currently is to leave it as it is, since it's so easy to give a command that does what you originally wanted. It's really tricky to decide good defaults in these cases that inherently involve moving data from a very flexible format to a very constrained one. (Didn't we also just deal with the issue of moving n-channel exr to JPEG that is limited to 3 channels?) You lose something any way you shake it, and it's an icky judgment call to choose between various bad options.

**Comment by justinfx** [comment]
Yep, fair enough. I'm definitely not going down the route of asking for new defaults to be chosen. Something changed from the way it was before, and you gave me an adjustment to the command that resolved it. So that pretty much buttons it up for me :-) 

In the case of the N-channel to jpeg that was more about not being able to get any kind of image at all and error-ing out. Whereas in this case I get images either way, but a change made the same command produce different images between versions.
