### ISSUE TITLE
PFM (part of pnminput) rows should be bottom to top

### ISSUE THREAD

**Issue by devernay** [OpenImageIO/oiio#1170]
PFM is an exception in the PNM families: rows are bottom to top, see http://netpbm.sourceforge.net/doc/pfm.html and http://www.pauldebevec.com/Research/HDR/PFM/
PPM and friends are top to bottom, see http://netpbm.sourceforge.net/doc/ppm.html
I don't know how to do this cleanly in pnminput.cpp, do you want me to try submitting a patch?

**Comment by lgritz** [comment]
Sorry for the delay.

We have a few choices:

1. One solution is, for the pfm case (but not the other pnm types), we can read the entire image when the first scanline is requested by PNMInput::read_file_scanline, buffer it, and then dole out the data in reverse order. Pro: fast file reads, since we are reading the whole thing contiguously in one shot. Con: must keep the whole image in memory, which is wasteful if we will tend to see lots of large PFM files.

2. After reading the header, do an tellg of the input stream to find the file offset of the first scanline. Since the data are uncompressed, each scanline is the same length and any scanline's offset can be trivially calculated. So we change read_file_scanline to do a seekg to the right spot for each scanline. Pro: easy, no buffering. Con: lots of seeks and essentially reading the file out of order, so this will be slower to read the file.

3. Do nothing. Pro: easiest solution of all. Con: makes pfm images upside down. Does anybody actually use PFM? In a way that actually matters if it's upside down? 

Where are you coming across PFM files? Under what circumstances would we ever see these in real live? Should whatever users or applications might be producing PFM files be better in the long run if we take this opportunity to switch them to something better like OpenEXR, whereas our fixing pfm read is, in some sense, letting a much larger problem persist? (Three HUGE advantages of EXR over PFM: (1) compression; (2) half; (3) metadata -- I mean seriously, how useful is an HDR image that can't document anything about itself, such as even anything as basic as what color space the values are in?)

**Comment by devernay** [comment]
The first solution looks nice and easy to me.

I use PPM/PFM a lot with my computer vision/image processing students, because a PFM writer is just 10 lines of codes in any language and adds no dependency at all to any existing program.

We store many scalar fields that way that are not image intensity data, and cannot be represented faithfully as half.

But you can also make the choice to not support PFM at all in OIIO (rather than having a broken plugin), which I wouldn't blame you for

fred

**Comment by lgritz** [comment]
As long as somebody is using it, we may as well do it right. Either (1) or (2) that I proposed earlier ought to be straightforward. I'm actually thinking that (2) is a little simpler, since it requires no buffering.

I'm happy to take a stab at it if you want, unless you wanted to do it yourself. It looks like it's pretty simple, I bet I can knock it out in minutes.

**Comment by devernay** [comment]
You're right, (2) may be less efficient in terms of i/o (although maybe buffered i/o is not so bad in this case).
I guess you already have the code somewhere in your head, so if it only takes minutes to type, I'll leave it to you !

**Comment by lgritz** [comment]
I'll give it a try. If it really turns out to be not super easy, I will throw it back to you. :-)

**Comment by lgritz** [comment]
Proposed fix: #1230

**Comment by lgritz** [comment]
Did you have a chance to try this?

**Comment by lgritz** [comment]
Never heard anything back. It seems to work for me, so I'm going to commit it. Open a new issue if anything about pfm is still broken after the patch.

**Comment by devernay** [comment]
sorry, I didn't find time to check, but fix seems ok
