### ISSUE TITLE
Errors should always be printed out

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#1242]
Some errors are only printed out when NDEBUG is undefined.  This bit us when we spent a bit of time trying to figure out why the following applied on an EXR was still resulting in a ratio of 1.

    spec.attribute("PixelAspectRatio", 2);

It wasn't until we recompiled OIIO in debug mode that we finally saw an error explaining that:
```
Caught OpenEXR exception: Cannot assign a value of type "int" to image attribute "pixelAspectRatio" of type "float".
Don't know what to do with int pixelAspectRatio
```
One simple solution is to get rid of the NDEBUG checks in these places.  A quick look shows exif.cpp, imageioplugin.cpp, and exroutput.cpp as possible places where fails are likely silently handled (I only confirmed exroutput.cpp, the others might be non-issues).  Another option is to allow these warnings to be printed if we defined some flag at compile time such as DISABLE_SILENT_FAILS

**Comment by lgritz** [comment]
I think there are really two problems here, and perhaps they should be handled separately.

First, you passed in an integer for PixelAspectRatio, OpenEXR wants a float, and it dropped it (silently for non-debug mode). I think in this case, it's an easy mistake to make, it's obvious what your intentions were, and clearly it should be smart enough to convert the int to float automatically. I will propose a patch that addresses this, and we can finish that conversation on the other ticket.

As far as the NDEBUG, there is a design philosophy issue. The point of OIIO is to present a uniform API for many formats, and in fact for the calling app to mostly not need to know anything about those formats and their limitations and not need to be full of clutter to handle all the possibilities of what a format can accept. Mostly, we just want the app to work, producing the closest output to what they asked for, within the limits of sensibility. Some things are just errors -- if you ask for a resolution or number of channels that simply can't be supported by the format, or tiles for a scanline-only format, that kind of thing. But we try to tolerate as much mismatch as we can, trying to handle it gracefully. Among other things, if we encounter metadata that the format doesn't understand, the specific design decision was to silently drop it.

Because for debugging purposes it might be handy to get a clue that this is happening, there are a few spots guarded by NDEBUG where we print some status messages to stderr or stdout. Note that this is for debugging only, and is known to be unsafe on Windows or when used from an app where nobody is paying attention to a terminal.

ImageInput API calls can have errors (returning false and preferably also setting an error message that can be retrieved with geterror()). There is not, at the moment, a way to throw a "warning", and I'm not sure in what circumstances you'd want to, or want the calling app to have to sort through them, or want users to see them. For example,

    oiiotool in.exr -o out.tif

converts from EXR to TIFF, and since OpenEXR allows (mostly) arbitrary metadata but TIFF does not, we expect this combination to silently drop most of the metadata it finds, that's the only sensible thing to do. Having it dump a couple screen-fulls of warning messages doesn't seem like a good idea.

I can think of several things to do:

1. Nothing -- now that I've explained the idea, you agree that unrecognized metadata should be silently dropped, and that spurious debug messages meant for the OIIO developers are ok in debug mode.

2. Add ways to propagate warnings, which can be retrieved by an app that really cares, but is also safe (and expected) to ignore. (Side issue: if you ignore it in a long-running, warning-producing program, what should happen to all those accumulated warnings?)

3. Like (2), but have one or more OIIO attributes (or one or more build-time options) that cause the warnings to be issued, with the default being that they aren't even registered at all (as now).

4. Like (3), but those warnings become true errors.

**Comment by lgritz** [comment]
The PixelAspectRatio (and other similar errors for exr) should be fixed by #1249.

**Comment by ThiagoIze** [comment]
Making sure that the errors never occur in the first place, like with #1249, is a nice way of getting around this issue to begin with.  Hopefully now there are almost no occasions where the errors being printed out are actually still critical to know about, so option 1 is perfectly fine with me.  

Ideally though would be option 2 that reports the last saved error (or if you think it's likely that there are often multiple errors, then maybe it has a ring bugger of 100 or so errors?).  That way if something odd is happening, it's easy for the programmer to clear the error buffer before the call and then check to see if there are any errors generated after the call they are interested in.  This can be especially helpful for situations where rebuilding OIIO with debug symbols and without optimizations might be challenging.  For instance, maybe OIIO is a dynamic library shipped with a program and the end user might not be able to recompile OIIO themselves.

**Comment by lgritz** [comment]
OK, what do you think about this, then:

Add a warning() that can be used to register things that are not serious enough to consider an impediment to reading or writing the file, it will queue up some reasonable maximum, and it can be retrieved by an app that cares, or safely ignored by those that don't.

AND/OR... 

We could have a debug() for messages like this, but they are just silently dropped unless a global option is set to make them actually print. Anything that now uses stderr directly should use that instead, so there is no bare console output (since it's a library).

**Comment by ThiagoIze** [comment]
Both good options, but I think the second option might be easier to use
since it doesn't require placing checks all over the client code.  It's
also almost just as powerful since someone could enable this before the
function they care about and then disable it afterwards so that roughly the
same functionality of the first option can be obtained (though this
particular usage isn't thread safe).

Maybe give the user the option of passing in what stream they want to write
out to?  That way they can have this write out to stderr or their own
custom stream (maybe it outputs to a file).

**Comment by lgritz** [comment]
OK, I have a stab at this that I will submit as a PR once the other one gets approved and merged (the debug stuff is on top of the other one).
