### ISSUE TITLE
About the "multiView" attribute and unknown sized attributes

### ISSUE THREAD

**Issue by MrKepzie** [OpenImageIO/oiio#1247]
In exrinput.cpp the "multiView" attribute is a OpenEXR 2 StringVectorAttribute. 
When handling the attribute, it does the following (https://github.com/OpenImageIO/oiio/blob/master/src/openexr.imageio/exrinput.cpp#L613-L614) : 

```
TypeDesc sv (TypeDesc::STRING, ustrvec.size());
 spec.attribute(oname, sv, &ustrvec[0]);
```

1) This attribute has an unknown size by the caller, but the TypeDesc is "identified" by the vector size. The only solution then to retrieve this attribute from the _find_attribute()_ function is to pass TypeDesc::UNKNOWN so we are sure it does not attempt array length equality check (because we don't know on the calling hand the size of the array). 

2) The second line :  _spec.attribute(oname, sv, &ustrvec[0])_ will create an attribute with only 1 value as size, see: https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/formatspec.cpp#L298
This results in the function _ParamValue::nvalues()_ returning 1 always, even if this is in this case a string vector. 
The only workaround at the moment is to call _ParamValue::type()_ on the attribute to retrieve the original TypeDesc and check its array length. 
Is this the intended way to deal with dynamic size attributes ?

**Comment by lgritz** [comment]
I'm not sure if this is still an issue in our code any more or not (this area of the code has changed a lot since the embarrassingly long time ago that this was filed). But in any case, I think that this method of dealing with multi-view is no longer favored, and instead everybody is using multi-part exrs, which we do support.

I'm going to speculatively close this, but if you think that there's still a problem worth investigating in current versions, please re-open or re-file the issue.
