### ISSUE TITLE
oiiotool segfaults running same commandline on deep exr file a second time

### ISSUE THREAD

**Issue by sebastianelsner** [OpenImageIO/oiio#1282]
I ran the following command line on a deep exr coming from houdini:

 oiiotool deep.exr --scanline --compression zip1 --autotrim --ch A,Z -o deep.exr

Running it again on the same file gives a segfault on CentOS 6.6, OpenEXR 2.2.
I have attached the file in question, so running the command on the file, should produce the error.

[deep.exr.zip](https://github.com/OpenImageIO/oiio/files/53963/deep.exr.zip)

**Comment by lgritz** [comment]
Looking into this. I can reproduce, and for that matter I can do it simply as

    oiiotool deep.exr --ch A,Z -o deep2.exr

whereas

    oiiotool deep.exr -o deep2.exr

works fine. So I'm concentrating on --ch as the culprit.

Also, I've already been able to determine that it seems to specifically be the case where the channels are exactly what's already in the file (that's why it only is an error the *second* time).

If you need a temporary workaround, look for these lines

    if (nchannels == src.spec().nchannels && inorder) {
        return dst.copy (src);
    }

in ImageBufAlgo::channels (see imagebufalgo_copy.cpp), and just comment out the "return". That appears to make it work for now. I'll figure out tomorrow why the copy is crashing.

**Comment by lgritz** [comment]
I think I see what's going wrong. Needs to wait until tomorrow morning, but I'll have a PR that fixes it.

**Comment by lgritz** [comment]
Proposed fix in #1286 

That's a patch against RB-1.6.  It would be helpful if you could try it out and verify that it completely solves your problem.

**Comment by sebastianelsner** [comment]
Issue fixed, many thanks!
