### ISSUE TITLE
[MingW] Fix UTF-8 support using fstream 

### ISSUE THREAD

**Issue by MrKepzie** [OpenImageIO/oiio#1349]
OIIO correctly handle issues in fopen on Windows by using _wfopen in the FileSystem::open(...) function which is handled by GCC too on MingW.

Unfortunately *ifstream* and *ofstream* UTF-8 support (i.e: passing a wchar_t to *open()* or the constructor) is a MSVC extension and will not compile in MingW. 

A wrong patch proposed by MINGW-packages (the active maintainers of MSYS2) (https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-openimageio/fix-mingw-w64.patch)  added a patch to use the same version for unix and MingW, but unfortunately, that would mean no UTF-8 support in the case of MinGW. 

The proposed patch correctly fixes this by using a GNU extension ** __gnu_cxx::stdio_filebuf**
Note that it works by embedding a file descriptor into the *istream* (or *ostream*) hence we cannot use *ifstream* and *ofstream* directly but must use the base class everywhere using pointers for inheritance. 

This change hence needs a modification of the Filesystem A.P.I regarding the 2 open() functions because they would force the using of *ifstream* and *ofstream* directly. This patch does the change and correctly fixes it wherever it is used within OpenImageIO. 
 
Note that since we use pointers now and that the allocation is done within the open() function, the caller is responsible for ownership and should encapsulate the return pointer into a RAII style structure such as a smart_ptr. This has been done in all places where it uses these functions in OIIO itself. 
I didn't want to include boost/shared_ptr.hpp in the Filesystem.h directly since it looks like no header brings in boost anyway. 

Without this patch, any application compiled against MINGW using OpenImageIO would not have UTF-8 support and most images read with special filenames would not be read. 

I will also propose this to MINGW-packages maintainers in the meantime. 

Here-in attached the patch:

[oiio-1.5.23-mingw-UTF8iostream.txt](https://github.com/OpenImageIO/oiio/files/123382/oiio-1.5.23-mingw-UTF8iostream.txt)

On Github: https://github.com/MrKepzie/Natron/blob/workshop/tools/Windows/include/patches/OpenImageIO/oiio-1.5.23-mingw-UTF8iostream.patch

**Comment by c42f** [comment]
Regarding ownership, how about just returning a `std::unique_ptr`?  This is the no-cost solution to managing ownership in C++11 factory functions.  Not sure how soon you want to do this @lgritz, but `unique_ptr` has been around for a long time now, being one of the first features which was fairly uniformly available across compilers.  (And I did notice #1344)

**Comment by MrKepzie** [comment]
The patch was slightly updated on the github link to fix the missing _O_CREAT flag for ostream

**Comment by lgritz** [comment]
Sorry for the delay. I'm not ignoring. Just need to digest this without my head exploding.

Is it possible for you to submit this as a PR against OIIO master? I'm always leery of a downloadable patch, in the back of my mind I'm wondering if I applied it correctly, if it's been changed since the last time I downloaded it, etc. True PRs are so much easier to review and merge.

I think that rather than remove the old functions, we need to *add* the new ones, so that we don't break compatibility with any apps that use the functions we've exposed in filesystem.h. That's especially crucial if you want this backported to release branches, since in those we promise to never break or remove any exposed public API calls. (In master, we can mark the old ones as deprecated, but I like to leave them around for a full release before removing them entirely, if at all possible.)

@c42f (oh, and great to see you around these parts again!), I'm going to be very happy to incorporate unique_ptr into APIs once we are really, truly C++11 only. But for any branches that need to support C++03 and older compilers, we can't do that quite yet, and I'm assuming by the naming of his patch that he's still on 1.5. So again, the need to backport this fix places some hard restrictions on the approach in this case. I think that the best approach is the istream **, leave it to the caller to RAII it, but we can revisit this when fully C++11 and consider another overhaul that does away with all that in favor of a unique_ptr.

**Comment by MrKepzie** [comment]
Ok I will fork and pull request the patch and make 2 new open functions. 
We would be happy to switch to 1.6.9 but we encountered issues with some multi layered EXR files not being read correctly, see https://github.com/OpenImageIO/oiio/issues/1335.

**Comment by lgritz** [comment]
Fixed now.
