### ISSUE TITLE
Channel sorting bug(?) with OpenEXR files

### ISSUE THREAD

**Issue by irieger** [OpenImageIO/oiio#1480]
**Expected behavior:** OpenImageIO to save channels in the order I they are passed to the write_image function

**Actual behavior:** Channels seem to be resorted by name and worst, even if no name is set the channels will be named "unknown X" with X being a number without leading zeros and the sorting ordering like "unknown 1", "unknown 10", ... "unknown 19", "unknown 2", "unknown 20"....

This problem caused me a headache as I'm working on Reflectance Transformation Imaging and I use exr to store the coefficients for functions representing the value of a pixel dependent to the light position.

I already set some individual channel names in the style of "c0_0"... with the first number being the channel (c0 = red, c1 = green, c2 = blue in the simple case) and the second number being the coefficient number counting from zero. With simple polynoms this worked well but with more complex functions I got weird results and was searching for bugs for some weeks now in the math I use and as I had already some files working. As I now realized all working files were before a specific date so via git I found that the change which caused the problem to first become visible was a commit 2 weeks ago.

Before this commit I just had a static number setting c0_0 - c0_5, c1_0 - c... resulting in 18 channels named c?_? + X channels named "unknown y" with y >= 18. So as all relevant cases where between 18 and 90 channels the problem didn't show in this version as the names matched the sorting algorithm. After the change I was working on another system searching for the error in the system and in changes in my code.

As I expected to get the channels in the order I save them I just read the image at once on the viewing side where things get mixed up depending on the channel names ...

Is this sorting meant to be a feature? I'd call it unexpected behavior from my end.

### Steps to Reproduce

1. Have more than 9 channels and don't name them
2. Save exr
3. Read file and get a different channel order

### Versions

* OIIO branch/version: 1.6.11
* OS: Ubuntu 16.04
* C++ compiler: 5.4.0

**Comment by lgritz** [comment]
Unfortunately, this is OpenEXR's fault. OpenEXR *always* saves channel in alphabetical order (meaning that "11" will come before "2" (but "11" will properly be after "01", if that's helpful).

There's not much OIIO can do, because every time it writes an exr file, no matter what order it presents the channels, the OpenEXR library (libIlmImf) will reorder the channels, so they will be in a different (canonical) order by the time they are read again.

There is an exception to the rule: OIIO's exr reader will reorder channels so that "R", "G", "B", "A", and "Z", if they exist, will be moved to the front and in that order. But that's just the way it presents it to the app that's reading files through OIIO, it doesn't actually change anything on disk. But it has no way to guess about your custom channel names.

**Comment by irieger** [comment]
Ok, good to know. So it's upstream. I already saw the RGBA behavior but the rest was strange. Already changed my channel naming to contain leading zeros but I would consider this a bug in OpenEXR than.

Bu of course this is no OpenImageIO related thing than and I'll close it. Maybe it could be documented thought I didn't find anything in the documentation about this behavior while nice stuff like arbitrary metadata is well documented. Could be a nice note to save others some headaches.

**Comment by lgritz** [comment]
I agree that it's weird. I'll add something to the OIIO docs that describes this behavior for OpenEXR.

A few points of discussion:

OpenEXR is, I think, the only image file format I'm aware of that allows explicit naming of channels (and one of only a few that allow an arbitrary number of channels, beyond rgba). Between you and me, I think they totally botched it by reordering upon write. But the other formats are even worse, in that they tend to have no support for naming channels at all, so that information is totally lost in, say, a TIFF file, between a write and a subsequent read.

I've wondered before if the solution to TIFF and other formats without channel names is to adopt a convention for saving channel names in the metadata, and for formats that don't allow arbitrary names of metadata (like, ugh, TIFF), we could just add it to the image description field (in some special format, like "OIIO:ChannelNames={c1,c2,c11}"), and then the reader could notice and decode this and present it properly in the ImageSpec. Only OIIO-based writers could be counted on to add the comments properly, and only OIIO-based readers would honor them when read. But plenty of apps use OIIO, so at least within that ecosystem the channel names might be preserved.

So now after your comments, I'm wondering if that idea should be extended to OpenEXR as well --despite its already storing channel names, we could use the same convention to allow us, despite the efforts of libIlmImf, to preserve channel order across a write/disk/read cycle, by having the reader fully reorder channels to match what the writer said in that special metadata.

Again, this would be totally thwarted by any non-OIIO-based reader or writer in the pipeline. Also, it would allow some hilarious bugs if somehow a careless writer managed to copy the metadata unchanged while altering the channels meanings or names. (I guess our reader could do some sanity checks and ignore the metadata if the number of channels or names didn't match the set implied by our name list.)

Does this sound like a good idea, or just an added layer of complexity that can lead to difficult bugs?

**Comment by irieger** [comment]
I just checked back and realized I hadn't answered your last thoughts. Seems this was lost in a browser crash as I already had written something about 10 days ago and thought I posted it ....

On one side I like the idea of OIIO saving it's channel name (and order information if needed) in its own way to assure the image is the same as was written. But on the other side I would prefer if the file formats had a standard for this to have a general way. But on OpenEXR it may not be the worst idea - if not considered a bug by ILM - as arbitrary metadata fields are available. On the other side - as you commented - it might lead to other errors...

Misusing a field in a format with no appropriate way to store individual metadata (like TIFF) inside a general metadata tag however would be dangerous as they might be used otherwise in some apps. This might also interfer or at least get destroyed by external application using the description field for a description or anything else.

But as you noted it might be dangerous to introduce this layer of complexity so I'd rather go for a clear bold warning in the documentation warning that additional channels have to be threated with care, especially with EXR files, instead of a workaround that might bring it's own class of problems.

P.S. As Github noted I have cross-posted this problem to the OpenEXR project without any reaction yet. Would prefer if they would fix this behaviour.
