### ISSUE TITLE
simd.h missing inline implementations for int8 components

### ISSUE THREAD

**Issue by mikaelsundell** [OpenImageIO/oiio#1506]
On windows, the simd int8 implementations for int8 components access seems to be missing, simd_test.cpp:1344 gives missing symbols.

Missing (copied from int4)

OIIO_FORCEINLINE int int8::x() const { return extract<0>(*this); }
OIIO_FORCEINLINE int int8::y() const { return extract<1>(*this); }
OIIO_FORCEINLINE int int8::z () const { return extract<2>(*this); }
OIIO_FORCEINLINE int int8::w () const { return extract<3>(*this); }
OIIO_FORCEINLINE void int8::set_x(int val) { *this = insert<0>(*this, val); }
OIIO_FORCEINLINE void int8::set_y(int val) { *this = insert<1>(*this, val); }
OIIO_FORCEINLINE void int8::set_z(int val) { *this = insert<2>(*this, val); }
OIIO_FORCEINLINE void int8::set_w(int val) { *this = insert<3>(*this, val); }

**Comment by lgritz** [comment]
It's actually more subtle than that!

Those functions were purposely omitted from int8, because it didn't feel like x, y, z, w made any sense for an 8-vector.

If you notice in simd_test.cpp, line 422,

    if (VEC::elements <= 4)

guards the section where it uses those functions. (int4::elements is 4, int8::elements is 8).

It appears that for clang and gcc, the template instantiation folds away the contents of that 'if' before considering whether the functions used inside are valid, so it's not an error.

But for MSVS on WIndows, it appears to still be an error to mention VEC::x() if it's not defined, even when only done from inside a conditional that cannot possibly be taken!

**Comment by lgritz** [comment]
I seem to have defined those functions for float8, apparently solely to make those templated unit tests work without complaint. I guess I'll add the same for int8.

**Comment by lgritz** [comment]
Oddly, this never made errors for my Appveyor builds. Exactly which compiler are you using on Windows?

**Comment by mikaelsundell** [comment]
Good, works, it's actually line 1357 test_component_access<int8>(); that asks for the missing symbol. The compiler is MSVC 18.0.31101.0 (Visual Studio 2013) - we still have some binary-only libraries in our tech-stack and we don't want to mix up msvc* versions.
