### ISSUE TITLE
Possible to eliminate boost in public headers?

### ISSUE THREAD

**Issue by meshula** [OpenImageIO/oiio#1571]
A build of OCIO can fall over due to dassert.h inclusion of boost/static_assert.hpp, because OCIO doesn't have boost as a dependency. 

Not having boost includes in the public header suite would eliminate a bit of tedious debugging when trying to build a custom build environment that includes both OIIO and OCIO. In general, people don't run into this due to installing boost globally in /usr/local. This assumption falls over though when you have an environment with multiple boosts installed, or boost is not installed in a globally visible location, hence my request.

Really, OCIO should be searching for boost in its own cmake files in order to avoid this problem, but I feel it would be more elegant to solve it at the OIIO level, since OCIO doesn't rely on boost in any other way.

**Comment by lgritz** [comment]
I'm fairly certain that the #include is not referenced unless you are compiling in C++03 mode. You aren't doing that, are you, Nick?

And if you must compiler OCIO with C++03... I'm all ears, how would you suggest I fix this on the OIIO side?

**Comment by meshula** [comment]
Ok, good tip ~ that looks plausible. Investigating...

**Comment by lgritz** [comment]
Any luck on this, Nick?

Another thing we can do on our side is make OIIO_STATIC_ASSERT do nothing for C++03. Since in master, C++11 is a requirement, and is common for users of 1.7 as well, I'm not sure we'd be losing much if we eliminated those compile-time checks for the few users stuck on C++03. By making this compromise, we would be eliminating the last boost inclusion in the public headers, I believe.

**Comment by meshula** [comment]
Thanks for the follow up! Here's what worked for me as a cmake invocation for OCIO. OCIO 1.0.9 gave the least troublesome results (compared to ToT or 1.0.7 which I also tested).

I've forced C++11, but also induced the boost dependency through USE_BOOST_PTR because OCIO without boost goes off and references tr1 files, a whole other can of worms since the tr1 files don't exist everywhere any more.

At the moment, removing boost seems premature :)

````
cmake \
  -DCMAKE_PREFIX_PATH="${LOCAL}" \
  -DCMAKE_INSTALL_PREFIX="${LOCAL}" \
  -DOCIO_USE_BOOST_PTR=1 \
  -DCMAKE_CXX_FLAGS="-std=c++11" \
  -DCMAKE_INSTALL_NAME_DIR=@rpath \
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON \
  -DCMAKE_VERBOSE_MAKEFILE=OFF \
  -DOCIO_BUILD_APPS=OFF \
  -DOCIO_BUILD_DOCS=OFF \
  -DOCIO_BUILD_TESTS=OFF \
  -DOCIO_BUILD_JNIGLUE=OFF \
  -DEXTERNAL_INCLUDE_DIRS="${LOCAL}/include" \
  ../../OpenColorIO
````

**Comment by lgritz** [comment]
OK, if that works for you.

FWIW, I'm going to remove the lines that reference boost from dassert.h in the OIIO master branch, since it *can't* come into play any longer now that we're C++11 moving forward. If it is an issue for anyone in 1.7, I'm happy to alter 1.7 to also remove the boost refs (by making the STATIC_ASSERT do nothing when in non-C++11 mode).

**Comment by meshula** [comment]
That's great - the problem is double-solved for me then ;)
