### ISSUE TITLE
Failing to link dynamically to boost at runtime

### ISSUE THREAD

**Issue by alecjacobson** [OpenImageIO/oiio#1597]
I installed OpenImageIO via homebrew:

    brew install openimageio

A can successfully compile and link this program `test.cpp`:

```cpp
#include <OpenImageIO/imageio.h>

int main(int argc, char *argv[])
{
  OpenImageIO::ImageOutput *out = OpenImageIO::ImageOutput::create(argv[1]);
}
```

using:

    clang++ test.cpp -o test -lOpenImageIO

But if I run `./test`, I see:

```
dyld: Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/opt/openimageio/lib/libOpenImageIO.1.7.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/opt/openimageio/lib/libOpenImageIO.1.7.dylib
Trace/BPT trap: 5
```

I'm on Mac OS 10.11.6 running the built-in Apple LLVM version 7.3.0 (clang-703.0.31)

FWIW, I can compile, link and run the boost regex [grep example](http://www.boost.org/doc/libs/1_61_0/libs/regex/example/grep/grep.cpp).

How can I test my OpenImagIO install and figure out what's not linked correctly?

**Comment by tjwebb** [comment]
@alecjacobson did you figure this out?

**Comment by lgritz** [comment]
This kind of error (dyld shows a symbol not existing in boost) is usually the result of the boost and OpenImageIO in question not having been built with the same C++ standard (for example, OIIO compiled in C++11 mode while boost not compiled with C++11).

**Comment by alecjacobson** [comment]
No, unfortunately I never found a solution.

**Comment by lgritz** [comment]
You're installing from homebrew, right?

Do you desire the OIIO to be build for C++11 or C++03?

Try

    brew uninstall openimageio       # just to clear it out
    brew install -s openimageio

That will install from source. Presumably that will use the boost that's installed on your system, which hopefully will work better than using precompiled boost and oiio bottles from the homebrew archives, which may not match. But you may still have problems if the boost was not built with --c++11, I'm not sure.

If that still doesn't work, and you are willing to run from master rather than Release 1.7, you could instead try

    brew install -s --HEAD openimageio

or, alternately, just check OIIO master out of GitHub and build it yourself. In master (but I think not in 1.7), it is smart enough to realize you are using a new enough C++11 to contain std::regex, and will use that rather than relying on boost for its regex needs. Maybe that will do the trick. But again, only if you are ok using master.

**Comment by lgritz** [comment]
Closing, stale. Please re-open if there's still an outstanding issue.
