### ISSUE TITLE
Support for Python 3.6 os.PathLike objects (e.g. pathlib.Path)

### ISSUE THREAD

**Issue by skycaptain** [OpenImageIO/oiio#1598]
With [PEP 519](https://www.python.org/dev/peps/pep-0519/) Python 3.6 introduced a file system path protocol. Notably for most IO operations pathlib.Path objects now does not have to be casted into str objects. It would be nice to see this feature in OpenImageIO.

**Comment by lgritz** [comment]
Sorry for the delay responding.

That's a good idea, though I think it might be premature. Right now, most VFX studios are still on Python 2.7 (though everybody's looking to convert to Python 3 in the coming 1-2 years). I'm hesitant to restructure the APIs in ways that only work with Python3. Also, I think that there's no direct support in pybind11 for paths yet, so I expect it would take quite a bit of pipe-fitting to make versions of the API entry points that take paths, convert them to strings, then pass to OIIO (maybe someday OIIO will also make entry points that take std::filesystem::path rather than strings, but we aren't there yet).

Unless somebody wants to come forward to volunteer to do this work... I think that I'm inclined to close this issue for now as one we're not going to act on quite yet. But let's remember to revisit down the road when python3 is dominant among our audience and maybe by then pybind11 will also have added features to make path support extra easy.
