### ISSUE TITLE
python modules not installed

### ISSUE THREAD

**Issue by remusvrm** [OpenImageIO/oiio#1621]
Is there any reason way the python modules istitch.py, icrypt.py, etc ... are not installed when running "make install"? In the .../lib/python/site-packages is installed only OpenImageIO.so module.

### Versions

* OIIO branch/version: 1.6.18
* OS: CentOS 6
* C++ compiler: gcc 4.4.7

**Comment by lgritz** [comment]
The reason is that they were just examples in the early days of the Python bindings. They never were properly documented, never were tested in the testsuite, and have not been kept up to date with the changing APIs over the years. They very likely don't work at all.

I think the correct solution is to remove them entirely, and I will do so right away.

**Comment by remusvrm** [comment]
Thanks @lgritz for the explanation.

**Comment by calvinchang33** [comment]
Hi is this still true in September 2022? It seems that the https://openimageio.readthedocs.io/en/v2.3.19.0/pythonbindings.html#:~:text=You%20must%20ensure%20that%20the%20environment%20variable%20PYTHONPATH%20includes%20the%20python%20subdirectory%20of%20the%20OpenImageIO%20installation.

is missing from https://github.com/Correct-Syntax/py-oiio#:~:text=Copy%20the%20vcpkg%5Cinstalled%5Cx64%2Dwindows%5Clib%5Cpython3.10%5Csite%2Dpackages%5COpenImageIO.cp310%2Dwin_amd64.pyd%20file%20to%20oiio

If it is depreciated can you remove the documentation as it made the capabilities of oiio extremally misleading.
