### ISSUE TITLE
TIFF: TIFFTAG_XPOSITION is in Resolution units

### ISSUE THREAD

**Issue by devernay** [OpenImageIO/oiio#1623]
### Problem

oiio interprets TIFFTAG_XPOSITION/TIFFTAG_YPOSITION as pixel units:

- https://github.com/OpenImageIO/oiio/blob/master/src/tiff.imageio/tiffinput.cpp#L689
- https://github.com/OpenImageIO/oiio/blob/master/src/tiff.imageio/tiffoutput.cpp#L298

According to the TIFF 6 spec, they are in resolution units. they should thus be multiplied by X/YResolution and rounded to the nearest int.

TIFF files with valid TIFFTAG_X/YPOSITION can be produced by nona, part of Hugin http://wiki.panotools.org/Nona

see http://hugin.sourceforge.net/docs/manual/Panorama_scripting_in_a_nutshell.html for an example of using panotools and nona to produce these tiff files from a set of photographs forming a panorama

### Versions

* OIIO branch/version: 1.7.11 + master
* OS: all
* C++ compiler:  all

**Comment by devernay** [comment]
patch: https://raw.githubusercontent.com/MrKepzie/Natron/master/tools/MacPorts/graphics/openimageio/files/oiio-1.7.11-tiffposition.patch

**Comment by devernay** [comment]
just tested may patch with nona's output, and it works great (in Natron, all transformed images have the right position when read using oiio)

**Comment by lgritz** [comment]
Ugh, this is a tough one.

I think that you are technically correct, according to the spec. However, I suspect that the reason it's implemented this way is that as I was writing this module, there were already many examples of TIFF files out there that seemed to consider the XPOSITION and YPOSITION to be in pixel units, and none (at that time) that I could find that treated it correctly as in the RESOLUTIONUNIT. The fact that this the first time anybody has brought this up is consistent with the hypothesis that TIFF files out in the world tend to to have them in pixel units (or perhaps, not to use the field at all).

I don't have any good evidence one way or the other whether extant TIFF files that have the positions set are either always using resolutionunit "none", or are correctly scaling by the resolution unit.

My fear is that if we change the interpretation of this metadata, it will create a hopeless compatibility break that will wreak havoc -- apps with old OIIO will totally misinterpret the offset of TIFF files written with newer OIIO, and apps with new OIIO will misinterpret the offset of TIFF files written by older OIIO (or by non-OIIO apps that don't consider the resolution unit).

Can you point me to one of the images from the particular apps that seem to support scaling by the resolution unit? Do they leave anything else in the metadata that we can use as a reliable indicator that it comes from those few apps, and so we can do the divide by the resolution unit only for that case?

What I can certainly get behind is having OIIO's tiff OUTPUT write it "correctly" -- that is, if either XPOSITION or YPOSITION is nonzero, automatically setting resolutionunit to "none", so that offset will be interpreted correctly by all programs reading the file. (At the expense of not being able to simultaneously have a non-zero offset and a resolution unit other than none.)

But changing the interpretation of the input seems very risky to me.

(Aside: this would not be the first time we technically violate image format specs after finding that an overwhelming number of other programs do it wrong, and there is no alternative other than using the de facto interpretation rather than the original spec. I find this frustrating, but I don't know how to fix it.)

**Comment by devernay** [comment]
The fact that the position is a **rational** in the spec should be a strong hint that it is *definitely* not in pixel units.

nona, hugin and PTmender produce images with the correct position tags http://wiki.panotools.org/Nona http://wiki.panotools.org/Hugin http://wiki.panotools.org/PTmender
Those are *standard* tiff files with no extra tags (checked with `tiffdump`), so no way of identifying the source. The reason for the use of position tags, and how to set/read these, is fully explained in http://wiki.panotools.org/Cropped_TIFF

enblend reads images with the correct position tags http://wiki.panotools.org/Enblend http://enblend.sourceforge.net/ 

those are tools used internally by a huge family of PanoTools-based panorama software (commercial or open source): PTGui, Hugin and friends. I would say at least half of the professional-quality panoramas out there were produced using these tools (the only strong contender is Autopano).

The TIFF 6 Spec agrees with that.

GeoTIFF (as used by all GIS around the world) doesn't use X/YPosition, since it uses its own projection system, but clearly states that X/YPosition is in *device* space, not *raster* space, in its spec: http://geotiff.maptools.org/spec/geotiff2.5.html#2.5.1

Photoshop, Affinity Photo, Nuke and GIMP don't honor the position tags (just test by using the `tiffset` commands below to set the position to some value).

I think if there should be an exception, it should be the other way round, because so far all the evidences tend towards following the spec. If an application is known to have wrong position tags, then oiio could make an exception for this application, or there could be a paragraph in the documentation explaining how to fix these TIFF files. It's as simple as:
```
tiffset -s 286 <xposition_in_pixels/xresolution> <image.tiff>
tiffset -s 287 <yposition_in_pixels/yresolution> <image.tiff>
```

My guess is that *very few* applications actually use this tag, so why not assume they just do it correctly?

Which applications you know actually read or write these tags?

And which applications do it the wrong way?

**Comment by lgritz** [comment]
I completely agree that the intended meaning is for it to be in resolution units, and that the apps working that way are technically correct.

I'm merely fretting about what will break if we change things.

I have a feeling that a number of renderers have been using those fields in pixel units to describe the origin position for crop windows or overscan. I'll try today to check out Nuke and PRMan, for starters. Also, anything using OIIO will have been writing it "incorrectly", though hopefully those can be identified by looking at other fields (such as the "Software" metadata).

I'll open a discussion on the mail list. I want to give people a chance to figure out what would break and now to mitigate the problem. We can't just spring a change like this on people.

**Comment by lgritz** [comment]
@devernay, you say that Nuke ignores the field entirely? So does that mean that for an input image to be properly recognized by Nuke as a crop or overscan it needs to be OpenEXR, and that Nuke simply doesn't recognize non-zero origins of TIFF files?

**Comment by devernay** [comment]
Nuke simply ignores the xposition/yposition tags when reading tiff images. They do not affect the RoD in nuke and they do not appear in the metadata (whereas x/yresolution and resolution_units appear). You can easily check this by copying a tiff file and changing its origin using the `tiffset` commands above.

**Comment by devernay** [comment]
> We can't just spring a change like this on people.

The comment in the code said FIXME :-)
https://github.com/OpenImageIO/oiio/blob/master/src/tiff.imageio/tiffinput.cpp#L692

**Comment by lgritz** [comment]
OK, I'm pretty close to being comfortable with this.

I was under the impression that we were probably always outputting the XRESOLUTION, YRESOLUTION, and RESOLUTIONUNIT fields (and assumed they were set to some stupid default, like pixels are 1/72 inch). But upon inspecting the code and some files, it seems that we don't set these by default, unless specifically instructed to.

So I think that the vast majority of TIFF files will not have the RES fields set, and therefore the POSITION fields are already pixel space. So there are probably not many ambiguous files.

Let me prepare a patch to handle all this.

**Comment by lgritz** [comment]
So I found a case that is tricky. Although it seems that synthetic images typically don't put the RESOLUTION tags in their output, cameras DO. Digital cameras very typically save JPEG files with resolution (or density) tags, presumably so they have some reasonable default sizing behavior when printed or imported into a document.

So if you take a camera JPEG and convert it to TIFF via oiiotool (and certainly any OIIO-based code, and maybe others), the TIFF files will also probably carry along those resolution tags.

If you then crop the result, you'll have the dreaded combination of non-1 resolution and non-0 position, and that's the case where if we make this change, old OIIO and new OIIO will differ.

I'm preparing a patch, and one thing I do is look at the "Software" metadata for an OIIO version number. If it sees it's an old-oiio-written file, it will fall back to the old interpretation of the position. 

But it's still going to be wrong if it can't figure that out.

**Comment by devernay** [comment]
another question is: should crop really set the position?
isn't the intent of a crop to also shift the cropped area to the origin ?
that means a cropped tiff or exr will have a different interpretation than a cropped png, since its pixel data will lie somewhere else in raster space.
is there an option to *not* set the origin when cropping? should that be the default and should there be an option to set the origin when cropping instead?

**Comment by lgritz** [comment]
In oiiotool (and ImageBufAlgo) nomenclature, "cut" means to take a rectangle from an image and interpret it as now having (0,0) origin, whereas "crop" means to take a rectangle but keep it in its original position on the image plane (effectively, just discarding pixel data outside the crop region, but not moving it around).

To express it in OpenEXR language, cropping means adjusting the data window, but not "re-centering it" back to (0,0).

I like to think of it as having a big work table with a grid on it (the image plane), and images are like photographs you have lying on the table. "Crop" means you take your knife and trim the edges of one of those photos, but still leaving the remainder in its same location on the table (as if it were glued in place). "Cut" means trimming and then picking up the untrimmed remainder of the photo and physically moving it so that the its corner is touching the corner of the table.

For oiiotool, this distinction is carried out with --crop versus --cut. So people who want to both discard pixels AND then shift the remainder back to the origin, always have the option of doing so.

The reason you want a crop specifically is that you can take several different crops and then recombine them, and they will be in their original places relative to each other. Whereas if you "cut" them and then recombine, they will all be right on top of each other, if you know what I mean, having lost the information about where on the image plane they were before parts were trimmed away.

The original application of this was for rendering large images -- you could render just a small window on the screen (or maybe have different machines render different areas of the same image) and each one would know which part of the screen it covers by the POSITION, so they could be trivially reassembled into the original image. This behavior and interpretation of POSITION tags in TIFF files dates back at least to early-1990's era PRMan, and a whole bunch of other renderers that followed.

**Comment by devernay** [comment]
Sorry, I didn't know about crop vs. cut. You could have just redirected me to the doc!
On formats that don't support a data offset (png, jpg...), crop writes an image of the same size, with black outside of the crop region, which is the best possible behaviour.

But this wasn't clear in the doc. Maybe there should be a note in  the --crop paragraph of the oiio doc. It's not clear either in the doc about image writers how to handle the data window (or not).

**Comment by devernay** [comment]
thanks

**Comment by lgritz** [comment]
Sorry for the delay. This one kind of scared me because I really didn't know what it might break. I really wanted people to chime in one way or the other, but I suspect everybody was just as clueless about the ramifications. I guess we'll find out at some point if this introduces any subtle issues for people.
