### ISSUE TITLE
DPX read upside down

### ISSUE THREAD

**Issue by edubois** [OpenImageIO/oiio#1857]
### Problem

The provided DPX is read upside down.
[https://drive.google.com/open?id=1p5RWa4QNbbHmEMQAFbZd1n5QSey3sWh1](https://drive.google.com/open?id=1p5RWa4QNbbHmEMQAFbZd1n5QSey3sWh1)

**Expected behavior:**  read upside up

**Actual behavior:**  read upside down

### Versions

* OIIO branch/version: all versions
* OS: Windows
* C++ compiler: Visual Studio.

**Comment by lgritz** [comment]
I'll try to take a look at this today.

**Comment by lgritz** [comment]
I don't think that this is incorrect.

The image is stored "flipped vertically" in the file (note: it's reflected, not 180 degree rotated).

The OIIO convention is that as you read scanlines, you get them in the order that they appear in the file. This is the efficient thing for a reader such as the DPX reader to do -- you probably don't want to incur the expense of, for every scanline read, needing to re-seek and get a different scanline than what you asked for, in order to reorder it into the display order.

In cases like this, OIIO sets the Orientation metadata attribute, in this case to 4 to indicate a vertical flip is expected to display correctly. It's up to the app to use this extra information to display correctly. `iv`, for example, does this and thus displays the image "right side up" (as far as a human is concerned).

If you wish to actually re-orient the image (in the "move the pixels" sense, not just the "display it right" sense), you can do this:

    oiiotool upsidedown.dpx -reorient -o rightsideup.dpx

Does this help clear things up?

**Comment by edubois** [comment]
I will try to read the metadata, if it succeed, then I can definitely deal with this by means of boost::gil::flipped_up_down_view(srcView) without any cost.

**Comment by lgritz** [comment]
I'm going to assume that no follow-up means this answer was adequate. Closing.
