### ISSUE TITLE
Building from source requires internet connection for robinmap / pybind11

### ISSUE THREAD

**Issue by Shootfast** [OpenImageIO/oiio#1859]
Hi, 

Seems like some new dependencies have been added to OIIO master, and now builds require access to the internet in order to clone pybind11 and robinmap. Thanks to the MPAA we are not allowed to have our build servers connected to the internet. Can the dependencies on RobinMap and PyBind please be satisfied via FindPackage, as other OIIO dependencies are managed?

**Comment by lgritz** [comment]
For both of these (and any others we do this way in the future), it looks in ext/, and only if it's not already there, it downloads it. The ext/ directory is not erased by a "make clean" or "make nuke". So it will only need git access to the outside world the first time you build that it's not found. After that, unless you make the effort to remove what it downloads, it will keep using that original download.

We have the same constraints as you -- ordinary workstations can't talk to the outside world. But we have a combination of special machine+users that can have GitHib whitelisted. You need this combination to get the OIIO code itself, so at that time we do a clone or update of oiio, we also do the cmake setup, which auto-downloads these packages if they aren't already there. But once there, it stays until you take action to remove it.

I can also have the build them look more extensively in systems areas, if you think that's helpful. I suppose it might find pybind11 -- but do you even want the headache of worrying about what happens if your system pybind11 is different from the one oiio wants?

**Comment by lgritz** [comment]
Are you satisfied with the "you need to have internet access the FIRST time you make" answer?
Or is it substantially better to organize these as git submodules rather than downloads?

**Comment by lgritz** [comment]
Can we close this? As far as I know, the current status is:

* The current build files will find robinmap and pybind11 if installed on your system in any of the usual `CMAKE_PREFIX_PATH` directories or if you explicitly set ROBINMAP_HOME or PYBIND11_HOME (CMake variable *or* environment variable of that name).

* If not found in any of those areas, it will need internet to download, but only the first time it's built (it puts the results in the `ext/` subdirectory, which is not deleted by `make clean`. So you basically check those out that same first time that you need to download OIIO itself, and from then on, you can be disconnected from the net.

* I'm happy to accept patches to look in other places or do the search differently.

**Comment by lgritz** [comment]
Stale issue? Closing. Please re-open if it's a problem and we'll think about how to make it better.
