### ISSUE TITLE
[Feature request] Writing image file to a buffer without opening a file on disc

### ISSUE THREAD

**Issue by SylvainCorlay** [OpenImageIO/oiio#1895]
It seems that the `openimageio` API only allows writing to a file, but does not offer function to read and write to memory buffers.

We have a use case where data is not saved on disk, but sent as binary through communication channels (zmq sockets). We can always use a temporary file in the meantime but it would be much more convenient (and efficient) to not have to write anything on disk.

__Note__: For the record, this was [asked earlier](http://lists.openimageio.org/pipermail/oiio-dev-openimageio.org/2017-November/001088.html) on the mailing list by @wolfv.

**Comment by SylvainCorlay** [comment]
@lgritz this would be *really* cool if this was possible. We are using `openimageio` as a backend to load images in our tensor library `xtensor`.

One specific use case is in the context of the C++ kernel for the Jupyter notebook, where we can display rich content in the frontend

![mime-cpp](https://user-images.githubusercontent.com/2397974/37484634-6296c14a-2889-11e8-8a09-308844d72cc4.gif)

We also support Jupyter interactive widgets:

![widgets](https://user-images.githubusercontent.com/2397974/37484642-6a68a910-2889-11e8-9574-3d2d4f04ec19.gif)

Now, we have a few examples where we process the image using `xtensor` (think numpy for C++). The roundtrip to the file system is a bit lengthy...

**Comment by lgritz** [comment]
Are you asking for

(a) A particular ImageIO "format" that doesn't write anything to disk, but instead stores the pixel values in a memory buffer, but as far as an app is concerned, takes all the same ImageOutput API calls as usual?

(b) A general ability across all formats to intercept the ImageOutput calls and write the pixel values to an in-memory buffer? This is like (a) above, but works for any format. Essentially the ability to redirect any of the existing ImageOutput classes to instead behind the scenes give you the WriteToBuffer "format"?

(c) A general ability across all file formats to direct the very bytes that would have gone to disk (i.e., the TIFF or OpenEXR or GIF or whatever, the FILE ITSELF) to a memory buffer instead of a disk file?

I think that (a) is super easy, I could do it in an hour. Solution (b) isn't too bad, but we'd need to think of how to say "future requested ImageOutputs should be substituted with the special in-memory one". Solution (c) is really hard, because the individual underlying format-writing libraries (libtiff, libpng, libIlmImf, etc.) each have different and incompatible ways to substitute low level I/O functions, and some don't support such a thing at all.

**Comment by SylvainCorlay** [comment]
I was asking about (c), but that would be for PNG format only,  just for the front-end to display.

The main scenario would be "image to PNG memory buffer".

**Comment by SylvainCorlay** [comment]
Note, in the example above, I am base64-encoding the buffer but in the Jupyter protocol, I can send the raw PNG, so all what is needed is a means to write to a png buffer.

**Comment by lgritz** [comment]
So you want PNG specifically, and you want the buffer to be essentially the byte-for-byte in-memory copy of what would have been the PNG file on disk?

Would you assume that you pass it an existing buffer and length that you allocated and own, and it just fills it in (with an error if the file exceeds the length you allocated)? Or would you assume that it would allocate and manage the buffer and hand it back to you (with ownership) at the end of "writing" the image?

**Comment by SylvainCorlay** [comment]
> So you want PNG specifically, and you want the buffer to be essentially the byte-for-byte in-memory copy of what would have been the PNG file on disk?

Correct.

> Would you assume that you pass it an existing buffer and length that you allocated and own, and it just fills it in (with an error if the file exceeds the length you allocated)? Or would you assume that it would allocate and manage the buffer and hand it back to you (with ownership) at the end of "writing" the image?

I have not thought about it. I guess that if I don't have means to know how much should be allocated exactly, I would like the buffer to be allocated for me.

**Comment by lgritz** [comment]
I glanced at the libpng documentation and I think this is fairly straightforward. And I believe we can do it only for particular formats (PNG in this case) yet have a general API that allows for future support for other file formats, to the extent that they allow it and somebody wants to implement it.

The backlog of things requiring my own hands is way too long for me to tackle this right now. But if somebody else was interested in taking on the bulk of the implementation, I'd be very happy to explain the details of how it should be done, be available for any questions, offer suggestions, review the code, and get it merged. I don't think it's hard, maybe a day or two of work for somebody who is motivated by their own need for this feature.

**Comment by SylvainCorlay** [comment]
Thanks. I understand you are busy!

I might not be able to do this right away, but we will probably get a stab at it when we get the time.

**Comment by lgritz** [comment]
Me, too. It's so close to being "easy" that I'm very tempted to just try it and see if I can knock it out in a couple hours... except that there are just too many other people for whom it would be unfair to not give my long overdue time, just because it looks fun to try. :-)

How about this: whichever of us actually gets some time to dive in, post here FIRST, so the other knows at least not to work on it simultaneously.

I'll post later tonight or this weekend with an outline of how I think it should work, and maybe that will also clarify the amount of work that it really is.

**Comment by lgritz** [comment]
I've got an hour or so to kill. Let me give this a try. If I can make it work, great. If I'm not even close after two hours, I'm going to leave it for much later, or somebody else.

**Comment by lgritz** [comment]
The good news is that I got this working yesterday. 

But I realized only after I'd done it that I didn't clarify with you if you if it was ok for it to only work from the C++ API (what I did), or if you needed it to work from Python as well (which is much more awkward).

**Comment by lgritz** [comment]
Also: This is the kind of entirely new behavior that would ordinarily only go in master and therefore be in the NEXT major release, rather than be backported to the current release branch. Is that sufficient? Or is it important to you to get it in the current (1.8) release?

**Comment by SylvainCorlay** [comment]
@lgritz awesome! Fortunately, I don't need this from the Python API.

Regarding the version in which this should go, it does not matter that it would be a `1.8.x`. What is the logic that you are following for the version numbering? Is it semver?

**Comment by lgritz** [comment]
It's not *exactly* semver, but it's close in spirit.

True semver is X.Y.Z where Z increments are bug fixes only, Y can add features but not break backwards compatibility, and X increments are allowed to break compatibility.

In our versioning, X.Y is the "major release" where anything can happen, and .Z is the minor release which is a combination of bug fixes and backwards-compatible (but "low risk") additions.

Right now, the current stable release is the 1.8 family (1.8.9 is the latest tagged release, 1.8.10 is scheduled for Apr 1). The 'master' branch where risky development is allowed to happen will one day become the 1.9 release.

**Comment by lgritz** [comment]
I believe that this feature has been implemented in #1931, at least for PNG and OpenEXR, and could be expanded to other formats as needed. Closing.
