### ISSUE TITLE
Wrong TIFF PixelAspectRatio

### ISSUE THREAD

**Issue by riviera-kid** [OpenImageIO/oiio#1909]
### Problem 

TIFF files generated by Maya playbast have in OIIO wrong pixel aspect ratio.
See attached image (correct aspect ratio should be 1.0).

BTW Is the aspect pixel aspect ratio feature supported by TIFF spec?
Or it should be always 1.0?

[shot_001.cap_test.lr.capture.v001.mdusek.0001.tif.zip](https://github.com/OpenImageIO/oiio/files/1852738/shot_001.cap_test.lr.capture.v001.mdusek.0001.tif.zip)

### Versions

* OIIO branch/version: 1.8.9
* OS: Win10 x64
* C++ compiler: MSVC 2017

**Comment by lgritz** [comment]
Nomenclature is hard for things like this.

As for your file,

* The image is 960x540 pixels
* The TIFF XResolution and YResolution tags are 1 and 0.5625, which imply that the pixels are a just a little bit more than 1/2 as wide as they are high. (Those numbers are like pixels per inch, they are unitless, but the point is that smaller numbers are BIGGER pixels, because it's a "per unit distance" measure.)
* OIIO master (`oiiotool -info -v shot_001.cap_test.lr.capture.v001.mdusek.0001.tif`) correctly reports the resolution values, as well as an overall "PixelAspectRatio" metadata of 0.5625. 
* With this ratio, the image, although 960x540, ought to display as SQUARE, and the object should look like a sphere, not an ellipsoid. And indeed, it does so when I use Apple's Preview.app.

This appears to work for both OIIO master as well as the current tip of RB-1.8 (that's slightly ahead of 1.8.9, but I don't see any commits since then that would have affected pixel aspect ratio metadata).

So... can you describe in more detail the exact steps you are taking and at what point you think something is incorrect?

**Comment by riviera-kid** [comment]
To be clear, I'm talking about the PixelAspectRatio metadata.

I think it should be 1 for that image instead of 0,5625 (=540/960).
I'm using the pixel aspect to scale the image to be displayed correctly.

For example:
If you have an 720x576 PAL 16:19 (pixel aspect 1.46), it should be scaled:
[test.zip](https://github.com/OpenImageIO/oiio/files/1853837/test.zip)
(created in Nuke)

So the PixelAspectRatio should be use for the EXR but not for the TIFF from Maya...
(I'm now using a workaround - just ignoring the pixel aspect for all TIFs, because the nonsquare TIFs are rare)
I think that the interpretation XRes and YRes tags as pixel aspect is not correct and it is ignored by most of image viewers. But I'm not a TIFF expert...
BTW this is from Windows 10 desktop preview :) 
![win10](https://user-images.githubusercontent.com/7337247/37995943-54b4a95c-3216-11e8-85eb-c793cfc006d5.jpg)


Thanks

**Comment by lgritz** [comment]
"Pixel aspect ratio" refers to the shape of each pixel as captured or displayed. I guess different formats or APIs can disagree over whether 0.5 ought to mean that the pixels are "fat" or "skinny" (OIIO thinks skinny!), but there is no doubt that 1.0 indicates a "square" pixel and vice versa, i.e. where pixel density is equal in x and y when printed or displayed. If you believe that your image does not have evenly spaced pixel samples, then an aspect ratio of 1.0 is certainly wrong.

The TIFF specification is clear that the XResolution and YResolution TIFF tags refer to the density of pixels in the width and height directions, respectively. It's a density, not a size, so it is measured in "pixels per resolution unit". And thus, it must be that our PixelAspectRatio is YResolution/XResolution. (TIFF doesn't directly store PixelAspectRatio tag, it is implied by the [XY]Resolution tags, and so that's how OIIO is computing it and presenting as the "PixelAspectRatio" metadata.)

It wouldn't surprise me at all if there were applications that read TIFF files and don't notice or respond to the resolution tags when displaying, or for that matter if there were non-OIIO-based applications that write TIFF files with incorrect tags. 

Perhaps I am still confused, but for your 960x540 image example, do you intend that it should display with the object looking like a sphere, or like a thin ellipsoid? When I display your example with Apple's Preview.app, it looks spherical. (In general, when it comes to correct display of imagery, I'm inclined to bet that Apple's preview is correct and Windows is wrong, rather than the other way around.)

**Comment by riviera-kid** [comment]
The sphere is correct, but only if displayed as square pixel data ~1.0 pixel aspect ratio.
For the 0.5 it should be displayed as an elipsoid...
So I think that the XRes/YRes is ignored by Apples preview, Nuke, Irfan View and probably most other viewers. The Windows 10 preview shoes the elipsoid - pixel aspect nonsquare.

This is TIF has been created by Nuke - 720x576 and aspect set to 16:9
[pal.zip](https://github.com/OpenImageIO/oiio/files/1857644/pal.zip)

See the xres/yres - it is 72/72 -> pixel aspect 1.0 in oiiotool.
But when I open this image in nuke it is really displayed as 16:9 (the checker is "square - pixel aspect 1.46). The same image opened in irfan view - it is rectangle (pixel aspect 1).
It is really strange :)

**Comment by lgritz** [comment]
Oh, ok, I see what you mean. This is a confusing test, and it didn't help that I only tried viewing it with Apple preview.

If you just forget OIIO, leave it out of the loop entirely,

    tiffinfo shot_001.cap_test.lr.capture.v001.mdusek.0001.tif

it will reveal that the TIFF tags are

    Resolution: 1, 0.5625 (unitless)

So Maya itself added the resolution tags. Why would it do that, if the pixels are supposed to be square? The TIFF spec could not be more clear that the X and Y resolution tags should be the same value (or not present at all) if the image is supposed to have square pixels.

All OIIO is doing is turning the existing TIFF XResolution & YResolution tags into the "PixelAspectRatio" metadata.  I'm not sure what else it can do, unless you think that it should never recognize pixel aspect ratio at all.

So I was wrong about my bet, I now see!  It seems that Apple Preview.app is ignoring the TIFF XResolution and YResolution tags and displaying square pixels no matter what, while Windows 10 is (correctly!) honoring that metadata. Again, this is all without OIIO being in the loop at all.

**Comment by riviera-kid** [comment]
I've just edited the post - the Arnold renderer doesn't set the xres/yres - see the image. It could be maya bug, but I'm not sure if "anybody" is really interpreting the xres/yres as pixel aspect - seems that only Windows 10 :)

**Comment by lgritz** [comment]
What app wrote the file? Somebody instructed it to set those XResolution & YResolution tags. An app that is unaware of it will just leave them blank (defaulting to a 1.0 aspect ratio). 

I think that if you have a file in which the pixels are supposed to be square, but the app that wrote the TIFF file put something other than equal XResolution and YResolution values, then it is that app that is broken.

**Comment by riviera-kid** [comment]
I'l probably report it to Autodesk as Maya playblast bug, because it really writes XRes/YRes as an image resolution ratio regardless the pixel aspect ratio setting.
For now I can probably be using a common workaround - ignoring the pixel aspect for all TIFF files. Non square TIFs are in production rare and for the EXRs it works well...
