### ISSUE TITLE
Incorrect image when tile size isn't multiple of image size

### ISSUE THREAD

**Issue by Blackhart** [OpenImageIO/oiio#1911]
### Problem

When filling the ImageSpec structs with incoherent tile size and image size, I get a corrupted/undesirable image.

For example:

tile size: 32x32 | image size: 62x62
tile size: 32x32 | image size: 2x2

**Expected behavior:**  

In the first case, the tiles must fit to the image size. In other word, tile size should be resized according to image size.
=> Maybe the first tile can be of size 32x32 and the second one can be 30x30.

In the second case, it should have only one tile of size 2x2.

**Actual behavior:**  

In these both cases, some pixels at the end of the image are skiped (and so, has incorrect values). 

### Steps to Reproduce

1. Create an ImageSpec.
2. Fill the field tile size and image size of the ImageSpec with the values given in my previous example.
3. Write an exr file with the `write_tile()` method.

### Versions

* OIIO branch/version:  1.7.10
* OS:  Windows 10
* C++ compiler:  Visual studio 14 2015

**Comment by lgritz** [comment]
You don't actually give repro steps that I can directly follow, so I'm assuming you are talking about software you wrote that is making the OIIO calls.

I'm not 100% sure that this isn't a flaw in OIIO itself, but I suspect that the problem is on your end.

    oiiotool -pattern checker 62x62 3 -d half -tile 32 32 -o out.exr

reveals that OIIO is certainly capable of producing a correct tiled exr file even when the image size is not a whole multiple of the tile size.

I tested on master, and 1.8, and the most recent version of 1.7 (though not quite as old as 1.7.10, just because software upgrades and whatnot make it a bit of a pain for me to currently compile 1.7.10 on my current machine).

The first thing I'd encourage you to try is to see if you can build your software against a more current releases (1.8.10 is the most recent stable production release) or even against master, just to see if it's a bug that has already been fixed.

If that doesn't help, they I would request that you try to create and post here the shortest possible C++ program that  reproduces the issue. I bet I can spot the problem with it (probably you are not understanding how the stride parameters to the write_tile call are supposed to work in cases of partial tiles -- it's tricky and I get that wrong sometimes, too). But if not, and it really is an OIIO bug (a distinct possibility), it will give me a very focused case to examine to track it down.

**Comment by Blackhart** [comment]
Hi lgritz,

Thanks for your answer.

I'm working on the integration of OpenImageIO into Appleseed, which is a software renderer.
Unfortunately, too heavy for debugging purposes ...

So, I made a small program (with pre-built binaries for a complete OpenImageIO 1.7.10 usage for VS2015).
Here is the link of the git repo: https://gitlab.com/Blackhart/oiio_sandbox
Just compile it by calling `compile.sh` in your command shell :).

It enable you to produce an openexr image of size 2x2 with tile size set to 32x32. The produced image show the two first pixels set with red color (desired color) and the last two pixels are skipped by OpenImageIO ...

As you tell me, maybe I misunderstand the `stride` parameters ?!

I'll test with a most recent version ...

Thanks a lot.

**Comment by lgritz** [comment]
The problem is this statement:

            if (!m_writer->write_tile(
                    static_cast<int>(tile_offset_x),
                    static_cast<int>(tile_offset_y),
                    0,
                    OIIO::TypeDesc::UINT8,
                    tile.buffer))

The signature of write_tile is:

    bool write_tile (int x, int y, int z, TypeDesc format,
                             const void *data, stride_t xstride=AutoStride,
                             stride_t ystride=AutoStride,
                             stride_t zstride=AutoStride);

The optional stride parameters default to a special value `AutoStride` which means for `write_tile()` to assume it is pointing to a data buffer whose layout is the size and shape of a contiguous full tile. In fact, to quote the explanatory comment in `imageio.h`:

    Strides set to AutoStride imply 'contiguous' data in the shape of a full tile, i.e.,
         xstride == spec.nchannels*format.size()
         ystride == xstride*spec.tile_width
         zstride == ystride*spec.tile_height

So, in this case your data buffer is NOT the same layout as a full tile, so you can't rely on the defaults and need to pass the strides explicitly. 

I believe the correct code would be:

            stride_t xstride = m_spec.nchannels * sizeof(uint8_t); // because your buffer is UINT8
            stride_t ystride = xstride * std::min (m_spec.width+m_spec.x-tile_offset_x, m_spec.tile_width);
            if (!m_writer->write_tile(
                    static_cast<int>(tile_offset_x),
                    static_cast<int>(tile_offset_y),
                    0,
                    OIIO::TypeDesc::UINT8,
                    tile.buffer,
                    xstride,
                    ystride))

Does that help?

**Comment by Blackhart** [comment]
Hi lgritz,

It does! I misunderstood the stride parameters.
Sorry for that waste of time and thanks for your explanation!

We can close this issue.
