### ISSUE TITLE
oiiotool --text for timecode

### ISSUE THREAD

**Issue by tiltX** [OpenImageIO/oiio#2063]
### Problem

It seems as if there is no way to use oiiotool to write the timecode metadata as a human-readable string (HH:MM:SS:FF) onto the image. I have tried the following command line arguments:

    --text {TOP.smpte:TimeCode} 
This works, but it writes the integer representation

    --text {TOP.input/timecode}
Nuke writes a metadata key called "input/timecode" into OpenEXR files that contains the timecode as a string. However, this can't be printed because oiiotool wants to treat this as an arithmetic division.

    --text {TOP.timecode}
    --text {TOP.TimeCode}
Results in an "unknown attribute" error.

    --sattrib my_timecode {TOP.smpte:TimeCode} --text {TOP.my_timecode}
This also prints a number instead of a string.

    --attrib:type=timecode my_timecode {TOP.smpte:TimeCode} --text:size=100 {TOP.my_timecode}
This also prints a number instead of a string.

**suggested syntax:**  

    --text {TOP.timecode}

In my opinion, this would be a good solution to print the human-readable timecode string (for example "01:00:00:00"). It would match the current syntax for "built-in" attributes like width or height and it wouldn't change the current result of {TOP.smpte:TimeCode}.

The metadata key _timecode_ is already treated in a special way when using --attrib: it seems as if you can use "timecode", "TimeCode" or "smpte:TimeCode" to set the timecode when writing OpenEXR files, so there doesn't seem to be a way to actually generate a metadata key called "timecode" using OIIO. But just in case there is such a metadata key generated by a 3rd party application, the suggested syntax should obviously print that attribute instead of what's stored in "smpte:TimeCode".

### Versions

* OIIO branch/version: 1.8.10
* OS: CentOS

**Comment by lgritz** [comment]
Quite right. I have a patching coming up shortly to address these shortcomings.

**Comment by lgritz** [comment]
The proposed fix is #2068 and it's been merged into the master/RB-2.0 branches. Since the 2.0 release is imminent, I'm really planning to backport to 1.8 unless specifically requested (it touches a few things).

The result is that you can use single or double quotes to enclose a metadata name when using it in an expression, if it is not in the form of a "C identifier". For example,

    --text {TOP.'input/timecode'}

will look up the metadata "input/timecode", not "input" and divide by timecode.

Also, expression lookups of Timecode values will return a reasonable string representation ("00:00:00:00") rather than the raw integer values. Hopefully this does everything you need. Let me know if there are any problems, or if you need a backport.

**Comment by tiltX** [comment]
Thank you, that was fast. I haven't tried compiling the 2.0 branch yet but seeing that the minimum requirements haven't changed since 1.8 I'll give that a try asap.
