### ISSUE TITLE
resizing images of type double

### ISSUE THREAD

**Issue by asuter** [OpenImageIO/oiio#2210]
https://github.com/OpenImageIO/oiio/blob/b32cc4eddef22f84ee6b92a821dad452b331650e/src/libOpenImageIO/imagebufalgo_xform.cpp#L235

Hey,

Thanks again for the wonderful library. We're probably outliers using doubles in our particular workflow.

This pel variable being type float* seems to cause just enough of a precision error in my resizing an image of type double to show up in the unit tests. (A value is 1.0000012 instead of 1.0000000). If I change it to type double it works great. 

Would making it double cause too many issues elsewhere? It seems to scale with the number of channels rather than the number of pixels, but maybe there's memory issues I'm not thinking of. It could also possibly be templated to DSTTYPE, with possible issues with lower bit-depth types.

                      -- Alex

**Comment by lgritz** [comment]
Yeah, taking a quick look, I think that the right way to deal with this (to not accidentally inject any performance hit for the common case of float or less precision) is to use template magic to use double when DSTTYPE is double, and float otherwise.

Let me see what I can cook up.

Are you confident that it's just this "accumulator" that needs to be double (for the double case) and the other float variables in this function can safely stay float?

Aside: Needing double is not super common in CG, certainly not where image data is concerned, so I'm sure there are lots and lots of places where I've used "float" even in templates that might be instantiated for doubles. This may not be the last time we come across this kind of issue, but I"ll try to fix it right away when you find those spots.

**Comment by lgritz** [comment]
See #2211 for proposed fix. Can you try that on your end and verify that it solves your precision issue?

**Comment by asuter** [comment]
Solves it!

In my testing, only the accumulator is impacting the final precision for resize. The rest seem to be ratios of widths and the like, not impacting the raw data. I've only hit this with resize so other algo functions might have issues, but this is a huge help. Thanks!
