### ISSUE TITLE
RB-2.2 - Compilation warning fixes - VS2017 & VS2015

### ISSUE THREAD

**Issue by hodoulp** [OpenImageIO/oiio#2246]
Here are three patches to fix some warnings with **VS2017** (and VS2015) and the branch **RB-2.2**. 

When compiling OIIO I did not see them. But these warnings were present when compiling OCIO with VS2017 & VS2015. So I built these patches to avoid disabling some compiler flags in the OCIO project. They all seem to be easy fixes but some could highlight precision concerns (i.e. simd.h). So, please carefully review them before changing the OIIO code.

[fmath_h_patch.txt](https://github.com/OpenImageIO/oiio/files/3242257/fmath_h_patch.txt)
[simd_h_patch.txt](https://github.com/OpenImageIO/oiio/files/3242134/simd_h_patch.txt)
[ustring_h_patch.txt](https://github.com/OpenImageIO/oiio/files/3242135/ustring_h_patch.txt)

**Comment by lgritz** [comment]
Thanks, Patrick. I'll turn this into a PR and get it integrated.
I'll test everything and make sure there are no problems for precision.

**Comment by lgritz** [comment]
ustring: very embarrassing, but the real fix is simply that the return type of stof ought to be float, not int!

fmath: I don't quite understand what the fix is. What warning did you get here? Why did it need const? I'm happy to make these changes, I just don't understand why they are warnings in the first place.

**Comment by hodoulp** [comment]
fmath: Only the `float` cast on `q` is needed. The const keywords were leftover from previous changes i.e. not mandatory.
