### ISSUE TITLE
[BUG] ImageBufAlfo.render_text() returns a bool, not an ImageBuf object

### ISSUE THREAD

**Issue by dovanbel** [OpenImageIO/oiio#2354]
**Describe the bug**
`oiio.ImageBufAlfo.render_text()` returns a bool instead of an ImageBuf object

**To Reproduce**
Here's a snippet of my python script :

```
buf = oiio.ImageBuf(frame)
print ('first buf', buf)
buf = oiio.ImageBufAlgo.render_text(buf, 0, 0, "dddd")
print ('second buf', buf)
```
This prints this :

```
first buf <OpenImageIO.ImageBuf object at 0x000000000EF8D500>
second buf True
```
So the buf variable holds an ImageBuf object at first, but after using the render_text method, instead of an ImageBuf object, I get a bool. What did I do wrong ?

**Expected behavior**
I would expect the `render_text()` method to return an `ImageBuf `object

**Platform information:**

I built OpenImageIO using vcpkg. Here's parts of the portfile.cmake file :

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO OpenImageIO/oiio
    REF ad1ab61a56c63d770e4beb335efe8b1f1a9e36cd
    SHA512 48ee7862583e7adb86b56b20634c34aebf83ef0a3a14ad96182494ce6a84cb027334840a6c4c335e9342110c3a36532e3eeae22a3ed7363cd91b27cb7ca58154
    HEAD_REF master
    PATCHES
        fix_libraw.patch
        use-webp.patch
        remove_wrong_dependency.patch
        use-vcpkg-find-openexr.patch
```
I did change a few values inside the portfile, for instance :
```
-DUSE_FREETYPE=ON
-DUSE_PYTHON=ON
```
)
 - OIIO branch/version:
 - OS: Windows 10 x64

**Comment by lgritz** [comment]
It's not a bug.

render_text() modifies an existing buffer, rather than return an entirely new image. The render_point, render_line, and render_box methods work this way, too, and this is different from the majority of ImageBufAlgo methods that treat the inputs as nondestructive and return a new image.

So the correct code in this case would be

    buf = oiio.ImageBuf(frame)
    oiio.ImageBufAlgo.render_text(buf, 0, 0, "dddd")

The reasoning here is that something like render_text (and certainly individual points, lines, etc.) are probably just one step in a long series of calls -- for example, writing lots of pieces of text in different places in the image, and you don't want to make a full copy of the image for every individual word, line segment, etc. That would be very expensive.

**Comment by dovanbel** [comment]
Thanks a lot for the explanation.  I got it working thanks to your help.
