### ISSUE TITLE
[BUG] wrong EXR merge

### ISSUE THREAD

**Issue by kuzynsyna** [OpenImageIO/oiio#2485]
I try merge multi images in one.
I use Python openimageio 2.1.11 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#openimageio, Python 3.8.1 

```
import OpenImageIO as oiio

image1 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0000_.0001.exr")
image2 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0001_.0001.exr")
image3 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0002_.0001.exr")
image4 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0003_.0001.exr")
image5 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0004_.0001.exr")
image6 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0005_.0001.exr")
image7 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0006_.0001.exr")
image8 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0007_.0001.exr")
image9 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0008_.0001.exr")
image10 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0009_.0001.exr")
image11 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0010_.0001.exr")
image12 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0011_.0001.exr")
image13 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0012_.0001.exr")
image14 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0013_.0001.exr")
image15 = oiio.ImageBuf("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\Heat_BLANKET_02_RF_s0014_.0001.exr")


spec = image1.spec()
w = spec.width
h = spec.height

goal_width=w
goal_height = h*15

new_im = oiio.ImageBuf(oiio.ImageSpec (goal_width, goal_height, spec.nchannels, spec.format))
oiio.ImageBufAlgo.resize(new_im, image1)

y=0
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image1)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image2)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image3)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image4)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image5)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image6)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image7)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image8)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image9)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image10)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image11)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image12)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image13)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image14)
y+=72
oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image15)


new_im.write("D:\\_TESTY\\20896_AUTO_DATA_WINDOW\\200115_Adidas\RENDERS\\Heat_BLANKET_02_RF_T6\persp1\wynik.exr")
```

it's working for png, but not for EXR. For EXR images are moved. for EXR working if  y=0 always.

**Comment by lgritz** [comment]
I think that is the right behavior if your individual exr images already encode their relative position in the overall image.

PNG doesn't have that ability, so each of the individual PNG pieces will think its own origin is (0,0), so you have to offset it when you paste into the master copy.

OpenEXR has metadata (called the "data window" in OpenEXR, but often in OIIO docs we call it the pixel data origin). So if your image2 already knows its data window starts at (0,72), then the `paste()` command should take an offset of 0, not 72. You are just placing the image down at the origin it already knows about, you do not need to offset it. I hope my terminology is clear.

You can verify if my hypothesis is true by using `oiiotool -info -v image.exr` on your image slices and see what it says about "pixel data origin").

So if you know you are working with openexr images that each already have the correct data origin for its final placement, then you can just eliminate the y increments, like this:

    ...
    oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image12)
    # NO   y+=72
    oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image13)
    # NO   y+=72
    oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image14)
    # NO   y+=72
    ...

An alternative is to manually reset the origin of each piece to 0 before you paste it, and then the code will work identically for file types that understand their origin, as well as those that do not. But you have to be 100% certain that the individual files really do have the origins you expect, since you're overriding their inherent knowledge of where they fit in the overall picture.  For example,

    ...
    image12.specmod().y = 0;   # reset origin
    oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image12)
    y+=72
    image13.specmod().y = 0;   # reset origin
    oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image13)
    y+=72
    image14.specmod().y = 0;   # reset origin
    oiio.ImageBufAlgo.paste(new_im, 0, y, 0, 0, image14)
    y+=72
    ...

This may be extra confusing because the `paste` behavior was changed in OIIO 2.1, and here's how the release notes described it:

- `--paste` semantics have changed: the meaning of pasting FG into BG at
  (x,y) now means that the (0,0) origin of FG ends up at (x,y), whereas
  before it placed the corner of FG's data window at (x,y). This will
  not change behavior for ordinary images where FG's data window is (0,0),
  but it makes behavior more sensible for "cropped" or "shrink-wrapped"
  FG images that have non-zero data window origin. #2369 (2.1.5)

**Comment by kuzynsyna** [comment]
Now working with "image14.specmod().y = 0;   # reset origin". With the earlier version(1.6.18) my code works ok. 
Thanks for the help. 
Subject to close.
