### ISSUE TITLE
[BUG] Something weird in PSNR calculation?

### ISSUE THREAD

**Issue by FrancoisBeaune** [OpenImageIO/oiio#2496]
**Describe the bug**

In [imagebufalgo_compare.cpp line L286](https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/imagebufalgo_compare.cpp#L286), the variable `maxval` (which is used to keep track of the largest component value found in either image being compared) is initialized to `1.0`, meaning that it will assume that the max value is at least 1.0 when in reality it could be a lot smaller. Shouldn't it be initialized to 0.0, or some arbitrary negative value?

`maxval` is only used to compute the Peak SNR value.

**To Reproduce**

N/A

**Expected behavior**

N/A

**Evidence**

N/A

**Platform information:**

 - OIIO branch/version: master

**Comment by lgritz** [comment]
I have to admit that I don't remember what I was thinking when I wrote this (or, frankly, if it was even me who wrote it -- it's hard to trace the full history of this line, because the function moved between .cpp files at some point, and I'm too lazy to start checking out versions from the early 2010's to try to figure out the origins).

But here is my guess:

See this explanation of PSNR: https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio

Relevant text: "Here, MAXI is the maximum possible pixel value of the image. When the pixels are represented using 8 bits per sample, this is 255.

OIIO deals with everything normalized, we never talk about "255" because that's a stupid artifact of the particular encoding. The 255 code value in a uint8 image *represents* 1.0, just like in a uint16 image, the code value 65535 represents 1.0.

Consider that if you had A_uint8.tif and B_uint8.tif and converted them to A_uint16.tif and B_uint16.tif, and A_float.exr and B_float.exr. Clearly it would be desirable to have the A vs B difference metric to be the same regardless of which data type we stored the values in, right? 

So our "maximum possible value" should be 1.0, regardless of data type, and of course all the math should be on the normalized values.

But, wait... what is the right max value to use for an HDR (float) image? The maximum possible value is infinity (or MAXFLOAT maybe?), but that's clearly a useless value to plug into this formula if we want it to be a helpful metric. 

So it seems that the rule I'm implementing is this: Use 1.0 as the "max" except in the case that they are HDR images that actually contain values > 1.0, in which case punt and use "max" equal to the actual highest value found in either image.

If you think my logic here is flawed, or if you have a better heuristic to use for how to apply the PSNR formula to HDR images, I would love a suggestion.

**Comment by FrancoisBeaune** [comment]
Thanks for the explanation Larry, it makes sense (and it probably deserves to be put in the code).

I'm not sure there's a better way to define PSNR when the signal's maximum value is unbounded. Maybe in that case (non-peak) SNR is better suited?

**Comment by lgritz** [comment]
Yeah, good point, I will add this explanation as a comment.

**Comment by lgritz** [comment]
There are probably better image comparison metrics we should be using, especially for HDR images.

**Comment by lgritz** [comment]
Closing. Comment added to code.
