### ISSUE TITLE
[BUG]Error with concurrent reading jpeg files from IOMemReader

### ISSUE THREAD

**Issue by etsach** [OpenImageIO/oiio#2544]
**Describe the bug**
I'm accessing a JPEG texure through TextureSystem and ImageCache multiple times, in several concurrent threads. The JPEG file is first loaded to a memory buffer, and added to the image cache using IOMemReader proxy.

**To Reproduce**
Simple test program attached : it loads the JPEG file in memory, and adds it with a proxy to the TextureSystem underlying ImageCache. Then, multiple threads are started (as much as hardware concurrency) and lookup the texture through the TextureSystem.

[bug-2544.zip](https://github.com/OpenImageIO/oiio/files/4444783/bug-2544.zip)

**Expected behavior**
It shouldn't produce any error and always give the same output

**Evidence**
Random error messages : 

> Could not open file "membuffer-grid.jpg"

The code works sometimes. It always works properly with a single thread, the problems get more frequent with more threads.
The issue also happens when OSL is in the loop, with more explicit error messages through the error handler, such as:

> Error:[RendererServices::texture] Could not open file "membuffer-grid.jpg"
> Error:[RendererServices::texture] JPEG error: Improper call to JPEG library in state 0 ("membuffer-grid.jpg")
> JPEG error: Improper call to JPEG library in state 0 ("membuffer-grid.jpg")
> JPEG error: Improper call to JPEG library in state 0 ("membuffer-grid.jpg")

**Platform information:**
 - OIIO 2.1.10
 - OS: ubuntu 18.04
 - C++ compiler: clang 7
 - Any non-default build flags when you build OIIO:
`cmake -DCMAKE_CXX_FLAGS="-Wno-macro-redefined"`

**Comment by etsach** [comment]
I believe this issue is due to IOProxy which cannot be shared between threads. The internal state (file handle or memory pointers) can not be used by multiple threads, even if we add locking.
It's not an issue in the common use case, when no oiio::ioproxy parameter is set, since the InputImage then creates a local, non shared IOFile class.

Here are two possible fixes I can  see:

1. Create a IOProxyFactory class. Add an  "oiio::ioproxyfactory" parameter to ImageSpec to pass a pointer to an IOProxyFactory. Modify input plugins, so that they look first for an IOProxyFactory before an IOProxy, and if they find one, use it to create an IOProxy local to the ImageInput. Specify in the documentation that oiio::ioproxy can't be used if the texture will be read from multiple threads, for instance through an ImageCache

2. Add a "clone" virtual method to IOProxy. Modify input plugins so that they never directly use the value of "oiio::ioproxy" in InputImage subclasses, but clone it first locally. This is just an integration of the factory role inside the class itself.

3. Turn the IOProxy class into a factory, without changing its name, remove all io methods from it, and add an "open" method which creates an IOProxyInstance object, having the purpose of the former IOProxy class.


I prefer by far method (3) which does not require any action from library users, if they use the stock IOProxy subclasses (IOFile, not really useful, and mostly IOMemBuffer). 
But, this will break code subclassing IOProxy for custom IO, and clutters the API a bit more.

Method (1) does not break anything, but doesn't fix anything without user action, which need to use oiio::ioproxyfactory everywhere it was using oiio::ioproxy before

Method (2) is the less disruptive but is sketchy and will leave the mess in place for current code.

**Comment by lgritz** [comment]
I don't think your analysis is correct.

A FILE* is also inherently not thread-safe because it has internal state. We don't open a separate file for each thread, or clone the file handle. The format readers that rely on ordinary file reads also need to be careful with mutexes and whatnot to make thread-safe behavior out of a non-thread-safe primitive underneath. Using IOProxy is no different in this respect.

No, there is a specific bug here that we will find. Working on this today.

**Comment by lgritz** [comment]
Thanks SO MUCH for your example. I am able to repro and am working on the problem. Stay tuned.

**Comment by lgritz** [comment]
Aha, I understand the problem. It's not about multithreading at all (except that multithreading can lead to the scanlines being needed in random order).

Here is the problematic code, in JpgInput::read_native_scanline:

    if (m_next_scanline > y) {
        // User is trying to read an earlier scanline than the one we're
        // up to.  Easy fix: close the file and re-open.
        ImageSpec dummyspec;
        int subimage = current_subimage();
        if (!close() || !open(m_filename, dummyspec)
            || !seek_subimage(subimage, 0))
            return false;  // Somehow, the re-open failed
        OIIO_DASSERT(m_next_scanline == 0 && current_subimage() == subimage);
    }

So, if you need to backtrack, it closes and reopens the reader. But... it is not calling the version of open() that takes the config spec that communicates the proxy! So after it closes, it re-opens fresh expecting to find the image in a FILE, which of course does not exist.

This is not a flaw with IOProxy per se. It's just a plain old bug in our jpeg reading module, not accounting for the existence of proxies in this one spot.

In fact, it's not even a problem with being unaware of proxies. It's a problem of forgetting the entire `config` spec that was used to open it the first time. Any other settings communicated by a config spec would be similarly forgotten. It needs to stash the config spec (if one was used) and then use it again if it needs to close and re-open the file.

I should be able to have a patch ready for you today.

**Comment by lgritz** [comment]
Wow, and the same mistake is in other format readers.

**Comment by lgritz** [comment]
Fix is PR #2549

**Comment by etsach** [comment]
> A FILE* is also inherently not thread-safe because it has internal state. We don't open a separate file for each thread, or clone the file handle. The format readers that rely on ordinary file reads also need to be careful with mutexes and whatnot to make thread-safe behavior out of a non-thread-safe primitive underneath. Using IOProxy is no different in this respect.

Do you create a single ImageInput and lock it or does each thread reading tiles opens its own ImageInput? I had (arbitrarily) assumed that you were creating multiple ImageInputs.

**Comment by etsach** [comment]
Great! This fixes the issue in both the test program and the renderer, also with the JpegInput patch which allows generic IOProxy jpeg reading (which I suspected first and made me crazy before figuring out that IOMemBuffer was doing the same...)

**Comment by lgritz** [comment]
In the ImageCache, a single ImageInput for each file is shared among all the threads. The cache is not only trying limit memory for all the pixels (tiles), it's also trying to limit resources like open file handles or memory allocated inside a format-reading library such as libjpeg. Things would get pretty crazy if you had hundreds or thousands of textures (which we do) and each one had a separate open file handle for each of dozens of threads.

OK, if you have tested and this fixes on your end, I will commit the patch and backport it.

Thanks again for your working example. I was super busy this week and this saved me SO MUCH TIME.

**Comment by etsach** [comment]
> In the ImageCache, a single ImageInput for each file is shared among all the threads. The cache is not only trying limit memory for all the pixels (tiles), it's also trying to limit resources like open file handles or memory allocated inside a format-reading library such as libjpeg. Things would get pretty crazy if you had hundreds or thousands of textures (which we do) and each one had a separate open file handle for each of dozens of threads.

Ah OK, so yes my understanding of the causes was totally wrong

> Thanks again for your working example. I was super busy this week and this saved me SO MUCH TIME.

Well, I think this should be the rule when you file a bug in an open source project, provide a minimal, compilable, verifiable example, or don't expect anyone to look at it! This could be worth a coffee or a beer at the next SIGGRAPH but the chances of both having the conference taking place and the plane flying with me inside are getting reduced...

**Comment by lgritz** [comment]
Oh wow, that is an amazing attitude that I wish more people adopted when reporting complex bugs. But I know people are busy and sometimes it is extremely challenging to boil it down to a simple example, especially when you are only encountering the problem from deep within a complex application.

Recently we've been using the memory proxy extensively in our renderer, so I was reasonably sure it was basically sound. But we never use jpeg files, so it was not hard to believe that it was a specific bug in the jpeg reader somehow.

The big clue was that your example (when failing) ended up triggering this error:

> Could not open file "membuffer-grid.jpg"

And I knew from a quick glance at the code that this could only happen when the jpeg reader was trying to first open a file on disk. So that meant that somehow we were getting to a point where the jpeg reader **forgot** about the proxy, and was starting from scratch as if it were a file. 

Definitely a beer at the next SIGGRAPH that we are both at in person!

**Comment by lgritz** [comment]
Addendum: After I fixed the bug where it forgot about the configuration settings when it needed to close and reopen the file (because it needed to read scanlines in reverse order), I got to thinking... **WHY** should it have ever needed to "backtrack" in your example, given that it's an untiled file and so it should have read the whole file at once and made it into a single big tile. 

I instrumented the code a bit better, and indeed, it was reading the whole file multiple times (on some runs). I was able to identify the reason -- if multiple threads need the same tile at the same time, there is a brief moment where they can all see that the tile is not in the cache, and end up EACH reading it. This won't pollute the cache, because eventually they realize it's redundant and throw out their wasteful copy. But it's still doing I/O that it doesn't need to do.

I found a way to rearrange that code that completely eliminates the redundant I/O. I'm doing tests now on production frames to see if that actually makes a noticeable performance improvement in real world cases.
