### ISSUE TITLE
[BUG] Missing channels in multipart EXR

### ISSUE THREAD

**Issue by zavinator** [OpenImageIO/oiio#2608]
**Describe the bug**
Not all channels are loaded from the multipart EXR, see the provided example.

**To Reproduce**
1. Download EXRs: http://leteckaposta.cz/967836314
2. Try to load both files and check the channels:
```
auto in1 = OIIO::ImageInput::open("multi_layer.1001.exr");
auto in2 = OIIO::ImageInput::open("multi-part.1001.exr");
//in1->spec().channelnames.size() == 103
//in2->spec().channelnames.size() == 6
```
3. There should be equal number of channels (check the files for example in Nuke)

**Platform information:**
 - OIIO branch/version: 2.1.15
 - OS: Windows 10 x64
 - C++ compiler: MSVC 2019 x64
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
I believe this is the correct behavior.

A "multi-layer" exr file is just an old style normal exr file containing all the channels. The only thing that is "multi" about it is that a convention for naming the channels ("layername.chanelname") so that it's easy to identify which sets of channel belong together in a logical group.

A "multi-part" exr file truly contains multiple separate subimages, each of which only holds a few channels. ImageInput::open() will only view one of those subimages at a time. You need to call ImageInput::seek_subimage() to move from one "part" to another.

**Comment by zavinator** [comment]
Ok, RTFM problem ;)
