### ISSUE TITLE
Filter attribute for PNG write

### ISSUE THREAD

**Issue by lashgar** [OpenImageIO/oiio#2645]
OpenImageIO does not allow setting filter attributes when writing PNG files. This feature request is to add attribute for PNG on write to support set the filter.

I manually tested that setting the filter to NONE can improve PNG write speed by 10x. Steps:
- Modify oiio/src/png.imageio/pngoutput.cpp
- Somewhere early in PNGOutput::open add following
`png_set_filter(m_png, 0, PNG_FILTER_NONE);`

Note: this is tested on Release- 2.1.17.0.tar.gz release of oiio.
Note: tested image was 512x512 uint8 3-channel PNG with a random noise pattern as content.

**Comment by lgritz** [comment]
Should we be doing that unconditionally? Or should it be an exposed option?

What does this attribute control?

**Comment by lashgar** [comment]
From libpng documentation:
> The selection and configuration of row filters can have a significant impact on the size and encoding speed and a somewhat lesser impact on the decoding speed of an image.

I think the requested featured should be an exposed option to allow flexible size and encoding speed controls. This attribute should be a wrapper for possible row filters in libpng. Here is the libpng doc for possible row filters and how to set them:
http://www.libpng.org/pub/png/libpng-1.2.5-manual.html#section-5.9

**Comment by lgritz** [comment]
OK, I took a look at this, and very straightforwardly added an option to allow this to be set. I assumed that the default should be PNG_FILTER_NONE as you suggested. So, before submitting a PR of the implementation, I ran some tests on performance and compression. Just to arbitrarily pick some images, I used some sample images from the openexr-tests/Scanlines.

For each image, I converted to PNG, using each of several filter choices:

      0    PNG_NO_FILTERS
      8    PNG_FILTER_NONE (your suggestion)
     16    PNG_FILTER_SUB
     23    PNG_FILTER_UP
     56    PNG_FAST_FILTERS = NONE | SUB | UP
     64    PNG_FILTER_AVG
    128    PNG_FILTER_PAETH
    248    PNG_ALL_FILTERS = NONE | SUB | UP | AVG | PAETH

And I got the following results (sorry for the length):

    
    0 Blobbies    real 0.51
    8 Blobbies    real 0.34
    16 Blobbies    real 0.46
    32 Blobbies    real 0.45
    48 Blobbies    real 0.47
    56 Blobbies    real 0.47
    64 Blobbies    real 0.47
    128 Blobbies    real 0.50
    248 Blobbies    real 0.52
      989,482   0/Blobbies.0.png
    1,299,855   8/Blobbies.8.png
    1,020,350   16/Blobbies.16.png
      986,755   32/Blobbies.32.png
      996,871   56/Blobbies.56.png
      982,078   64/Blobbies.64.png
      989,693   128/Blobbies.128.png
      989,494   248/Blobbies.248.png
    
    0 CandleGlass    real 0.21
    8 CandleGlass    real 0.19
    16 CandleGlass    real 0.19
    32 CandleGlass    real 0.20
    48 CandleGlass    real 0.21
    56 CandleGlass    real 0.23
    64 CandleGlass    real 0.20
    128 CandleGlass    real 0.22
    248 CandleGlass    real 0.21
    138,132   0/CandleGlass.0.png
    156,171   8/CandleGlass.8.png
    167,698   16/CandleGlass.16.png
    146,217   32/CandleGlass.32.png
    138,914   56/CandleGlass.56.png
    169,052   64/CandleGlass.64.png
    143,732   128/CandleGlass.128.png
    138,144   248/CandleGlass.248.png
    
    0 Cannon    real 0.21
    8 Cannon    real 0.20
    16 Cannon    real 0.18
    32 Cannon    real 0.18
    48 Cannon    real 0.19
    56 Cannon    real 0.19
    64 Cannon    real 0.20
    128 Cannon    real 0.20
    248 Cannon    real 0.22
      894,183   0/Cannon.0.png
    1,171,302   8/Cannon.8.png
      935,107   16/Cannon.16.png
      943,127   32/Cannon.32.png
      930,151   56/Cannon.56.png
      887,987   64/Cannon.64.png
      902,941   128/Cannon.128.png
      894,195   248/Cannon.248.png
    
    0 Desk    real 0.36
    8 Desk    real 0.27
    16 Desk    real 0.34
    32 Desk    real 0.33
    48 Desk    real 0.37
    56 Desk    real 0.35
    64 Desk    real 0.35
    128 Desk    real 0.35
    248 Desk    real 0.36
    719,453   0/Desk.0.png
    855,423   8/Desk.8.png
    775,791   16/Desk.16.png
    783,870   32/Desk.32.png
    733,535   56/Desk.56.png
    793,830   64/Desk.64.png
    734,029   128/Desk.128.png
    719,465   248/Desk.248.png
    
    0 MtTamWest    real 0.48
    8 MtTamWest    real 0.37
    16 MtTamWest    real 0.42
    32 MtTamWest    real 0.44
    48 MtTamWest    real 0.44
    56 MtTamWest    real 0.44
    64 MtTamWest    real 0.45
    128 MtTamWest    real 0.46
    248 MtTamWest    real 0.47
    1,082,753   0/MtTamWest.0.png
    1,168,251   8/MtTamWest.8.png
    1,094,212   16/MtTamWest.16.png
    1,148,900   32/MtTamWest.32.png
    1,098,299   56/MtTamWest.56.png
    1,081,870   64/MtTamWest.64.png
    1,142,426   128/MtTamWest.128.png
    1,082,765   248/MtTamWest.248.png
    
    0 PrismsLenses    real 0.33
    8 PrismsLenses    real 0.25
    16 PrismsLenses    real 0.29
    32 PrismsLenses    real 0.28
    48 PrismsLenses    real 0.29
    56 PrismsLenses    real 0.30
    64 PrismsLenses    real 0.28
    128 PrismsLenses    real 0.31
    248 PrismsLenses    real 0.31
    568,420   0/PrismsLenses.0.png
    639,136   8/PrismsLenses.8.png
    578,418   16/PrismsLenses.16.png
    583,915   32/PrismsLenses.32.png
    571,011   56/PrismsLenses.56.png
    575,076   64/PrismsLenses.64.png
    575,264   128/PrismsLenses.128.png
    568,432   248/PrismsLenses.248.png
    
    0 StillLife    real 0.40
    8 StillLife    real 0.30
    16 StillLife    real 0.35
    32 StillLife    real 0.34
    48 StillLife    real 0.35
    56 StillLife    real 0.36
    64 StillLife    real 0.35
    128 StillLife    real 0.39
    248 StillLife    real 0.39
    610,590   0/StillLife.0.png
    660,906   8/StillLife.8.png
    613,854   16/StillLife.16.png
    633,675   32/StillLife.32.png
    610,092   56/StillLife.56.png
    601,713   64/StillLife.64.png
    617,208   128/StillLife.128.png
    610,602   248/StillLife.248.png
    
    0 Tree    real 0.50
    8 Tree    real 0.39
    16 Tree    real 0.45
    32 Tree    real 0.46
    48 Tree    real 0.47
    56 Tree    real 0.47
    64 Tree    real 0.45
    128 Tree    real 0.48
    248 Tree    real 0.49
    1,245,346   0/Tree.0.png
    1,282,188   8/Tree.8.png
    1,263,745   16/Tree.16.png
    1,275,242   32/Tree.32.png
    1,253,806   56/Tree.56.png
    1,240,937   64/Tree.64.png
    1,269,813   128/Tree.128.png
    1,245,358   248/Tree.248.png

I hope it's clear what is going on here -- for each image, I use each filter combination and report runtime ("real") and also a list of the resulting file sizes (in bytes).

It's a lot of data to absorb.

For runtime, there is no doubt that filter 8 ("NONE") is usually the fastest option, substantially faster than 0 ("no filters", which is somehow different than NONE) and faster than any of the other filter choices. (Except for the "Cannon" image, for some reason.)

However, when we look at file sizes, filter 8 ("NONE") is almost always the worst compression ratio, and choice 0 ("no filters") is almost always the best, or nearly tied with the best. 

This all really confused me, because if I understand the docs properly, the whole point of this filtering is supposed to be to condition the image data to have a better compression ratio. So I would expect the original default (0, "no filters") to be the fastest, and have the largest file size. 

None of these choices were very substantial improvements in either time or space, in contrast to your original report of 10x. The biggest high-to-low swing I saw was no more than 25%.

I wonder if maybe this only has a significant advantage for random images, as you used? But is that really a case we should be optimizing for? Is it possible that for more photographic or rendered images, there is no large advantage, and indeed no clear winning choice for both space and time?

I don't mind adding this, but it's still not clear to me what the default value should be.

**Comment by lgritz** [comment]
I would love to know what the difference between "no filters" and "filter none" is. They sound like they are the same thing, but have the widest difference in both speed and compression of any of the choices.

Can I confide that it does not surprise me one bit about PNG or its docs that it's 100% opaque what these options do, that the performance results are counterintuitive (to say the least), and that there is no clear best choice and little guidance given?

**Comment by lashgar** [comment]
Thanks @lgritz for evaluations. That's fair enough, the image I've been evaluating has no real pattern and libpng likely tests various compression schemes with no luck. Attached the photo for the record: ![sample-phase](https://user-images.githubusercontent.com/3949295/88971232-7fc0e080-d268-11ea-9664-1ea6ac92bdfb.png)

The default value of the attribute is hard to decide, I agree. Currently, it is set to libpng default. If attribute is not set by the user, oiio wrappers can leave it unset so picks up libpng default. It's not great way to handle this, but one option.

**Comment by lgritz** [comment]
I would consider that fairly unusual.

I think what I will do is leave the ability to set the option, for those who want to explore it, but keep the default value at 0, meaning the libpng default (no filter) and matching the old performance.

**Comment by lgritz** [comment]
I would assume that if there was a consistently best choice (or even any consistently better choice than 0), that would have been the libpng default.

I speculate that maybe the history here is that early in the life of libpng, it was thought that the filtering would be important, but later was discovered not to be very helpful in any consistent way so the default remains to use no filters, but the option is nonetheless still there for the sake of compatibility.
