### ISSUE TITLE
ParamValue.type returns string, not TypeDesc

### ISSUE THREAD

**Issue by filmkorn** [OpenImageIO/oiio#2672]
**Describe the bug**
In the Python bindings, `ImageSpec.extra_attrs[i].type` used return a `TypeDesc` object, now returns a `string` ie `'float'`. The [docs](https://openimageio.readthedocs.io/en/release-2.2.4.0-beta1/pythonbindings.html#ImageSpec.extra_attribs) may need to be updated or the returned type is incorrect.

**To Reproduce**
```python
>>> spec = oiio.ImageSpec()
>>> spec.attribute("test", 42)
>>> spec.extra_attribs[0].type
'float'
```

**Expected behaviour**
Return a `TypeDesc`.
```
>>> spec.extra_attribs[0].type
<OpenImageIO.TypeDesc object at 0x...>
```

**Evidence**
See above.

**Platform information:**
 - OIIO branch/version: 2.2 beta1
 - OS: cent7
 - C++ compiler: gcc 6.4.0
 - Any non-default build flags when you build OIIO:

We have some code that copies attributes from one spec to another. `ImageSpec.attribute` expects a TypeDesc when setting the type explicitly so it would be convenient if we directly get the TypeDesc instead of a string from the ParamValue object when iterating over the `extra_attrs`.

**Comment by filmkorn** [comment]
Found I can just create a `TypeDesc` from the string like this:

```python
TypeDesc("float")
```

Please disregard if this isn't a bug.

**Comment by lgritz** [comment]
Oh, interesting!

You're right, for some reason the ParamValue.type returns a string (since 2.0 -- that's late 2018) whereas before that it was a TypeDesc.

I... think that's a bug? But since it's been like that for 3 major releases now (2.2 is in beta, this was a change between 1.8 and 2.0), I'm afraid to change it.

You are right, it is also set up to convert strings transparently into TypeDesc. So I hope this is harmless.

This really bugs me. I think the change was unintentional. But I'm worried that changing it back to a TypeDesc could break people's python scripts.

**Comment by lgritz** [comment]
I'm really sorry about this.
Since the C++ 'type' field of ParamValue is TypeDesc, I would expect the Python binding to be the same way. 
I can't think of any reason for it to be this way. To be honest, I suspect it was basically a cut and paste error.

But this is the kind of change that can't happen until we're at a 2.x -> 3.0 boundary.

**Comment by filmkorn** [comment]
No worries. As a non-breaking change, `ParamValue` could have another attr `ParamValue.type_desc` that returns the `TypeDesc` - but creating the `TypeDesc` from the string as in my workaround above works for me.  From how I understand the `ImageSpec.attribute()` interface I should only pass the `TypeDesc` when passing a tuple (?) anyways.

**Comment by lgritz** [comment]
I'm adding a big fat TODO comment, but not changing anything for now for fear of breaking people or digging the hole deeper. Apologies again.
