### ISSUE TITLE
[HELP] How to manually specify reader for an ImageInput

### ISSUE THREAD

**Issue by gregcotten** [OpenImageIO/oiio#2680]
Is it possible to manually specify the reader used for ImageInput? 

I have some files I don't want to modify the extension of but want to efficiently open them. I take it there is **some** overhead by iterating through each reader to see if can open the image?

Another solution would be to somehow associate these non-standard file extensions with a reader?

**Comment by lgritz** [comment]
Absolutely!

There are two ways to create and open an ImageInput. (1) The easy way is to call the static `ImageInput::open(filename)`, which both creates and opens the ImageInput. (2) You could also call `ImageInput::create(filename)` to create the ImageInput, then the non-static `open(filename)` method to open it.

So it's the second technique that I'm referring to below.

The ImageInput::create() takes a "filename", but it's not really a filename. At least, it doesn't have to be. It's customary to pass a filename, from which but it will try to infer the file type from the extension, but if that doesn't work, it will try all of them, as you note. But the name you pass to create() can also be just a file extension (from which it makes its best guess about which file format would be associated with it), or even an explicit format name.

Now, if you use technique (2), then once you've created an ImageInput that reads a certain file type, the `open()` method just tries to open, it can't change the kind of ImageInput it is, since you already created it. 

So, for example, suppose you have a TIFF file which you have for some reason called "myfile.xyz". It will never know xyz is a TIFF file, so it would ordinarily try every file type. This is what you are trying to avoid! So do this:

    std::unique_ptr<ImageInput> in = ImageInput::create("tiff");  // create by file format name: TIFF
    in->open("myfile.xyz");   // Open with the TIFF reader, even though the filename is weird

**Comment by gregcotten** [comment]
Awesome! I knew there'd be an incantation to make this happen.
