### ISSUE TITLE
oiiotool multiple bit depths channel syntax [HELP]

### ISSUE THREAD

**Issue by mlavoy** [OpenImageIO/oiio#2710]
Im trying to convert proxy exrs that contain cryptomatte channels; i need to maintain some channels as full float.

Im attempting with:
oiiotool.exe -a multipart.exr --resample 50% -d cryptomatte_ASSET=float -o proxy.exr

this isnt working, its making everything half float because of the first rgba channel.

am I missing something for the correct channel name? cryptomatte_ASSET.R didnt work either.

documentation only shows channel names like R,G,B,A,Z, any ideas? Thank you!!!

**Comment by lgritz** [comment]
Can you email me a (small) example file so I can see exactly the configuration you're starting with?

**Comment by mlavoy** [comment]
Here you go, thanks for checking it out.

[exrExample.zip](https://github.com/OpenImageIO/oiio/files/5235323/exrExample.zip)

**Comment by lgritz** [comment]
Yeah, definitely something weird going on here. Investigating...

**Comment by lgritz** [comment]
OK, I got distracted by the fact that this example was crashing for me (an unrelated bug fixed by #2712).

But I now understand what's going on here. In *all* of your parts, the channels are named R,G,B,A (or R,G,B, or in a few subimages X,Y,Z). In other words, although each part has a different name, the channel names are not unique, and so that is totally confusing the way it tries to remember the original set of channels and what formats they should be.

I will need to change this to incorporate the subimage name into how it keeps track of this. A real fix is coming shortly.

**Comment by lgritz** [comment]
Comprehensive fix in #2717
