### ISSUE TITLE
[BUG] Color conversion crash with certain images

### ISSUE THREAD

**Issue by andrewkaufman** [OpenImageIO/oiio#2713]
**Describe the bug**
A particular png file is crashing during a color conversion that uses `ImageBufAlgo::colorconvert`. My original repro was in a unittest for [Cortex](https://github.com/ImageEngine/cortex), but I've stripped it down to a minimal test case using OIIO only.

**To Reproduce**
1. Download [this png](https://github.com/ImageEngine/cortex/blob/10.0.0-a83/test/IECoreNuke/data/png/kodak_dx7590_test.png)
2. Compile [this program](https://gist.github.com/andrewkaufman/3c1194c4d5356e46f27e859ea4dcd390)
    - My command was `g++ -o ./colorConvert ./colorConvert.cpp -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 -Werror -O3 -fPIC -lOpenImageIO;`
3. Run it on the image (eg `./colorConvert /path/to/kodak_dx7590_test.png`)

**Expected behavior**
I'd expect the script to return 0 with a "success!" print to stdout.

**Evidence**

Step 3 crashes with the following output:
```
$ ./colorConvert kodak_dx7590_test.png 
    reading kodak_dx7590_test.png
    convert to sRGB
Segmentation fault (core dumped)
```

I tested on many other png files without any trouble (ie. the other images convert correctly). When creating this Issue I came across https://github.com/OpenImageIO/oiio/issues/2191. I downloaded the image attached and confirmed that:
- running `./colorConvert that.jpeg` also crashes
- running `oiiotool -i that.jpeg -o that.png` succeeds in OIIO 2.0.8 (as such #2191 can probably be closed?)
- running `./colorConvert that.png` also crashes

**Platform information:**
- I originally saw the crash using a custom build of OIIO 2.2.6.1 on CentOS 7 with gcc 6.3.1
- I verified the crash using OIIO inside ASWF docker [ci-vfxall/2019.9](https://github.com/AcademySoftwareFoundation/aswf-docker/releases/tag/aswf%2Fci-vfxall%2F2019.9), which I believe is OIIO 2.0.8
- I verified the conversion succeeds in OIIO 1.8.10 and 1.8.12 (both custom builds), but have not tried other versions between 1.8 and 2.0.

**Comment by lgritz** [comment]
I'll check it out right away. Thanks for the repro case.

**Comment by lgritz** [comment]
I can reproduce the segfault. Investigating...

**Comment by lgritz** [comment]
Well, there are a number of very strange things going on here. I'm not sure which are intentional, or which are just looking strange because this is a greatly stripped down version of something in a big app where it made more sense (or got garbled in the translation). I'll just list them all and you can make of them what you will:

* Is there a reason why you're using the ImageCache to get_pixels into a raw buffer, then set up an ImageBuf that "wraps" the buffer? I mean, if you just make the ImageBuf with the filename itself, it will all work and will even still use the ImageCache underneath if the file is large, and will avoid a needless copy from the imagecache to your raw buffer.

* That cache->get_pixels call is only reading part of the file -- it's 2576 x 1932, 3 channels, but you are reading just the first channel into a 2576 x 1932 x 1 buffer (because your get_pixels is getting passed chbegin=0, chend=1).

* This isn't your crash, but I bet that you will run into problems eventually calling colorconvert on a 1-channel image. Single channel images don't really have color spaces, and OCIO will not be happy with that. The thing that might save you here is if you have OCIO disabled, or don't have an OCIO config, or your OCIO config doesn't know about "srgb" color space, if that is true then it might fall back to the internal (non-OCIO) linear<->sRGB conversions, which *maybe* will just silently apply the transform to whatever number of channels you have? That sounds iffy and at the very least untested. In general, colorconvert is meant for images with (at least) R, G, and B channels.

* OK, but not only are you reading one channel, but when you "wrap" your buffer into an ImageBuf, instead of telling it that it is wrapping a 2576 x 1932 image, you are for some reason intentionally making it a 1D, 4976832 x 1 image? At the very least, this will mess up the internally threaded implementation of colorconvert (which I bet is processing blocks of scanlines in parallel) so that probably will be less efficient than a regular image. (I think? maybe it's smart enough to notice and split in X? I would need spelunk through the code in detail.)

* But anyway, the real problem is that internal to colorconvert, it's doing an alloca of one scanline of data, and since your scanline is not 2576, but rather 4976832 floats wide, I think you are just hitting a stack overflow. To be fair, this is sloppiness on my part, it should be a real allocation, but I didn't think we would be dealing with any 20MB single scanlines. The workaround here, too, is also to make it think it's the 2576 x 1932 image that it really is.

You should probably scold me about how I should never use alloca, at least not for big things, and also that I should not make any assumptions about how big a scanline might get. But the fact of the matter is that while we are very careful to use a real malloc for whole images, there are probably a variety of places where we assume that an alloca of a small number of bytes per scanline or per column is safe. It's one thing if you really have millions-wide or millions-high images, we'll root out those bugs when people have images that big. But I wouldn't advise making "ordinary" size images artificially look like they are 1D, this is probably not the last such bug we will stumble across.

**Comment by andrewkaufman** [comment]
Thanks for your insights. I confirmed that if I use the real `ImageSpec` rather than the bizarre flatSpec then I do not get the crash. I guess the only reason our other test images didn't catch this is they just weren't quite large enough...

We'll have to figure out some workaround in Cortex, since the real code path is a bit more complex... We don't have the spec available when the color conversion is performed, we just have the raw buffer of a single channel.

On the off chance you're interested in the details, I'll respond to your individual comments as well:

> I'm not sure which are intentional, or which are just looking strange because this is a greatly stripped down version of something in a big app where it made more sense.

Its a bit of both... when we adopted OIIO (and OCIO) in Cortex to replace our own image/color processing (~3 years ago), we chose to keep the client facing interface of our `ImageReader` class. That gives user control over the ROI, which channels to read, miplevel, whether to return raw data, cast to a different data type, perform a color conversion, etc. It also enforces the idea that channels are separate flat vectors (akin to primitive variables of geometry). At the same time, our `ImageReader` became a somewhat deprecated-but-not-deprecated part of Cortex... anything performance-focused isn't using it (ie. Gaffer's image processing uses a different approach). That was all done very quickly in a PR that touched ~900 files, so some implementation details surely slipped through the cracks.

> Is there a reason why you're using the `ImageCache` to `get_pixels` into a raw buffer, then set up an `ImageBuf` that "wraps" the buffer? ... just make the `ImageBuf` with the filename itself...

In the real code, the `get_pixels` call lives within our `ImageReader` and may return the raw buffer back to the user without ever going through an `ImageBuf`. Similarly, the `ImageBuf` might get constructed from a raw buffer that never came from an image on disk.

> That `cache->get_pixels` call is only reading part of the file -- it's 2576 x 1932, 3 channels, but you are reading just the first channel into a 2576 x 1932 x 1 buffer (because your get_pixels is getting passed chbegin=0, chend=1).

In the real code the user can request a single channel, or non-sequential channels (eg `[ "R", "B" ]` ). For simplicity of implementation, and since its not used in performance critical situations, we only fetch them one at a time (the `get_pixels` call is given an `[ i, i+1 ]` range).

> I bet that you will run into problems eventually calling colorconvert on a 1-channel image. In general, colorconvert is meant for images with (at least) R, G, and B channels.

This seems to be the crux of the issue. I know very little about color personally, and 100% defer to your expertise. From what you are saying, [`IECoreImage::ColorAlgo::transformChannel`](https://github.com/ImageEngine/cortex/blob/master/include/IECoreImage/ColorAlgo.h#L50-L52)is a bad interface and we should not be using it.

> when you "wrap" your buffer into an ImageBuf, instead of telling it that it is wrapping a 2576 x 1932 image, you are for some reason intentionally making it a 1D, 4976832 x 1 image? ... I think you are just hitting a stack overflow. The workaround is also to make it think it's the 2576 x 1932 image that it really is.

I kept that in the repro program because it looked odd and I suspected it might be part of the problem. I suppose the trouble here is our interface doesn't retain the ROI when we perform the color conversion. The data may never have come from an image at all, it could be authored in-memory in python (eg `r = IECore.FloatVectorData( [ 0.01*x for x in range( 0, 100 ) ] ); IECoreImage.ColorAlgo.transformChannel( r, "linear", "sRGB" )`.

> You should probably scold me about how I should never use alloca, at least not for big things, and also that I should not make any assumptions about how big a scanline might get.

Not at all. I think its totally reasonable to optimize for real world production uses rather than theoretical infinitely wide/skinny images.

**Comment by andrewkaufman** [comment]
I've opened a Cortex issue to address it on our side, so we can close this one.

**Comment by lgritz** [comment]
Reopening because I do think this revealed a problem on the OIIO side (crashes are bad) and I will have a PR to help make smarter decisions about memory allocation.

I don't have a good solution for the single-channel issue. In OCIO's conception of a color space, there are no color color spaces that are 1D, and thus no way to do a color space transformation on a 1-channel image. The "sRGB" specification is a combination of particular color primaries and whitespace (same as Rec709) and also a particular encoding of values (the nonlinear sRGB transfer function). While it makes sense to do the transfer function to just one channel, it's only correct if your "linear" default color space also uses the same color primaries. So this would work for a linear Rec709 <-> sRGB, but would be way wrong if your working color space was ACEScg, for example.
