### ISSUE TITLE
[BUG] RAW plugin does not compile with recent libraw versions

### ISSUE THREAD

**Issue by ebatsin** [OpenImageIO/oiio#2718]
**Describe the bug**

In `src/raw.imageio/rawinput.cpp`, there is a typo around line 667, `longtitude` instead of `longitude`.

```
        add("GPS", "Longitude", other.parsed_gps.longtitude, false,
            0.0f);  // N.B. wrong spelling!
```
This typo has been fixed 3 month ago in libraw: https://github.com/LibRaw/LibRaw/commit/ac5367b352fff4d5b854d44c979636d21951588b

**Platform information:**
 - OIIO branch/version: HEAD
 - OS: linux
 - C++ compiler: clang++-10
 - Any non-default build flags when you build OIIO: none

**IF YOU ALREADY HAVE A CODE FIX:** There is no need to file a separate issue,
please just go straight to making a [pull request](https://github.com/OpenImageIO/oiio/pulls).

I can do a PR but I'd like to know why is there a comment next to a typo saying there's a typo instead of fixing said typo.

Edit: Just understood that this was a typo in libraw that was fixed recently. I'll do a MR for this.

**Comment by lgritz** [comment]
Just to explain a little for anybody else who stumbles across this issue in the future:

The misspelling was intentional and un-fixable because the field in the LibRaw API struct was itself misspelled and had been for many years.

At some point in the development of LibRaw 0.20, the field was renamed to fix the spelling, breaking compatibility permanently -- the field is named one thing in earlier versions, and named differently in later versions.

We did modify OIIO at some point to notice the LibRaw version and conditionally switch names (#2613). So OIIO 2.2 and later (and also backported to 2.1.17) handle versions of LibRaw on both sides of the transition. But prior released versions of OIIO will only work with LibRaw <= 0.19 and will have a build error if they encounter LibRaw >= 0.20.
