### ISSUE TITLE
[BUG] ImageBufAlgo::channels sets ImageBuf::nsubimages to 0

### ISSUE THREAD

**Issue by MickeyKnox** [OpenImageIO/oiio#2755]
Consider this snippet:

```c++
buffer.nsubimages() --> 1

if (buffer.nchannels() == 3)
    buffer = OIIO::ImageBufAlgo::channels(buffer, 4,
                /* channelorder */ { 0, 1, 2, -1 /*use a float value*/ },
                /* channelvalues */ { 0 /*ignore*/, 0 /*ignore*/, 0 /*ignore*/, 1.0 },
                /* channelnames */ { "", "", "", "A" });

buffer.nsubimages() --> 0
```

The pixels can still be read from the new buffer, but `nsubimages()` reports 0. This only happens for single frame images; for multiframe images (animated GIFs) the number reported by  `nsubimages()` does not change after the `ImageBufAlgo::channels` call.

**Comment by lgritz** [comment]
Ah, this is conceptually subtle.

You have to remember that an ImageBuf is a single image. It should not be confused for an image file, which might hold more than one image.

When you have `ImageBuf buf("myfile")`, that directly represents an image in a file, the nsubimages() will return the number of subimages in the file. Though it's worth remembering that at this point, the `buf` itself will hold only one image from that file (by default, the first one).

When you do `buf = ImageBufAlgo::channels(...)`, now the buf does not correspond to a file at all. It's a new ImageBuf that is the result of a computation. So subsequently to the channels call, nsubimages() should return 1 always.

I think it's a bug that it returns 0. It's probably also a mistake to make it carry its original value from the input file, since that buffer no longer represents the file. Probably 1 is a better value for nsubimages() at that point? In fact, looking at some related methods (subimage(), nmiplevels(), file_format_name(), etc.), those should all a little dubious and be audited to make sure they do something sensible for images that don't come directly from file reads.

**Comment by MickeyKnox** [comment]
Hm.. I'm using the ImageBuf from the `channels` call to loop through all the images in the image file:

```C++
        int index = buffer.subimage() + 1;
        if (index == buffer.nsubimages())
            index = 0;

        buffer.read(index);
```

That works. From what your saying I take that this shouldn't be done this way. How am I supposed to loop through all the images in a file? I suppose I could store the original buffer and do the loop with it, but what if I have fix the channels? If I'd do that on every iteration, wouldn't that be less efficient?

**Comment by lgritz** [comment]
That works just fine as long as the buffer actually refers directly to a file on disk. Like if you did this:

    ImageBuf buffer ("filename.ext");
    // or:
    ImageBuf buffer (filename, subimage, miplevel);

also, keeping the image referring to that file but changing which subimage it's referring to also should work:

    ImageBuf buffer ("filename.ext");
    buffer.read(subimage);
    // still refers to an image on disk

But once you *assign* buffer something that is the result of a computation, rather than something directly referring to a disk file, like

    buffer = ImageBufAlgorithm::something();

Now that buffer is no longer corresponding directly to a disk file, it makes no sense to ask how many subimages it has, because at this point it's just a single image buffer in memory.

So what you should do is ask how many subimages there on while the buffer still refers to the file. Don't ask after you've reassigned a completely new ImageBuf that is returned from ImageBufAlgo::channels.

**Comment by MickeyKnox** [comment]
Ok thanks, I get the difference between ImageBuf that represents a file and an ImageBuf that is the result of a computation.
