### ISSUE TITLE
Invalid TIF file

### ISSUE THREAD

**Issue by kiliandys** [OpenImageIO/oiio#2774]
Hi everyone 😄 

I try to update only "tiles" of a file - and I want it to be of type TIF.

I want to store a z-buffer, so I need to either put a NaN of a float in a pixel.

I tried to create a TIF with the following code, but when I use it using ImageJ, I get an invalid tiff (see below).

Here is the code:
1. Creates a tiff. Give even pixel a value of 0.0f and odd ones a value of NaN
2. Update the first tile of the file with only 0.0f

```cpp
// Create a "NAN" image
std::string path{ "fake.tif" };

const uint64_t xres = 200, yres = 200;
uint64_t tileSize = 64;

OIIO::ImageSpec spec(xres, yres, 1, OIIO::TypeFloat);
spec.tile_width = tileSize;
spec.tile_height = tileSize;

{
    std::unique_ptr<OIIO::ImageOutput> imageOutput = OIIO::ImageOutput::create(path);
    if(!imageOutput) {
        std::cerr << "Failed creationg of imageOutput" << std::endl;
        return -1;
    }
    if(!imageOutput->supports("tiles")) {
        std::cerr << "Tiles are not supported" << std::endl;
        return -1;
    }


    // Forge data
    std::unique_ptr<float[]> data;
    data.reset(new float[xres * yres]);
    for(uint64_t idx = 0; idx < (xres * yres); idx++) {
        data.get()[idx] = (idx % 2 == 0) ? 0.0f : std::numeric_limits<float>::quiet_NaN();
    };

    // Write data
    imageOutput->open(path, spec);
    bool ok = imageOutput->write_image(OIIO::TypeFloat, data.get());
    if(!ok) {
        std::cerr << "Failed write_image, error=" << imageOutput->geterror() << std::endl;
    }
    imageOutput->close();
}

{
    std::unique_ptr<OIIO::ImageOutput> imageOutput = OIIO::ImageOutput::create(path);
    if(!imageOutput) {
        std::cerr << "Failed creationg of imageOutput";
        return -1;
    }

    // Update a tile
    std::unique_ptr<float[]> tileData;
    tileData.reset(new float[tileSize * tileSize]);
    for(uint64_t idx = 0; idx < tileSize * tileSize; idx++) {
        tileData.get()[idx] = 0.0f;
    }

    OIIO::stride_t xstride = spec.nchannels * sizeof(float); // because your buffer is UINT8
    OIIO::stride_t ystride = xstride * std::min(spec.width + spec.x, spec.tile_width);

    bool ok = imageOutput->write_tile(0, 0, 0, OIIO::TypeFloat, tileData.get(), xstride, ystride);
    if(!ok) {
        std::cerr << "Failed write_tile, error=" << imageOutput->geterror() << std::endl;
    }
    imageOutput->close();
}
```

I get the following output
```
Failed write_tile, error=
```

If I use only the first part of the code (generating the tiff), I get the following tiff:

![image](https://user-images.githubusercontent.com/49058099/100124782-61689b80-2e7c-11eb-87a1-7317260630d9.png)

- Black = NaN
- Red = -3.0117
- Yellow = 0

I used ImageJ to open the tiff.

Here is the raw tiff:

[fake.zip](https://github.com/OpenImageIO/oiio/files/5591378/fake.zip)

**Comment by lgritz** [comment]
If I understand your code, you are doing the following:

1. Create an output (at this point, it's not yet open), open it, write a full image, close it.
2. Create another output using the same filename (at this point, it's not yet open),  call write_tile().

So the most immediate problem is that the second write_tile is not happening to an open file at all. 

But also, even if you did open the file, you would notice that the OIIO interface will erase/truncate a file when you do open it for output. There isn't a way within the OIIO API to have a read/write file where you replace just a subset of scanlines or tiles.

This is not merely a limitation of OIIO -- the reason the API doesn't support it is that none of the major image libraries (including libtiff, which we use for the lower level read/write of TIFF files) support amending a file in place. The TIFF format isn't especially amenable to this, because the file is riddled with offsets to different locations within itself. Any operation that might change the relative size of things (like a tile, which having different contents would be a different compressed size on disk) would really need the whole file to be rewritten so that all the offsets elsewhere in the file were fixed.

The only way to edit the pixel values in a file is to read the whole thing, change the values in memory, and then write out a new file. You can't write just one tile.

**Comment by lgritz** [comment]
As an aside, NaN is a poor choice for an empty zbuffer pixel. The way NaN values work is that ALL ordering comparisons involving them are false. So imagine that you have a zbuffer, and the fundamental operation is to overwrite the value if the new object is closer than the object in the file. For example,

    if my_z < zbuffer[pixel] 
        color_buffer[pixel] = my_color
        z_buffer[pixel] = my_z

But if z_buffer[pixel] is NaN, then `my_z < z_buffer[pixel]` will be false. So will `my_z < z_buffer[pixel]`. 

A value of `inf` (or some other finite but very large value, like `numeric_limits<float>::max()`) will be much better because the comparison will work properly.
