### ISSUE TITLE
[BUG] oiiotool Silently fails to resize 16k EXR images

### ISSUE THREAD

**Issue by gregzaal** [OpenImageIO/oiio#2813]
**Describe the bug**
Running `oiiotool input.exr -resize 1024x512 -o output.exr` on a 16k pixel wide input fails without producing any error message. No output file gets created.

Adding `-v --debug` shows this output:
```
>oiiotool -v --debug stone_alley_03_16k.exr -resize:filter=box 1024x512 -o test_t.exr
Reading stone_alley_03_16k.exr
Performing 'resize' with args:  "-resize:filter=box", "1024x512"
  Resizing 16384x8192 to 1024x512 using box filter

>
```

While running on an 8k (or smaller) version of the same image succeeds and shows this output:

```
>oiiotool -v --debug stone_alley_03_8k.exr -resize:filter=box 1024x512 -o test_t.exr
Reading stone_alley_03_8k.exr
Performing 'resize' with args:  "-resize:filter=box", "1024x512"
  Resizing 8192x4096 to 1024x512 using box filter
    resize took 0.64s  (total time 0.65s, mem 418.5 MB)
Output: test_t.exr
Writing test_t.exr
    output took 0.04s  (total time 0.69s, mem 418.2 MB)

>
```

**To Reproduce**
1. Download this 16k EXR file (cc0 license): https://hdrihaven.com/files/hdris/stone_alley_03_16k.exr ([acquired from here](https://hdrihaven.com/hdri/?h=stone_alley_03))
2. Run `oiiotool -v --debug stone_alley_03_16k.exr -resize:filter=box 1024x512 -o test_t.exr`

**Expected behavior**
A new smaller image file should be created.

**Evidence**
Do you have error messages? (please quote exactly) Screenshots? Example
command lines or scripts that reliably reproduce the error? If it only
happens with certain image files, can you attach the smallest image you
can make that reproduces the problem?

**Platform information:**
 - OIIO branch/version: Installed yesterday using vcpkg, not sure what version this is.
 - OS: Windows 10 64 bit.
 - C++ compiler: Whatever gets used with vcpkg and VS 2019 community.
 - Any non-default build flags when you build OIIO: Ran `.\vcpkg install openimageio[tools]:x86-windows-static`

**Comment by gregzaal** [comment]
Confirmed this is also broken with the `.hdr` format as well, so not exclusive to `.exr` files. 16k is broken but 8k works fine.

**Comment by dmitryshurov** [comment]
I've stumbled upon the same issue and I figured out that the culprit here is the x86 platform package. 

The reason for that is memory allocation - `ImageCacheTile::read` function [here](https://github.com/OpenImageIO/oiio/blob/91e9852ac2c8422faebc3018c0665c195e368dae/src/libtexture/imagecache.cpp#L1500) tries to allocate more memory than x86 platform supports (a block of ~1.5 GB, which, in addition to other memory allocated by the `oiiotool`, seems to exceed the x86 platform memory limit). 

So the solution here is to install the 64-bit version of the package: `.\vcpkg install openimageio[tools]:x64-windows-static`

I could possibly make a merge request that would handle the issue in a more verbose way since there's a chance of facing memory allocation issues even in x64 systems with an insufficient amount of free memory (which is obviously a rare corner case, but it would be nice to handle that any way to avoid confusion in the future).

**Comment by lgritz** [comment]
Very interesting! That certainly explains why I was unable to reproduce, and I failed to notice that the OP's vcpkg install was specifying 32 bit.

There are ways I can mitigate this if I know memory is limited, it doesn't have to try to swallow the whole image into one tile all at once.

Sorry, I am not a Windows programmer at all, literally have not used Windows since the '90s. Is there a reliable way from C++ to detect if it's the 64 bit vs 32 bit build, and/or what the process memory limit is?

**Comment by gregzaal** [comment]
Ah of course! That makes sense. I recompiled and can confirm it works as expected :)

Some more informative error handling would certainly be appreciated, but I imagine anyone intentionally compiling for x86 (not just by mistake) probably knows their limitations already.
