### ISSUE TITLE
[FEATURE REQUEST] Add jp2 to supported file format

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2908]
Jpeg2000 appears to be supported, but jp2 is not in the extension list.

**Comment by lgritz** [comment]
https://github.com/OpenImageIO/oiio/blob/master/src/jpeg2000.imageio/jpeg2000input.cpp#L166

How did you determine this? Did something not work?

Also, the extension list is only used as the first guess. If no matching extension is found from any reader, OIIO will try to open() with *every* reader in turn until it finds one that can open the file, only completely failing if none will open the file. Makes me wonder if the real problem is that you have a jp2 file that either is corrupted, or else for some reason the jpeg2000 reader is having trouble with it.

**Comment by DougRogers** [comment]
The extension list is used to determine if OIIO supports a file type.  If the format is not in that list, it is rejected and open() is not attempted.

I did not realize that OpenJPEG is also optional, so I had not installed it, hence no jp2 in the list.

**Comment by lgritz** [comment]
Yeah, because there are so many potential dependencies for the different file formats, and everybody seems to care about a different subset of them and will complain bitterly if a format they don't need is breaking their build, almost all are "optional" dependencies where the support is enabled only if the right dependent library is found at build time.

Incidentally, "oiiotool --help" prints a ton of stuff, including all the formats that were enabled in that build.

**Comment by lgritz** [comment]
Some of the dependencies are very common -- at least on Linux, you expect every core system install to have libtiff, jpeg, png, openexr, so these are hard requirements. But many of the others dependencies are not commonly pre-installed on any major distros, so it's a very high bar for many users (especially on Windows) to expect them to separately build from source another dozen dependencies as a prerequisite to even starting an OIIO build. (And guess who they complain to if they have trouble building OpenJpeg, when they only need it for OIIO?)

None of it is a big deal for Linux, it's almost completely about Windows. What I think would be better is if our CI system (or some kind Windows-knowledgeable user) built the full suite of dependencies and OIIO and we could host the pre-built Windows binaries somewhere, keeping up with every release. If we did the work and most users who weren't trying to develop OIIO didn't need to build anything from source, it would be more practical to make almost all of the formats non-optional.

**Comment by DougRogers** [comment]
This is no longer the case for Windows.   You can direct them to use vcpkg and with one line it will install OIIO and all the dependencies.  

All I have to do is type:  

`vcpkg install openimageio[libraw,OpenJpeg]  --triplet x64-windows`
and it downloads the latest released version and creates a release and debug build.

**Comment by lgritz** [comment]
Yes, vcpkg is great.

I guess, then, the trick is that it would be nice for the default vcpkg openimageio build to have all the options turned on.

But in either case, I'm definitely open to feedback about which dependencies should be made required with an opt-out rather than including opportunistically if it happens to be detected.

**Comment by DougRogers** [comment]
The downside to vcpkg is that I can only pull from a release branch.  I am waiting for your changes to get into a release so I can continue testing.

**Comment by lgritz** [comment]
I do releases on the first of every month. Not sure how closely vcpkg follows us, but 2.2.13.0 should contain all the fixes related to your issues so far.
