### ISSUE TITLE
[BUG] Grey scale png is incorrect.

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2915]
This image display incorrectly for me:
![gray](https://user-images.githubusercontent.com/7563851/112571328-1072a080-8da5-11eb-9ff8-74ac922cfffa.png)

Looks like this:
![image](https://user-images.githubusercontent.com/7563851/112571440-431c9900-8da5-11eb-932c-6b419352eb07.png)

This is a test case, so it may be altered manually.

**Comment by lgritz** [comment]
Looks right to me. What program are you using to display it, that shows with the incorrect false color?

I also can't quite tell if my downloading the embedded PNG here will give me what you started with, or if GitHub does anything to alter it. If you right click on the greyscale image above and "save as", then is that saved image displayed incorrectly?

What happens if you say `oiiotool -info -v bad.png` ?

**Comment by DougRogers** [comment]
I am using QtOIIO to import the images into my Qt program.  The issues seems to be in its grey to RGB conversion.

**Comment by lgritz** [comment]
Ooh, I don't think I knew about QtOIIO

**Comment by DougRogers** [comment]
It is indeed a QtOIIO bug.  

https://github.com/alicevision/QtOIIO/issues/19
