### ISSUE TITLE
[BUILD]Failed to build on Linux (Flatpak)

### ISSUE THREAD

**Issue by Sunderland93** [OpenImageIO/oiio#2986]
Hello, I am maintainer of Natron's Flatpak package. Building of latest stable release of OpenImageIO is fails:

https://pastebin.com/R1fdjruP

Configuration options:

```
"-DCMAKE_BUILD_TYPE=Release",
"-DUSE_OPENCV:BOOL=FALSE",
"-DUSE_OPENSSL:BOOL=FALSE",
"-DUSE_QT5:BOOL=FALSE",
"-DUSE_OPENGL:BOOL=FALSE",
"-DUSE_HEIF:BOOL=TRUE",
"-DUSE_OPENJPEG:BOOL=TRUE",
"-DUSE_PYTHON:BOOL=FALSE",
"-DUSE_FIELD3D:BOOL=FALSE",
"-DOIIO_BUILD_TESTS=0",
"-DOIIO_BUILD_TOOLS=1",
"-DSTOP_ON_WARNING:BOOL=FALSE",
"-DUSE_GIF:BOOL=TRUE",
 "-DUSE_FREETYPE:BOOL=TRUE",
 "-DUSE_FFMPEG:BOOL=FALSE",
 "-DLINKSTATIC=0",
 "-DOpenJpeg_ROOT=/app/",
 "-DIlmbase_ROOT=/app/",
 "-DUSE_LIBRAW:BOOL=TRUE",
 "-DCMAKE_LIBRARY_PATH=/app/lib",
 "-DVERBOSE=ON"
```

**Comment by lgritz** [comment]
I believe that these lines in your log reveal the problem:

    -- Found fmt: /app/include (found version "50201") 
    -- Found fmt 50201 

The current version of fmtlib is 7.1.3. OIIO's build system doesn't check for a minimum, but apparently, this one is just too old, something must have changed in their internals or an important bug was fixed.

I would advise to either

* Upgrade your fmt to something newer.
* Build OIIO with `-DBUILD_FMT_FORCE=ON`, which will force OIIO to download its preferred version of fmt rather than use the one it finds on the system.

**Comment by Sunderland93** [comment]
Thanks, it helps!
