### ISSUE TITLE
[BUG] OpenImageIO/strutil.h macro pollution

### ISSUE THREAD

**Issue by johnhaddon** [OpenImageIO/oiio#3000]
**Describe the bug**

`OpenImageIO/strutil.h` includes `OpenImageIO/detail/farmhash.h`, which defines macros for many common names, including [`fmix`](https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/detail/farmhash.h#L1142). This pollutes the namespace, breaking client code (in this case, Gaffer).

**To Reproduce**

Compiling this code :

```
#include "OpenImageIO/strutil.h"

namespace Test
{
    uint64_t fmix( uint64_t k );
}
```

Results in an error along these lines :

```
test.cpp:5:10: error: ‘farmhash’ has not been declared
    5 | uint64_t fmix( uint64_t k );
```

**Expected behavior**

Compilation succeeds. OIIO's public headers only define macros with an OIIO prefix.

**Evidence**

https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/detail/farmhash.h#L1142

**Platform information:**
 - OIIO branch/version: Version 2.2.15.1.
 - OS: CentOS 7.
 - C++ compiler: GCC 9.3.1
 - Any non-default build flags when you build OIIO:

**Comment by johnhaddon** [comment]
Now I've tracked this down, I can workaround using `#undef fmix` after the OIIO includes, so this is not especially urgent.

**Comment by lgritz** [comment]
Fix in #3002

**Comment by johnhaddon** [comment]
Thanks Larry! That was quick!

**Comment by lgritz** [comment]
Sorry about that. It used to be an internal header (we didn't write it, it came from the farmhash project), but recently we made it public so that the ustring hash could be inline and constexpr for the sake of running identically on GPU, and I guess we didn't realize how much that header pollutes with preprocessor symbols. 

I'm still not super happy with the `#define` and `#undef` approach, I would prefer either fully named `FARMHASH_blah` or for them to all be private namespace inline functions or constants. But because this file comes from another project, I'm hesitant to diverge and end up where it's hard to diff or to upgrade the contents with new versions of farmhash.
