### ISSUE TITLE
OpenColorIO find module fails to locate versioned OCIO v2 lib

### ISSUE THREAD

**Issue by michdolan** [OpenImageIO/oiio#3048]
**Describe the bug**
The `FindOpenColorIO.cmake` module fails to locate OCIO v2 libs due to versioned naming. By default OCIO will now build libraries named like `OpenColorIO_2_0.lib`, but the find module expects `OCIO.lib` or `OpenColorIO.lib`. I know the more ideal solution here is to rely on the OCIO CMake module, which was recently added and will be included in OCIO v2.0.2 and v2.1.0: https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/cmake/Config.cmake.in , but just wanted to flag this as a current build issue I ran into.

**To Reproduce**
1. Build OCIO v2.0.1
2. Configure OIIO with the argument: `-DOpenColorIO_ROOT="/path/to/OpenColorIO"`
3. CMake will fail to locate the OCIO library

**Evidence**
```
-- OpenColorIO library not found 
--     OpenColorIO_ROOT was: .../install/msvc142-x64-cxx14-release-py37/ocio-2.0.1 
--     Maybe this will help:  src/build-scripts/build_OpenColorIO.bash 
```

Lib is located here in my env:
`.../install/msvc142-x64-cxx14-release-py37/ocio-2.0.1/lib/OpenColorIO_2_0.lib`

**Platform information:**
 - OIIO branch/version: 2.2.16.0
 - OS: Windows
 - C++ compiler: MSVC 14.2
 - Any non-default build flags when you build OIIO: I specified `OpenColorIO_ROOT` to point to my OCIO build

**Comment by lgritz** [comment]
Thanks for the alert, will fix right away!

**Comment by lgritz** [comment]
@michdolan, it's interesting that OCIO is folding the major/minor version into the library name now. OpenEXR/Imath also do this, but OIIO does not. Can you say a few words about what led you to that decision? Is it something I should be doing in my libraries as well?

**Comment by michdolan** [comment]
Thanks @lgritz ! 

I believe the motivation was to prevent name clashes of different library versions installed together on a system. @hodoulp could you provide some additional insight on this change?

**Comment by hodoulp** [comment]
The OCIO library is careful to avoid having issues when two OCIO libraries (with potential different versions) are used in the same app.

To avoid issues of `name clashes` or worst `app crashes`, the dynamic library name & namespace name are always (i.e. all platforms) versioned. The design is an enhancement of the Linux convention.
On the other hand, the static library name is never versioned because it's useless (but the namespace name is still versioned). The symbol hiding is the way to go when included in an app or in a third-party library (dynamic or not) -- or -- you can do nothing (symbols are still versioned) but it will pollute your app table of symbols. For example, if dyn. libraries A & B both internally need OCIO then ideally the OCIO symbols must be hidden by A & B project settings.

To go back to the issue, I did my tests on MacOS & Windows  for `master` and `RB-2.0` without finding a versioned static library name.

@michdolan Could you provide some details on how you compile OCIO?

**Comment by michdolan** [comment]
I am building the OCIO shared library on Windows, which also builds an import library with the same name for linking, so:
```
bin/OpenColorIO_2_0.dll
lib/OpenColorIO_2_0.lib
```

**Comment by hodoulp** [comment]
I compiled in static library mode, not in dynamic library mode. I can now reproduce the problem.

**Comment by hodoulp** [comment]
**That's another candidate for 2.0.2**

**Comment by michdolan** [comment]
@hodoulp if this is something we plan on fixing, is it still worth @lgritz fixing in the OIIO find module? Seems like it's more of an unintentional side effect on our end based on your input.
