### ISSUE TITLE
[BUG] Writing a PNG file using only the RGBA of an OpenEXR file with large number of channels 

### ISSUE THREAD

**Issue by lucienfostier** [OpenImageIO/oiio#3266]
**Describe the bug**
I'm not sure if it qualifies as a bug but I have found OIIO to be slower than other tools ( Autodesk RVIO/Foundry Nuke ) to write a PNG file (RGBA) from an OpenEXR file that has a large number of channels (302).

**To Reproduce**
1.`rvio -exrReadWindowIsDisplayWindow exrManyLayers.exr -resize 256 0 -o thumbnail.png` takes 6s
2.`oiiotool -i:ch=R,G,B,A exrManyLayers.exr -o thumbnail.png` takes 30s

**Expected behavior**
I wish oiiotool would match the performance of `rvio` or `nuke` when reading only a subset of the image ( my test file is not multi part but the performance is still slower with a multi part file and writing multi part is currently not an option in our workflow ).

**Evidence**
Attaching a test file that I used( https://github.com/OpenImageIO/oiio/files/7818080/exrManyLayers.exr.zip )

**Platform information:**
 - OIIO branch/version:OpenImageIO 2.2.6
 - OS:Cent7
 - C++ compiler:gcc 6.3.1

**Comment by agalbrai** [comment]
[exrManyLayers.exr.zip](https://github.com/OpenImageIO/oiio/files/7818080/exrManyLayers.exr.zip)

**Comment by lgritz** [comment]
Thanks for the example.

I tried this on my end, and I can't reproduce the behavior. On my laptop, that command runs in 3 seconds.

I noticed you are using an older version of OIIO. So I thought maybe it's something that has been greatly improved since then. I rebuilt the top of the 2.2 branch, and it still ran very quickly for me. But that's 2.2.19, so maybe still too new? Alas, when I tried to rebuild the 2.2.6 that you reported using, I was unable to get it to build against the current versions of several dependencies that I have on my machine now, so I could not directly test that.

So I have a few experiments for you, if you are able:

1. Are you able to try with the current release, 2.3.11.0?

2. If even a modern version still runs very slowly, then please run `oiiotool -runstats -i:ch=R,G,B,A exrManyLayers.exr -o thumbnail.png` and post the results here. Perhaps the detailed statistics will reveal more about what might be going on.

3. Other things to check: Are you sure the version you're using (and all its important dependencies like OpenEXR itself) are optimized release builds, not accidentally a debug build or anything like that? And can you also `env | egrep -i "OIIO|OpenImageIO"` just to make sure there isn't an environment variable accidentally set that might be impacting performance.

**Comment by lucienfostier** [comment]
Hi Larry,

Thanks for looking it!
I will do so more testing on my end and share the result.

Thanks again
Cheers!

**Comment by lgritz** [comment]
Great. That's so out-of-whack that I'm sure there is something funny going on, and surely some way to make it much better.

**Comment by lucienfostier** [comment]
```
oiiotool -runstats -i:ch=R,G,B,A exrManyLayers.exr -o thumbnail.png --threads 0

Threads: 1
oiiotool runtime statistics:
  Total time: 28.43s
      -o           :  0.30
      croptofull:allsubimages=1 :  0.06
      input        : 28.06
      unaccounted  :  0.00
  Peak memory:    316.9 MB
  Current memory: 222.0 MB

OpenImageIO ImageCache statistics (shared) ver 2.2.6
  Options:  max_memory_MB=4096.0 max_open_files=100 autotile=0
            autoscanline=0 automip=0 forcefloat=1 accept_untiled=1
            accept_unmipped=1 deduplicate=1 unassociatedalpha=0
            failure_retries=0 
  Images : 1 unique
    ImageInputs : 1 created, 1 current, 1 peak
    Total pixel data size of all images referenced : 6.2 GB
    Total actual file size of all images referenced : 6.3 MB
    Pixel data read : 0 B
    File I/O time : 0.0s
    File open time only : 0.0s
    Peak cache memory : 0 B
  Image file statistics:
        opens   tiles    MB read   --redundant--   I/O time  res              File
      1    1        0        0.0                       0.0s  5326x2084x302.f16  exrManyLayers.exr  UNTILED

  Tot:     1        0        0.0   (    0    0.0)      0.0s
  1 not tiled, 1 not MIP-mapped
  Broken or invalid files: 0
```
This is the runstats result.
There are a couple of things that are weird. First I noticed `Threads` as 1 so I tried to force the thread count in the command line.
`--threads 0` always give me 1 in the runstats log and when I use `--threads 12` is used I can see `Threads: 12` in the log but the runtime is equivalent.

Also I tried out of curiosity to install OIIO on my personal machine and it's running 2.1.17 and has a similar runtime as you reported.

So yeah something is very strange indeed.
Our IT department will have a new build tomorrow so hopefully I will test on something more modern.
Will keep you posted!
Thanks

**Comment by lgritz** [comment]
I did notice when I ran it on my end 

    $ time oiiotool -i:ch=R,G,B,A exrManyLayers.exr -o rgba.png
    real	0m2.912s
    user	0m24.966s
    sys	0m1.245s

The user time (across all threads) was suspiciously close to the 30s you complained about, so I did wonder if maybe there was something forcing it to run single threaded.

When you run `oiiotool --help` it will (among other things) give you an inventory of hardware and build-time features, like this:

    OIIO 2.4.0 built for C++14/201402 sse2,sse3,ssse3,sse41,sse42
    Running on 16 cores 32.0GB
        sse2,sse3,ssse3,sse41,sse42,avx,avx2,fma,f16c,popcnt,rdrand

What does oiiotool think your core count is?

I still don't have any hypothesis for why --threads 12 would still not run any faster.
That file uses zip compression scanline-by-scanline. When reading large exr files, the decompression is a big part of the runtime, so you should see a big change when using 1 vs 12 threads, no matter what else may be afoot, since it should be able to decompress in parallel.

Is it remotely possible that something about the hardware configuration, environment, or some limit set in the shell, is instructing the OS to not give you more than one core to run on?

**Comment by lucienfostier** [comment]
Hi Larry,

I think I have identified the culprit, we started using `OPENIMAGEIO_THREADS` a while ago because of performance problem when using AMD proc with a very large number of threads.

Interestingly it seems that `--threads` argument did not take precedence on the env var so I had the same runtime.

Thanks for pointing in the right direction anyways. Now it seems to be working fine and fast with `oiiotool` but I still have some issue when using the ImageReader in Gaffer so I need to debug further.

Thanks!
Lucien

**Comment by lgritz** [comment]
Aha, I'm glad you're on the right rack.

I don't understand the `--threads` behavior, are you quite sure? I can't reproduce it:

    OPENIMAGEIO_THREADS=1 oiiotoool --runstasts <expensive stuff>

definitely is single threaded, and

    OPENIMAGEIO_THREADS=1 oiiotoool --runstasts --threads 8 <expensive stuff>

is definitely multithreaded.

The OPENIMAGEIO_THREADS env variable is used to initialize some statics, and the command line is definitely parsed after that.  I'm not sure how the env variable could take precedence. Maybe this is also something that was fixed at some point, or did you try with a newer OIIO?

**Comment by lucienfostier** [comment]
Hey Larry,

sorry for the delay to answer.
Here is the test I've done:

`OPENIMAGEIO_THREADS=1 oiiotoool --runstasts <expensive stuff>`

```
Threads: 1
oiiotool runtime statistics:
  Total time: 28.17s
      -o           :  0.21
      croptofull:allsubimages=1 :  0.09
      input        : 27.86
      unaccounted  :  0.01
  Peak memory:    312.8 MB
  Current memory: 217.9 MB

OpenImageIO ImageCache statistics (shared) ver 2.2.6
  Options:  max_memory_MB=4096.0 max_open_files=100 autotile=0
            autoscanline=0 automip=0 forcefloat=1 accept_untiled=1
            accept_unmipped=1 deduplicate=1 unassociatedalpha=0
            failure_retries=0 
  Images : 1 unique
    ImageInputs : 1 created, 1 current, 1 peak
    Total pixel data size of all images referenced : 6.2 GB
    Total actual file size of all images referenced : 6.3 MB
    Pixel data read : 0 B
    File I/O time : 0.0s
    File open time only : 0.0s
    Peak cache memory : 0 B
  Image file statistics:
        opens   tiles    MB read   --redundant--   I/O time  res              File
      1    1        0        0.0                       0.0s  5326x2084x302.f16  exrManyLayers.exr  UNTILED

  Tot:     1        0        0.0   (    0    0.0)      0.0s
  1 not tiled, 1 not MIP-mapped
  Broken or invalid files: 0

```

`OPENIMAGEIO_THREADS=1 oiiotoool --runstasts --threads 8 <expensive stuff>`


```
Threads: 8
oiiotool runtime statistics:
  Total time: 27.16s
      -o           :  0.21
      croptofull:allsubimages=1 :  0.08
      input        : 26.85
      unaccounted  :  0.01
  Peak memory:    312.8 MB
  Current memory: 218.0 MB

OpenImageIO ImageCache statistics (shared) ver 2.2.6
  Options:  max_memory_MB=4096.0 max_open_files=100 autotile=0
            autoscanline=0 automip=0 forcefloat=1 accept_untiled=1
            accept_unmipped=1 deduplicate=1 unassociatedalpha=0
            failure_retries=0 
  Images : 1 unique
    ImageInputs : 1 created, 1 current, 1 peak
    Total pixel data size of all images referenced : 6.2 GB
    Total actual file size of all images referenced : 6.3 MB
    Pixel data read : 0 B
    File I/O time : 0.0s
    File open time only : 0.0s
    Peak cache memory : 0 B
  Image file statistics:
        opens   tiles    MB read   --redundant--   I/O time  res              File
      1    1        0        0.0                       0.0s  5326x2084x302.f16  exrManyLayers.exr  UNTILED

  Tot:     1        0        0.0   (    0    0.0)      0.0s
  1 not tiled, 1 not MIP-mapped
  Broken or invalid files: 0
```

As you can see the number of threads is correct but the runtime is more or less the same.

I'm happy to close the issue for my original problem but I'm happy to help so more if that last result is unexpected for you.
