### ISSUE TITLE
Add support for std::wstring for open

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3304]
Windows supported files that cannot be represented in std::sting. so the attached file cannot be loaded.

[test.zip](https://github.com/OpenImageIO/oiio/files/7930273/test.zip)

**Comment by lgritz** [comment]
All the places in OIIO that take strings for filenames assume utf8. In strutil.h, there are (on Windows) exposed utility functions `std::string utf16_to_utf8(const wstring&)` and `wstring utf8_to_utf16(const string&)`.

Do you think that (a) everyplace in the API that takes a string as a filename also needs a second wstring-based wrapper that simply calls utf16_to_utf8 and then passes it to the usual string version of the call? Or (b) should we just be better at documenting that the filenames are utf8 and evangelize the existence of utf16_to_utf8?

I'm not a Windows programmer. I've never seen wstring used in the actual code myself (except, myself, when converting utf8 std::string to wstring to pass to Windows open commands and the like).  Is wstring very common in user code, arguing for solution (a) above? Or is it only for the rare case when somebody may be fitting OIIO into an application that is unusual in its use of wstring, in which case maybe (b) is easier?

**Comment by DougRogers** [comment]
Microsoft is strongly encouraging unicode which defaults to all string being wstring.  wstring is use primarily to support other languages that cannot be represented in the standard eight bits.  

It is possible that some files cannot be converted to eight bits, but it works for this case.  

If there are a lot of front facing API call that use std::string, it is probably not worth adding the layer and documentation is sufficient   If there are cases where std::string fails to encode the filename, then it may be worth revisiting.

**Comment by lgritz** [comment]
My understanding is that on Windows, `fopen(const char*)` treats the string as ASCII by default, not UTF-8, so if you want to use Unicode characters in filenames, you have to open with `_wfopen(const wchar_t*)`. On modern Unix-like systems, all the underlying OS and standard C/C++ functions involving filenames (like `fopen()`) treat those names as UTF-8.

To deal with this discrepancy, we avoid std::fopen and instead use our own `Filesystem::fopen()` that does a little extra magic on Windows of translating utf8 to utf16 and calling _wfopen underneath (and on Unix, just calls the system fopen straightforwardly). This translation is handled by Strutil::utf8_to_utf16(); that and its inverse, utf16_to_utf8(), are exposed (for Windows only) in strutil.h

OIIO therefore supports UTF-8 filenames for all its API functions that take filename strings (such as `ImageInput::open()`).

Our assumption thus far has been that if a Windows app with wchar-based unicode filenames makes OIIO API calls, it should just pass the filename through utf16_to_utf8 before handing it to OIIO.

But if this is a bit PITA because in Windows land people are just universally using wstring and not std::string at all, at least for filenames, then I wouldn't be averse to adding inline wrappers providing wstring flavors of the obvious filename-related methods, so something like

    class OIIOClass {
        virtual bool open(const std::string& filename);   // Existing method, assumes UTF-8

        // Proposed non-virtual addition that does string translation
        inline bool open(const std::wstring& filaneme) {
           return open(Strutil::utf16_to_utf8(filename));
        }
    };

I don't have a very strong feeling about whether, from an overall complexity and aesthetic perspective, this sprinkling of additional wstring shims all over the API is preferred over just better-documenting which API calls support UTF-8 and expecting Windows users who are already using wstrings in their apps to do the conversion themselves.

In the process of looking into this, I did just submit #3307 which slightly simplifies/modernizes our implementation of the UTF conversion utilities (which I think had even predated our ability to rely on C++11), which additionally removes the `#if` guards that exposed those utilities only on Windows. That makes it fairly easy to add the wstring wrapper methods on all platforms.

What's your current opinion about the best way to proceed -- adding more entry points for wstring filenames everywhere, or better documenting the utility functions and relying on the callers to use them?

It's not an especially big deal to add the new methods. Each one individually is trivial; the work is in tracking down all the places where they are needed, but that doesn't technically need to be done all at once. And because they are not virtual functions, they don't change ABIs and are safe to backport to the release branch.

**Comment by DougRogers** [comment]
I would prefer the std::wstring wrapper.  In Windows, every _char_ function has the equivalent _wchar_t_ function.

**Comment by lgritz** [comment]
ok, that should be straightforward.

**Comment by lgritz** [comment]
Took a stab at this in  #3312
