### ISSUE TITLE
Issue with OpenImageIO.BASETYPE in python3

### ISSUE THREAD

**Issue by rebx** [OpenImageIO/oiio#3346]
**Describe the bug**
Sorting BASETYPEs causes a TypeError exception in python3

**To Reproduce**
1. execute the python 3 interpreter
2. run the snippet below 
```py
import OpenImageIO as oiio; sorted([oiio.BASETYPE.UCHAR, oiio.BASETYPE.UCHAR])
```
3. You will see the error below: 
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'OpenImageIO.BASETYPE' and 'OpenImageIO.BASETYPE'
```

**Expected behavior**
No TypeError should be thrown for the given snippet

**Evidence**
![Screen Shot 2022-02-22 at 10 10 11 PM](https://user-images.githubusercontent.com/105413/155099666-5ae76465-1aa2-4352-b581-0275d796ebdd.png)

**Platform information:**
 - OIIO branch/version: 2.2.1
 - OS: OSX and Linux
 - C++ compiler:
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
I'm admittedly not a Python expert (I can get around for writing small programs, but I don't use it myself for large-scale software).

But it looks here https://docs.python.org/3/library/enum.html#comparisons like this is not expected to work:

> Ordered comparisons between enumeration values are not supported.

I note also that you can sort the integer values by casting:

    # works:
    sorted([int(oiio.BASETYPE.UCHAR), int(oiio.BASETYPE.FLOAT)])

    # generates exception:
    sorted([oiio.BASETYPE.UCHAR, oiio.BASETYPE.FLOAT])

Do the experienced Python programmers out there tend to expect that our enums should allow comparison without the cast?

**Comment by nrusch** [comment]
In general, I wouldn't really expect Python enums to support any meaningful arithmetic unless they are enums of flags.

If the values are arithmetically comparable, there's a bit of a danger in someone assuming that, because (most of) the `BASETYPE` enum labels describe a clearly-sized type, the comparison is based on the type's bit size rather than the enum value (e.g. they might consider it a bug that `oiio.BASETYPE.INT64 < oiio.BASETYPE.HALF == True`), but that can easily be considered user error.

The comparisons do currently work when using Python 2, so maybe this really comes down to a question of correctness vs. consistency? Personally, I don't feel like changing the current Python 3 behavior would be particularly valuable, and I think the reduced ambiguity is good.

**Comment by lgritz** [comment]
Thanks, @nrusch, that confirms my intuition. I'm going to close this issue.

**Comment by rebx** [comment]
Cheers @lgritz and @nrusch for looking into it.
