### ISSUE TITLE
[FEATURE REQUEST] memory I/O names

### ISSUE THREAD

**Issue by OgreTransporter** [OpenImageIO/oiio#3426]
Why is it actually called `IOMemReader` and `IOVecOutput`? Wouldn't `IOMemReader` and `IOMemWriter` be more intuitive? Or `IOVecInput` and `IOVecOutput`?

**Comment by lgritz** [comment]
Your original issue asked how to use IOProxy with ImageBuf. (Yes you can!) Now it appears to be edited to no longer ask that. Does that mean you figured it out?

**Comment by lgritz** [comment]
Naming is hard. We don't always get it right, and sometimes the most intuitive names are only apparent in retrospect.

But in this case, I think we did mostly the right thing.

The IOMemReader is in some sense truly generic -- it just needs be given a memory address and know the length (either as a pointer + size, or as a `cspan<char>`). This covers all the bases, and it's hard to imagine that another reader-from-memory will ever be needed.

Writing to memory is harder, and we can imagine several possible implementations, all useful in different cases. This one specifically writes to a `std::vector<unsigned char>`, so we called it **IOVecOutput**. If we write a different one that, say, that fills a fixed buffer and errors if it runs out of space, that should be named something different. Or maybe somebody wants one that takes an address to a pointer and calls realloc() when it needs to grow, that would be another implementation with a different name. And so on. I didn't call it IOMemWriter because I wasn't confident that it was the one generic writer that would serve all cases.

**Comment by lgritz** [comment]
More detail:

> Wouldn't IOMemReader and IOMemWriter be more intuitive?

Because the latter isn't actually a generic writer to memory, it specifically requires a std::vector.

> Or IOVecInput and IOVecOutput?

Because IOMemReader *is* just a generic reader from memory that does not require a vector, but the IOVecOutput does require a std::vector.

Why not IOMemReader and IOVecWriter (just for the symmetry of reader/writer)? Yeah, that would be a good suggestion. It probably would be a little bit cleaner. I wish I had named it that. But now that the name is set, changing it to something that is only a little bit better is probably not worth the pain of changing the name now that people are using it.

(And, oh boy, there are SO MANY THINGS that I wish had been named differently. This isn't even close to the top of that list! But, alas, all of those things would be extremely disruptive to change now that it's so widely used.)

**Comment by OgreTransporter** [comment]
Yes, I have been able to solve the original problem. It took a while because the naming is a bit confusing. Thanks a lot!

Renaming is possible. There is nothing against it in a new main version 3.x.x to change the names. You just have to point out that the API has changed. With `typedef` you can keep the old names for compatibility and then declare them as deprecated. You can do that even now, if you don`t want to change the API but only the names.

I like the idea to use vectors and memory in pairs `IOMemReader`/ `IOMemWriter` and `IOVecInput`/ `IOVecOutput`. Or you remove `IOMemReader` completely and create `IOVecInput` with an additional constructor which also accepts memory and size and copies the bytes into the vector.
