### ISSUE TITLE
[BUG] read_native_tiles is much faster than read_tiles in some tiled OpenExr files.

### ISSUE THREAD

**Issue by klydeid** [OpenImageIO/oiio#3429]
**Describe the bug**
Hello. 
i'm not sure if this is a bug. so if i was wrong. please forgive me.

in my application i use OIIO for reading image.
most image file are working fine with ImageInput class then use read_image() function to read image data to memory.
but i found that reading some tiled OpenExr file is very slow in this method. i don't know why.

i have tested this tiled OpenExr files with read_tiles() function. it can get the right result. but as slow as read_image().
then i tried the read_native_tiles() function. magic happen...
the reading speed is 10x faster then another method with right result.

so here is my question. is this normal? 
what is the "native" means in read_native_tiles() function?
how can i determine that when to use the read_native_tiles() function?

**Expected behavior**
i just want to read all image file as soon as possible.

**Evidence**

**Platform information:**
 - OIIO branch/version: 2.3.15
 - OS:windows
 - C++ compiler: visual studio 2019

**IF YOU ALREADY HAVE A CODE FIX:** There is no need to file a separate issue,
please just go straight to making a [pull request](https://github.com/OpenImageIO/oiio/pulls).

**Comment by lgritz** [comment]
It's hard to tell without seeing your code and perhaps without a sample image so we can try it ourselves. So I don't know if you're encountering a bug. But maybe this explanation will help.

read_image just calls read_tiles underneath, with very little extra processing (in the case of openexr), so I expect them to be exactly the same speed, as you observed.

About read_tiles vs read_native_tiles:

* read_tiles takes a data type and strides, so it's expected to translate the data from whatever type was *actually* in the file, into the format you requested, and also has the option of rearranging the layout of the data according to the stride values it is passed.

* read_native_tiles reads exactly the data from the tiles and just dumps it contiguously into a buffer, with no adjustment or translation. You may notice that it does not take a `format` (data type) parameter, nor does it take "stride" values.

Format reader plugins only implement read_native_tiles -- it's simple, and we don't want every format reader to separately need the full complexity of knowing how to translate to any data type or how to deal with weird strides.

We expect applications to only call read_tiles -- which does all the data translation and shuffling for them -- because every application should not have to separately implement support for the full complexity of every possible data type translation and stride values, which is what they would need to do if they directly called read_native_tiles.

Simple reader. Simple application. All the complexity is hidden inside read_tiles(), and which only is implemented once for all application X reader combinations.

Now then, the speed. When calling read_tiles, if the data in the file is already the **same** data type that you request, and you are passing the default stride lengths that designate a "contiguous" data layout, the underlying call to read_native_tiles will write directly to your buffer, and read_tiles will appear to be the same speed as read_native_tiles (other than just a tiny bit of overhead for some parameter checking, etc).

But if you are asking read_tiles to do a bunch of extra work -- for example, requesting UINT8 data to be written to your buffer, from an OpenEXR file that is a mixture of 'half' and 'float' channels -- then obviously there is a whole lot of data type translation and channel-by-channel copying going on.

So I'm assuming that if you are noticing a big difference in how long it takes to read_tiles versus read_native_tiles, that probably means your read_tiles call is asking for a different data type than what's in the file. (Which also means: if you call read_native_tiles and aren't doing the translation on your end, your program is also very likely misinterpreting the pixel data because it thinks it's a different type than it really is.)

I'm going to close because I think I've answered your question fully and there is not likely any bug here, just a misunderstanding. But if you think it's really doing something wrong, please re-open the issue and provide us with sample code and a sample file, to demonstrate the problem, and we'll try to look into it right away.
