### ISSUE TITLE
Unable to open GIF

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3430]
[grabber.zip](https://github.com/OpenImageIO/oiio/files/8872035/grabber.zip)

Fails to open.  I have other examples.

```
            ImageSpec config;
            config["oiio:UnassociatedAlpha"] = 1;

            auto imageInput = ImageInput::open(entry.path(), &config);
```

**Comment by lgritz** [comment]
I haven't been able to repro on either Mac or Linux.

Some follow-up questions:

1. Does it still fail if you don't use the config? (Is is related to the request for unassociated alpha?)
2. Does it crash, or just refuse to open? If the latter, is there any error message?
   ```
   auto imageInput = ImageIput::open(...);
   if (!imageinput)
       Strutil::print("could not open, error was: {}\n", OIIO::geterror());
   ```
3. What version of gif library are you using, and are you sure you built OIIO with GIF support?
   ```
   oiiotool --help | grep -i gif
   ```
   what does that say?
4. Can you reproduce from any of the standard utilities, such as `oiiotool -info -v -stats grabber.gif` ?

**Comment by DougRogers** [comment]
Apologies.  GIF was not included as a build option.

**Comment by DougRogers** [comment]
Here is an odd GIF.  OIIO and Photoshop cannot open it. Some programs have the bottom shifted over, but IrfanView displays it correctly.

[earth.zip](https://github.com/OpenImageIO/oiio/files/8884841/earth.zip)

**Comment by lgritz** [comment]
Apple Preview.app also refuses to open earth.gif.

```
$ oiiotool earth.gif -o out.tif
oiiotool ERROR: read : "earth.gif": GIF read error at position 51684, asked for 130 bytes, got 28 (total size 51712)
Failed to read from given file
```

It may be possible to try to recover from the error (as Irfanview, and I think ImageMagick *appear* to do), but the thing that worries me is that accepting clearly broken files and trying to interpret them anyway might expose us to a new set of bugs in other places -- that is, being tolerant of flaws is great IF you can definitely eek out a correct interpretation despite the corruption, but I'm not sure how we'd know that we interpreted it correctly, and we might end up giving every indication to the app that things are fine but actually be returning the wrong image that will lead to a cascade of downstream errors.

Given that other widely used (and presumably robust) programs also recognize the file as damaged and refuse to open it makes me very confident that it really is a nonconformant or damaged file. Since OIIO has no crash, and gracefully recovers and prints a specific error message, I'm tempted to declare victory here and move on.

**Comment by DougRogers** [comment]
Not work trying to fix broken image files
