### ISSUE TITLE
[BUG] Cannot read all attribute types via Python

### ISSUE THREAD

**Issue by nrusch** [OpenImageIO/oiio#3537]
Currently, the Python bindings cannot be used to read the values of attributes with more "exotic" types. This includes things like `int64` (e.g. for `ImageCache` statistics like `stat:cache_memory_used` or `stat:image_size`), or `string[]` (e.g. for `ImageCache` `all_filenames` attribute).

Looking at the `ImageBuf` source, I have a feeling the same limitations more than likely apply there as well.

It would be great to be able to access these sorts of "extended" attributes using the Python API.

**Comment by lgritz** [comment]
On it!

**Comment by lgritz** [comment]
OK, I have solutions, some immediate and some coming soon.

1. I can see now that `ImageCache.getattribute("name")` is broken and will always fail. For ImageCache, you currently *must* specify the type you expect. So some of what you ask for will work right now, provided you supply the types:

```python
import OpenImageIO as oiio

# Just force something to be seen by the cache
imgBuf = oiio.ImageBuf("build/testsuite/j2kp4files_v1_5/testfiles_jp2/file5.jp2")

ic = oiio.ImageCache()
total_files = ic.getattribute("total_files", 'int')
print ("total_files", ic.getattribute("total_files", 'int'))
print ("all_filenames", ic.getattribute("all_filenames", 'string[{}]'.format(total_files)))
```
prints:
```
total_files 1
all_filenames ('build/testsuite/j2kp4files_v1_5/testfiles_jp2/file5.jp2',)
```

2. It is currently broken to ask for the attributes (in Python) that are int64 or uint64. For that reason, you can't get stat:cache_memory_used or stat:image_size, because they are int64.

I have a tiny patch that fixes this, coming right up!

3. Making getattribute() work without passing the type is trickier, turns out that I need to make a breaking change to a C++ API to pull it off. There's *just* enough time to squeeze it into OIIO 2.5, which I was going to release today, but which I think is worth postponing for this.

**Comment by nrusch** [comment]
> For ImageCache, you currently must specify the type you expect. So some of what you ask for will work right now, provided you supply the types

Ah, I didn't realize that you could pass string type symbols. I've confirmed that using a sized `string[]`... string works (I was just trying to pass in `oiio.TypeString` originally).

However, the fact that you need to include the array length for those seems like it would basically break the ability to look up `string[]` attributes read from input image headers. Granted, I'm not aware of a real-world scenario where that could occur, but people do crazy stuff with TIFF containers with some regularity...

> I have a tiny patch that fixes this, coming right up!

That's great, thank you!

> Making getattribute() work without passing the type is trickier, turns out that I need to make a breaking change to a C++ API to pull it off. There's just enough time to squeeze it into OIIO 2.5, which I was going to release today, but which I think is worth postponing for this.

That's a great bonus! However, if it ends up being too much of a can of worms for a short-term fix, I don't think requiring a type to be passed is a huge deal.

**Comment by lgritz** [comment]
yeah, the python bindings have an implicit ability to convert strings (e.g. 'int') to TypeDesc (`TypeDesc(TypeDesc.INT)`).

**Comment by lgritz** [comment]
Proposed fix for getting int64/uint64 getattribute working: #3555
