### ISSUE TITLE
[FEATURE REQUEST] Make fmt library a true dependency

### ISSUE THREAD

**Issue by DominikGrabiec** [OpenImageIO/oiio#3595]
**Problem Description**
I am trying to use a OpenImageIO in a Windows DLL to be used as a plugin for an application I am developing but I keep running into compiler/linker issues. I've managed to work around the previous issues I've encountered but I can't fix this one myself easily as it would involve modifications to the build systems and there is no documentation on how to do a clean Windows build.

In order to keep DLL dependencies to a minimum I am using static libraries and therefore also compiling OIIO as a static library. This worked to begin with until I started building out the plugin DLL and adding in other error handling code which also used the `fmt` library. This caused linker errors because OIIO has its own custom way of inlining the fmt library which seems compilcated and unnecessary and also does not interoperate well with other package systems.

**Proposed Solution**
One or more of the following would be greatly appreciated:
* Introduce a CMake variable (`USE_EXTERNAL_FMT`) like the existing one for the `pugixml` library, which will prevent inlining a header-only version of the `fmt` library into the codebase.
* Provide up to date instructions to build on Windows outside of vcpkg so I can try to do it myself and send a patch.
* Ideally though remove the custom code which embeds the fmt lib and just use CMake dependency resolution to pull a fmt lib from the outside environment.

I know that there are details that make it complicated:
* That there are other build systems supported than just CMake so changes will need to be made to others as well.
* The fmt library is being configured with specific settings because some of the code still uses old stream formatters.
* That some of these issues could be vcpkg related and should be brought up there instead.

**Alternative Solutions Attempted**
* I tried building OIIO as a dynamic library by changing the vcpkg triplet to add a custom override for `if(PORT MATCHES "openimageio")` but it failed to build because `typedesc_test.cpp` has unresolved externals to OpenEXR.
* If I added `-DOIIO_BUILD_TESTS=OFF` to the `portfile.cmake` in vcpkg then it failed to link `OpenImageIO.lib` with a whole lot of unresolved externals to the Imath and OpenEXR libraries.

**Comment by lgritz** [comment]
I think it's a very reasonable request to have a cmake option that lets OIIO use an external fmt. Let me try to whip something up. (When enabled, it would be on the builder/user to ensure that the externally installed fmt was in the right version range, etc.)

As to your last couple of points, the way we expose/hide OpenEXR has changed recently, so I'll be interested to hear if these are resolved when vcpkg upgrades from 2.3.x to 2.4.x.

**Comment by lgritz** [comment]
Wait, I think this may already exist: https://github.com/OpenImageIO/oiio/blob/master/src/cmake/externalpackages.cmake#L307

I think that building with `-DBUILD_MISSING_FMT=OFF` will prevent it from downloading a fresh copy of fmt and either use the installed one or fail if no installed fmt is found.

However, it does seem to copy the fmt headers into `include/OpenImageIO/detail` and use them from there. I'm not sure if that's a problem, but we can probably rig it to only do that in the "download and install" case.

So I would be interesting in hearing from you: when building 2.4 with BUILD_MISSING_FMT=OFF, which problems remain, and is there more to do?

**Comment by DominikGrabiec** [comment]
When I was building the vcpkg version 2.3.17.0 it was setting `BUILD_MISSING_FMT=OFF` because I checked that in the CMakeCache.txt. However it was still copying the fmt headers into the `detail/fmt/` directory which compiled the fmt library symbols inside `OpenImageIO.lib`. This meant meant I couldn't link OIIO and another fmt library into the same project.

I think it's slightly more complicated to remove this embedded fmt library as OIIO has certain settings that it sets before including the fmt library, which might need code changes in a lot of places. Unless I'm mistaken and the old `operator<<` formatter is only defined in the header files.

**Comment by lgritz** [comment]
Trying to take a step forward on this with #3598
Are you able to pull that patch on your side and see if it gets you closer?

**Comment by DominikGrabiec** [comment]
I'll try to give it a go but given that the `OpenImageIO/detail/fmt.h` file still defines header only usage of `fmt` my intuition says that the OIIO static library will be built with the symbols inside of it.

**Comment by lgritz** [comment]
Oh, I see. So for externally found fmt, do you think we should not set that symbol for header-only?

**Comment by DominikGrabiec** [comment]
I believe that would do it, as it would allow the person that supplied the external fmt library to determine how it is used. 

That's also where I see this being more complicated as there are other fmt settings that are set in the `detail/fmt.h` file like `FMT_EXCEPTIONS`, `FMT_USE_GRISU`, and `FMT_DEPRECATED_OSTREAM`, which could affect how the fmt library is built and might conflict with the external version. If these settings only affect the header files then that's going to be ok, if not then it might require more work. I'll try and take a look at the fmt library tomorrow and see if there could be issues or not.

**Comment by DominikGrabiec** [comment]
Even though they are inline functions, because they are used by OIIO they are included inside the OIIO static library. 

I built using vcpkg just quickly to verify this and even with `BUILD_MISSING_FMT:BOOL=OFF` and `BUILD_FMT_FORCE:BOOL=OFF` in the `CMakeCache.txt` it still included a bunch of fmt symbols in the library, then when I link I get a bunch of linker errors for already defined symbols.
```
2>fmt.lib(format.cc.obj) : error LNK2005: "int __cdecl fmt::v9::detail::fmt_snprintf(char *,unsigned __int64,char const *,...)" (?fmt_snprintf@detail@v9@fmt@@YAHPEAD_KPEBDZZ) already defined in OpenImageIO.lib(tiffinput.cpp.obj)
2>fmt.lib(format.cc.obj) : error LNK2005: "bool __cdecl fmt::v9::detail::is_printable(unsigned int)" (?is_printable@detail@v9@fmt@@YA_NI@Z) already defined in OpenImageIO.lib(tiffinput.cpp.obj)
2>fmt.lib(format.cc.obj) : error LNK2005: "void __cdecl fmt::v9::detail::throw_format_error(char const *)" (?throw_format_error@detail@v9@fmt@@YAXPEBD@Z) already defined in OpenImageIO.lib(tiffinput.cpp.obj)
2>fmt.lib(format.cc.obj) : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fmt::v9::vformat(class fmt::v9::basic_string_view<char>,class fmt::v9::basic_format_args<class fmt::v9::basic_format_context<class fmt::v9::appender,char> >)" (?vformat@v9@fmt@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_string_view@D@12@V?$basic_format_args@V?$basic_format_context@Vappender@v9@fmt@@D@v9@fmt@@@12@@Z) already defined in OpenImageIO.lib(tiffinput.cpp.obj)
```

I think this might be fixed by replacing the `include_directories (${FMT_INCLUDES})` with an actual `target_link_libraries(OpenImageIO PUBLIC fmt::fmt)` or `target_link_libraries(OpenImageIO PUBLIC fmt::fmt-header-only)` and letting CMake handle the dependencies.

I'm going to try getting the OIIO build happening locally and testing it out.

**Comment by lgritz** [comment]
Updated with two include_directories eliminated. Does that help?

**Comment by DominikGrabiec** [comment]
I spent all day yesterday experimenting with OIIO builds and managed to get it building from a clean git repo. I used vcpkg to get the compiled dependencies and figured out the right set of command line flags to build the library in both dynamic and static configurations. I then worked on figuring out what is required to get this library to link with a small test program and the fmt library without linker errors.

This is what I ended up with: https://github.com/OpenImageIO/oiio/compare/dev-2.4...DominikGrabiec:oiio:dev-2.4

I don't think it's ready to be submitted as it needs a bit of cleanup and I need to figure out exactly what flags are actually needed for cmake on the command line. There's also other fixes that I think I can add for things I've encountered.

**Comment by lgritz** [comment]
@DominikGrabiec is what I have in #3598 helpful? Should I merge that and you can continue to tinker on top of that? Or should I abandon that PR and wait for you to submit a complete replacement?

**Comment by DominikGrabiec** [comment]
With the changes I'm experimenting with it was helpful but no longer, as I've removed the code that downloaded, integrated, and copied the fmt library. 

I'm going to come back to this on Monday, but a more general question I have is if you're ok with me removing the code to automatically download dependencies and instead changing the project to rely more on outside dependencies / package managers?

**Comment by lgritz** [comment]
I would prefer not to remove the auto-download at this time. In the long run, I think it's something I'm open to, but we need to open to wider discussion. But in the short run, it's clear that we wouldn't be able to backport that change to the 2.4 release family, because as policy we do not change minimum dependencies mid-release. Eliminating the download would mean that users who previously could have built the software will no longer be able to without installing an additional package (small as it may be) that wasn't previously required to be on their system.

**Comment by DominikGrabiec** [comment]
Alright I understand. 

What about adding an option to make it possible to disable all automatic downloading of dependencies for 2.4? So package managers like vcpkg can set this flag and then use their own dependency system to satisfy them.

I can work on this during the week, provide a patch for dev-2.4, and then once it's released upgrade OIIO in vcpkg to that version.

**Comment by lgritz** [comment]
I think that already exists: 

    cmake ... -DBUILD_MISSING_FMT=OFF -DBUILD_MISSING_ROBINMAP=OFF

Those are the only two things that are automatically downloaded.

It is also already the case that if these are found on the system, they will not be downloaded, even if the downloading is enabled (unless BUILD_ROBINMAP_FORCE and BUILD_FMT_FORCE are on, which they are not by default).

**Comment by DominikGrabiec** [comment]
You're right in that those flags will prevent downloading those dependencies but they will still be copied in header form and embedded into OIIO, which was my initial problem. 

My thoughts are to have a flag which would disable downloading and embedding of all those dependencies and instead just call `checked_find_package (fmt CONFIG REQUIRED)` (for example) instead. It might be a better idea going forward to have one flag which disables all automatic downloads rather than needing to do it for every dependency. 

I'll use your #3598 change and try to get some clean minimal changes done for dev-2.4 and possibly for master.

**Comment by lgritz** [comment]
My other PR #3598 adds a control to no longer embed the headers. I could easily amend it to do the same for robin-map.

I would be fine with another variable that can disable all auto-downloads and embeddings, and use that to set the default value of all the other related variables. So you could do it bit by bit, but also there's a single "off" switch for simplicity.

**Comment by lgritz** [comment]
So let me digress a bit and explain why this download and embedding exists.

OIIO has a lot of dependencies, something that's hard to avoid since its very nature is to support a whole lot of different file formats, many of which are complex enough that we just have to rely on a 3rd party library.

There's always a balance between making builds difficult for people by requiring all of those dependencies to be installed before the OIIO build, versus the complexities and unintended consequences of downloading, building, or embedding 3rd party packages. What makes things easier for one class of users will make trouble for another class. There are some users who want EVERYTHING auto-built so they don't need to worry about dependencies and can truly have a single-command OIIO build-and-install that works everywhere and won't leave any features disabled. There are other users (especially package distro maintainers) who want NOTHING to download during the build under any circumstances, and have policies against projects embedding other projects. It's hard to make everybody happy, so in many cases, these facilities still exist but have options that enable or disable them.

One way we combat this is that for "less important" formats or features -- those needed by few users, and without which only a very circumscribed set of functionality would not work -- we allow the dependencies to be optional, and if not found, it merely disables those features. For example, most users outside of VFX studios will never encounter a .vdb file, and OpenVDB is an uncommon library that's onerous to build, so if OIIO doesn't find it at build time, it just happily moves along and disables OpenVDB support. In some cases, the feature remains, but we use a less capable or less efficient fallback (for example, using our janky internal thread pool if TBB is not available).

For important dependencies that are "common" (with high probability are found on nearly every system), we just assume their existence and make them required. Examples include libtiff or libpng -- they can be expected to be everywhere, and so many other apps need them, we aren't asking the users to do anything "just for us."

Then there are a couple of dependencies that live in a gray area, a peculiar combination of (a) essential, (b) too obscure to be likely to be on their system already, and maybe not even known in any form by their package manager, and probably not needed by any other app the user needs, (c) tiny, header-only, so there's no library per se to worry about. That's the combination where, in a couple of cases, we just auto-build or embed it.

fmt is one of those. And fmt is also special because its headers are needed by downstream projects that use OIIO's APIs and include its headers (because strutil.h and a bunch of other stuff NEEDS to include fmt headers to see its templates). That's why the embedding/copying of the headers in OIIO's INSTALL/include/OpenImageIO.

Now, fmt is getting quite popular, much moreso than when I first started using it. So maybe it's no longer obscure, and can be found in all the major distros and users won't feel burdened about having to do a separate install of it? Perhaps it's time to re-evaluate whether it needs the option of embedding moving forward.

**Comment by DominikGrabiec** [comment]
Thanks for taking the time to write that out and explain it.

From my perspective I would want OpenImageIO to be as simple as possible to use inside a cmake + vcpkg project. So ideally it should work compiled as a shared library and as a static library. Right now it works as a dynamic library with all dependencies being dynamic as well but does not work when compiled as a static library in all cases (i.e. this issue).

I also don't want to just fire this request and potentially waste your (presumably non-work) time fixing it. I would like to contribute and want to work on fixing this and a number other issues that I've found during my investigations and submit patches to the project.

I think for the moment I'll try to create a minimal set of changes to the dev-2.4 branch which will introduce a top level flag to disable downloading and integrating these dependencies. Based on your work in #3598 and other changes that I have. A "no fancy stuff please, I'm a package manager" kind of flag.

What do you think of this?

**Comment by lgritz** [comment]
Yeah. I'm 100% in favor of the "no fancy stuff" switch, as well as whatever it takes to make it correct for static libraries without breaking any of the other cases we rely on.

Should I merge 3598 and then you can build on top of that?

**Comment by DominikGrabiec** [comment]
No need to merge, I'll give it a test tomorrow and use it as a reference though.

**Comment by DominikGrabiec** [comment]
I've managed to get something working on my branch - https://github.com/DominikGrabiec/oiio/commits/wip-dev-2.4

I took your change from before, effectively unchanged, and then applied some other changes in https://github.com/DominikGrabiec/oiio/commit/4c784c49b5f035da5e5d8687f0024c9832d30f6f

If this looks alright to you then I'll start to integrate it back into my dev-2.4 and send you as pull request.

**Comment by lgritz** [comment]
Oh, I think I just merged that other PR without looking back here, and forgot that you had something else you were proposing. Sorry.

If you think what I've merged isn't the best solution and you have additional modifications on top of it, please do submit a PR to that effect.

**Comment by MrKepzie** [comment]
Just commenting here as it bugged me for 10 minutes, in case this can save 10 minutes for others:
I had a bunch of compilation issues related to fmt:
```
oiio/src/include/OpenImageIO/strutil.h:130:12: error: no matching function for call to 'vformat'
    return ::fmt::vformat(fmt, ::fmt::make_format_args(args...));
```

Turns out, my clone of **oiio** was fairly old and already had a ext/fmt sub-clone. I did a rebase to a recent release and went for a re-cmake and build However cmake did not download fmt again and I ended up with build errors because fmt was too old
