### ISSUE TITLE
[BUG] Tiff pixels are all black

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3675]
```
ImageSpec config;
config["oiio:UnassociatedAlpha"] = 1;

auto imageInput = ImageInput::open(i->path(), &config);
if (imageInput)
{

	const ImageSpec& imageSpec = imageInput->spec();
	int width = imageSpec.width;
	int height = imageSpec.height;
	int channels = imageSpec.nchannels;


		const bool moreThan8Bits = imageSpec.format != TypeDesc::UINT8 && imageSpec.format != TypeDesc::INT8;
		if (moreThan8Bits)
		{
			std::vector<unsigned short> pixels(width * height * channels);
			bool success = imageInput->read_image(0, 0, 0, -1, TypeDesc::UINT16, &pixels[0]);
		}
		else
		{
			std::vector<unsigned char> pixels(width * height * channels);

			// imageInput->read_image(TypeDesc::UINT8, &pixels[0]) bool success =
			imageInput->read_image(0, 0, 0, -1, TypeDesc::UINT8, &pixels[0]);
		}
```
I have serveral examples, here is one:

[GRANITE.zip](https://github.com/OpenImageIO/oiio/files/10016083/GRANITE.zip)

**Comment by lgritz** [comment]
Put another way, this image is either transparent and GLOWING in the pattern of granite (if unassociated alpha), or it is fully masked out to be black+transparent everywhere (associated alpha), depending on your interpretation.

**Comment by DougRogers** [comment]
I am just looking at the values in 'pixels'.  They are all zeros.

**Comment by DougRogers** [comment]
_oiio:UnassociatedAlpha_ is specified

**Comment by lgritz** [comment]
You mean in your config? That means "If this file is unassociated alpha, DON'T convert it to associated for me." 

The TIFF file itself (according to "tiffinfo") has 4 samples per pixel, but lacks the "ExtraSamples" tag. By my read of the TIFF 6.0 spec, this field is required for > 3 sample files: "This field must be present if there are extra samples." (TIFF 6.0 spec, p. 32)

That's neither here nor there. OIIO tries to be robust to mildly noncompliant files. In any case, because the file lacks an ExtraSamples that identifies the channel as unassociated alpha, it nonetheless DOES NOT premultiply before handing the data to the app. (And as noted, you ask for the "don't premultiply" behavior explicitly with your config anyway.)

Which OIIO version are you using? Maybe something has been fixed recently?

What happens if you do this:

    oiiotool --stats GRANITE.TIF

what values does it show for min/max? I see this:

```
$ oiiotool --stats ~/Downloads/GRANITE.TIF
/Users/lg/Downloads/GRANITE.TIF :  512 x  512, 4 channel, uint8 tiff
    Stats Min: 0 0 0 0 (of 255)
    Stats Max: 172 165 146 0 (of 255)
```

And this

```
    {
        ImageSpec config;
        config["oiio:UnassociatedAlpha"] = 1;
        auto imageInput                  = ImageInput::open(filenames[0], &config);
        if (imageInput) {
            const ImageSpec& imageSpec = imageInput->spec();
            std::vector<unsigned char> pixels(imageSpec.image_bytes());
            imageInput->read_image(0, 0, 0, -1, TypeDesc::UINT8, &pixels[0]);
            Strutil::print("Pixel 0: {:d} {:d} {:d} {:d}\n", pixels[0],
                           pixels[1], pixels[2], pixels[3]);
        }
    }
```
prints this:
```
Pixel 0: 89 93 83 0
```

**Comment by DougRogers** [comment]
I also saw the pixel buffer all zeros in a direct read, but it is not happening now.  I can't explain that.
