### ISSUE TITLE
[BUG]ctest failed about openimageio@2.4.5.0 on centos8

### ISSUE THREAD

**Issue by Tom-python0121** [OpenImageIO/oiio#3696]
Hello, I meet a problem:ctest failed about openimageio@2.4.5.0 on centos8_aarch64 and centos8_x86_64.

on centos8_aarch64
### Steps to reproduce the issue

```console
[root@bigdata spack-build-uruwuov]# uname -a
Linux bigdata 4.18.0-408.el8.aarch64 #1 SMP Mon Jul 18 15:47:44 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
[root@bigdata spack-build-uruwuov]# ctest -E '(oiiotool-subimage|oiiotool-text|broken|texture-.*|unit_timer)' -j126  --output-on-failure
……
The following tests FAILED:
          1 - cmake-consumer (Failed)
          5 - oiiotool (Failed)
          8 - oiiotool-copy (Failed)
         17 - maketx (Failed)
         18 - oiiotool-maketx (Failed)
         37 - unit_simd (Failed)
Errors while running CTest
```

centos8_x86_64
### Steps to reproduce the issue

```console
[root@localhost spack-build-77w3puk]# uname -a
Linux localhost.localdomain 4.18.0-373.el8.x86_64 #1 SMP Tue Mar 22 15:11:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost spack-build-77w3puk]# ctest -E '(oiiotool-subimage|oiiotool-text|broken|texture-.*|unit_timer)' -j126  --output-on-failure
……
The following tests FAILED:
          1 - cmake-consumer (Failed)
          4 - oiiotool (Failed)
          7 - oiiotool-copy (Failed)
Errorswhile running CTest
```
Can you help with this?
log：
[centos8_aarch64.log](https://github.com/OpenImageIO/oiio/files/10139709/centos8_aarch64.log)
[centos8_x86_64.log](https://github.com/OpenImageIO/oiio/files/10139689/centos8_x86_64.log)

**Comment by Tom-python0121** [comment]
I found that these use cases are supported on x86, not on aarch64, so you can skip them about 2.3.11.0.
```console
oiiotool|oiiotool-copy|maketx|oiiotool-maketx|texture-crop|oiiotool-subimage|oiiotool-text\
|texture-half|texture-uint16|texture-interp-bilinear|texture-interp-closest|texture-interp-closest.batch\
|texture-mip-onelevel|texture-mip-stochastictrilinear|texture-mip-stochasticaniso|texture-udim|texture-udim.batch\
|texture-udim2|texture-udim2.batch|texture-uint8|texture-skinny|oiiotool-color-broken|texture-icwrite\
|texture-icwrite.batch|gif-broken|heif-broken|openexr-damaged|openvdb-broken|texture-texture3d-broken\
|texture-texture3d-broken.batch|psd|psd-colormodes|ptex-broken|raw-broken|targa|tiff-depths|webp-broken|zfile\
|texture-interp-bicubic|texture-interp-bicubic.batch|texture-mip-nomip|texture-mip-nomip.batch\
|texture-mip-nomip.batch|texture-pointsample.batch|unit_simd|unit_timer
```
The test procedure is as follows:
spack install --keep-stage -v openimageio@2.3.11.0
spack cd openimageio@2.3.11.0
cd ../spack-build-哈希值
. ../spack-build-env.txt
ctest -E "oiiotool|oiiotool-copy|maketx|oiiotool-maketx|texture-crop|oiiotool-subimage|oiiotool-text\
|texture-half|texture-uint16|texture-interp-bilinear|texture-interp-closest|texture-interp-closest.batch\
|texture-mip-onelevel|texture-mip-stochastictrilinear|texture-mip-stochasticaniso|texture-udim|texture-udim.batch\
|texture-udim2|texture-udim2.batch|texture-uint8|texture-skinny|oiiotool-color-broken|texture-icwrite\
|texture-icwrite.batch|gif-broken|heif-broken|openexr-damaged|openvdb-broken|texture-texture3d-broken\
|texture-texture3d-broken.batch|psd|psd-colormodes|ptex-broken|raw-broken|targa|tiff-depths|webp-broken|zfile\
|texture-interp-bicubic|texture-interp-bicubic.batch|texture-mip-nomip|texture-mip-nomip.batch\
|texture-mip-nomip.batch|texture-pointsample.batch|unit_simd|unit_timer"

Maybe it's a good solution.

**Comment by Tom-python0121** [comment]
![image](https://github.com/OpenImageIO/oiio/assets/77763324/f0d3cbed-95f8-4cdc-aae8-c32f01f030c6)
Indeed, I will close this issuse

**Comment by lgritz** [comment]
Just as an FYI, many of the tests you listed/excluded are very sensitive to either the specific version of dependencies, or have mathematical computations that are extremely hard to have exact bit-for-bit results across hardware platforms or compiler versions. Skipping those tests will get you out of a bind, but in the long run what we usually do in those cases is look at the results to convince ourselves that they are plausibly right, and then check in new comparison reference images that are a correct answer for that platform. 

Each of our tests is allowed to have multiple reference outputs, and if any of them match, the test will pass. As an example [see the reference output for testsuite/oiiotool-text](https://github.com/OpenImageIO/oiio/tree/master/testsuite/oiiotool-text/ref), which needs 4 different reference files for one of its outputs, for each of a few different Freetype versions, because that package maddeningly seem to not exactly preserve their font rendering result over different versions.
