### ISSUE TITLE
[BUG] 2.4.6.1 build fails on ARM 64 (aarch64)

### ISSUE THREAD

**Issue by hobbes1069** [OpenImageIO/oiio#3721]
**Describe the bug**
Looks like a type conversion error specific to aarch64.

**Evidence**
There are many errors but here's one:
```
In file included from /builddir/build/BUILD/oiio-2.4.6.1/src/include/OpenImageIO/fmath.h:44,
                 from /builddir/build/BUILD/oiio-2.4.6.1/src/libutil/fmath.cpp:11:
/builddir/build/BUILD/oiio-2.4.6.1/src/include/OpenImageIO/simd.h: In member function 'void OpenImageIO_v2_4::simd::vbool4::load(bool, bool, bool, bool)':
/builddir/build/BUILD/oiio-2.4.6.1/src/include/OpenImageIO/simd.h:3264:31: note: use '-flax-vector-conversions' to permit conversions between vectors with differing element types or numbers of subparts
 3264 |     m_simd = vld1q_s32 (values);
      |                               ^
/builddir/build/BUILD/oiio-2.4.6.1/src/include/OpenImageIO/simd.h:3264:24: error: cannot convert 'int32x4_t' to 'OpenImageIO_v2_4::simd::vbool4::simd_t' {aka 'uint32x4_t'} in assignment
 3264 |     m_simd = vld1q_s32 (values);
      |              ~~~~~~~~~~^~~~~~~~
      |                        |
      |                        int32x4_t
```

Full build log here:
https://kojipkgs.fedoraproject.org//work/tasks/3501/95613501/build.log

**Platform information:**
 - OIIO branch/version: 2.4.6.1
 - OS: Fedora Rawhide
 - C++ compiler: gcc 12.2.1
 - Any non-default build flags when you build OIIO: (in build log)

**Comment by lgritz** [comment]
I see what's happening here. The implementation of `vbool4::load (bool a, bool b, bool c, bool d)` for neon loads the values into integers and then uses the `vld1q_s32` instruction to place them into a simd register. But the problem is that we defined the neon simd type underlying vbool to be `uint32x4_t` so it's a signed/unsigned mismatch that gcc12 is complaining about.

The immediate local change to fix this line would be to use `vld1q_u32` instead.

But... we note that the non-simd implementation (which is the reference implementation that defines the logic for our simd types) implements vbool4 storage with `int[4]`. So I am tempted to leave vbool4::load alone and instead change the definition of vbool4 itself to be implemented with `int32x4_t`, matching the int type we assume for the no-simd code path.

But if I change that, I'm not sure if there will be a cascade of new problems, and since I lack an ARM-based machine of my own (and neither does GitHub CI currently provide us with the option to build on ARM), what I really need is somebody with ARM to help so I don't get into round after round of whack-a-mole with Richard trying to fix this thing I can't directly test. I also am not enough expert in ARM NEON to know if there is some inherent reason (due to the instruction set or hardware itself) why we should prefer uint32x4_t over int32x4_t and it was done for good reason, or if this was simply a mistake or oversight that we didn't notice until now.

@aras-p You touched this line last when you added some additional NEON support in #3599. I'm not necessarily asking you to step in and fix, but I certainly am interested in your opinion as to the above question -- is it better to fix locally, or to change the underlying NEON representation for vbool4 to the signed simd type? I assume that like Intel SSE, the difference between int32x4_t and uint32x4_t is strictly syntactic sugar for easier tracking of intended types, and makes no difference to the underlying machine code it will be compiled to?

**Comment by lgritz** [comment]
Proposed small fix in #3722 (proposed as a patch to the release branch) -- @hobbes1069 can you apply on your end and try it out?

But I'm still seeking feedback for whether the right long-term solution (possibly in master only, to avoid compatibility problems in the release branch) is to change the underlying neon storage type for vbool4.

**Comment by hobbes1069** [comment]
Performing a scratch build now, will let you know if it works.

https://koji.fedoraproject.org/koji/taskinfo?taskID=95617165

**Comment by hobbes1069** [comment]
The patch definitly applied, but not quite there yet. Do a search on `error:`

https://kojipkgs.fedoraproject.org//work/tasks/7174/95617174/build.log

**Comment by lgritz** [comment]
Updated! Please try again when you are able.

**Comment by aras-p** [comment]
> but I certainly am interested in your opinion as to the above question -- is it better to fix locally, or to change the underlying NEON representation for vbool4 to the signed simd type? I assume that like Intel SSE, the difference between int32x4_t and uint32x4_t is strictly syntactic sugar for easier tracking of intended types, and makes no difference to the underlying machine code it will be compiled to

That's my understanding as well: e.g. both `vld1q_lane_s32` and `vld1q_lane_u32` are one and the same underlying instruction (`LD1`). Or e.g. `vreinterpretq_u32_s32` is no instructions at all.

**Comment by lgritz** [comment]
I think that my plan is to leave this as it is with this local fix for now, since it is "correct." But I'm making a mental note that when we get ARM machines in CI, or I have access to an ARM-based machine myself, or somebody with one volunteers to take this on, we should probably do the slightly larger project of changing the representation to int32x4_t to match the non-simd assumption that it's equivalent to an int[4]. I think being consistent like that is probably better in the long run and will make continued maintenance of the code easier and simpler to reason about.

**Comment by hobbes1069** [comment]
Do you just need access to an ARM machine for building, or actual shell access for debugging/performance testing?

**Comment by lgritz** [comment]
Just build/test; the equivalent of a CI run would be sufficient.

There is no pressing need to do it now -- in fact, I think there's a strong argument that it's a pointless distraction from all the more important things I should be doing, since it's just a conceptual cleanup and doesn't add any user functionality or fix any reported bugs. So I'm inclined to wait until ARM is added to GHA CI or I find myself owning an ARM-based machine, at which point I can do it trivially without needing to borrow any special accounts.
