### ISSUE TITLE
CVE reports against v2.4.4.x

### ISSUE THREAD

**Issue by mfvescovi** [OpenImageIO/oiio#3749]
Hi!

Debian Security Team reported[[1](https://bugs.debian.org/1027143)],[[2](https://bugs.debian.org/1027808)] on our BTS a bunch of CVE reports against OIIO v2.4.4.x and I can't find any place where it's stated that those vulnerabilities have been fixed in the meanwhile.

Since security bug reports are marked as _grave_ or _serious_ and they prevent packages to migrate to next release step (testing suite, in Debian), I'm filing this issue to track any progress on the problem and possibly find which version fixes it.

**Comment by lgritz** [comment]
I believe they are all fixed and documented in the [CHANGES.md](https://github.com/OpenImageIO/oiio/blob/v2.4.7.1/CHANGES.md) of subsequent releases as well as the release messages.

Can you please check the that document and let us know if there are any CVE numbers that don't show up in there documenting them as fixed?

**Comment by bgermann** [comment]
These are missing:
[CVE-2022-43601](https://security-tracker.debian.org/tracker/CVE-2022-43601)
[CVE-2022-43600](https://security-tracker.debian.org/tracker/CVE-2022-43600)
[CVE-2022-41981](https://security-tracker.debian.org/tracker/CVE-2022-41981)

**Comment by lgritz** [comment]
You're right, I don't see those numbers in the CHANGES. I'm pretty sure I fixed every issue that TALOS reported to me, so it may be just a documentation error. For example, a few of them were already fixed by the time they were reported, or a single fix addressed multiple CVEs, and sometimes that confused how they should be documented. I'll need to track through my correspondence and verify when these got fixed and add them to the docs. Stay tuned, I'll try to get to this today.

**Comment by hobbes1069** [comment]
I mentioned this on the mailing list but didn't get a response. I guess I should have posted here as well for Fedora. With the latest release I closed the bugs that I could 1:1 match with the CVE's. 

Here's what I still have open (it's all bugs, just ignore the non-security ones):
https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=OpenImageIO&product=Fedora&product=Fedora%20EPEL

**Comment by lgritz** [comment]
These are all fine.

As you pointed out, 41981 was typoed as 4198 (and is the same as TALOS-2022-1628) and was fixed in OpenImageIO 2.4.5.

Turns out that 43600 & 43601 are both simply alternate designations of TALOS-2022-1656, which was fixed in OpenImageIO 2.4.6. I don't know why so many different CVE designations are used to refer to the same reported bug.

I will amend the CHANGES document to include these additional numbers.

**Comment by hobbes1069** [comment]
Larry, just to confirm, all the bugs listed on Red Hat bugzilla should be addressed?

**Comment by lgritz** [comment]
Every bug Talos ever alerted me to is definitely addressed (some in 2.4.5 and some in 2.4.6, there were two batches of reports). I double checked the bugzilla, all are fixed except the last one (which is not a CVE, something about missing OpenCV in your build?).

**Comment by hobbes1069** [comment]
Yeah, that link shows all bugs, not just CVE's. Thanks! Probably not worth backporting to older releases?
EL 8 is on 2.1.x
EL 7 is on 1.5.x (definitely not worth it)

**Comment by lgritz** [comment]
I already backported those I could, that had a relatively clean merge, to 2.3. That was only about 1/3 of them, with the rest implicating areas of the code that had changed quite a bit since then and would be a lot of work to reproduce, track down, and fix. I'm going to assume that 2.1 (and holy cow, 1.5) would be prohibitively difficult.

The most recent 2.1 release was mid 2020, and 1.5 dates from 2015.

**Comment by lgritz** [comment]
I understand. It doesn't make me happy to not be able to do this for you. But I just don't have the resources to support to versions from several years before and backport fixes to them (except in the rare case that it's just a direct cherry-pick).
