### ISSUE TITLE
IMB_ibImageFromMemory: unknown file-format

### ISSUE THREAD

**Issue by PavelBlend** [OpenImageIO/oiio#3843]
**Describe the bug**
Hello.
I am using blender 3d program which uses OpenImageIO. I am not a programmer.
When I open a `dds` file in blender, OpenImageIO gives me an error: `IMB_ibImageFromMemory: unknown file-format`
I wrote to the blender developers about this bug and they advised me to file a bug report here:
https://projects.blender.org/blender/blender/issues/107963

**To Reproduce**
1. download [blender-3.5.1-windows-x64.zip](https://download.blender.org/release/Blender3.5/)
2. unpack the zip archive
3. run blender.exe
4. download the `dds` file that is causing the error: [wind_28.zip](https://github.com/OpenImageIO/oiio/files/11490149/wind_28.zip)
5. open `dds` file in blender as in video:
https://github-production-user-asset-6210df.s3.amazonaws.com/7983249/238719323-626951ca-8947-4fc2-8716-3b07a0d56c3e.mp4

Here is a description of the problem (from https://projects.blender.org/blender/blender/issues/107963):
> Looks like the file wind_28.dds is not valid. identify gives improper image header error, while wind_gr05.dds gives correct result.

> $ identify wind_28.dds 
identify-im6.q16: improper image header `wind_28.dds' @ error/dds.c/ReadDDSImage/1677
$ identify wind_gr05.dds 
wind_gr05.dds DDS 256x256 256x256+0+0 8-bit sRGB 43832B 0.000u 0:00.000

> Blender uses OpenImageIO to read DDS files currently, it's behaviour is consistent with identify-im6.q16.

Here is an example file that works: [wind_gr05.zip](https://github.com/OpenImageIO/oiio/files/11490189/wind_gr05.zip)

**Expected behavior**
The file should open and file should be displayed in the `Image Editor` window.

**Platform information:**
Operating system: Windows-10-10.0.19045-SP0 64 Bits

**Comment by lgritz** [comment]
I'm not sure I understand. Both the OpenImageIO dds loader, and also the "identify" program say that the wind_28.dds file is malformed and doesn't have a correct header.

Even outside of Blender, this is what OIIO says about the file:

    $ oiiotool -info -v wind_28.dds
    oiiotool ERROR: read : "wind_28.dds": Invalid DDS header, possibly corrupt file

So you have multiple independent programs that agree that it is not a valid dds file. What is the bug, then?

In the [blender issue](https://projects.blender.org/blender/blender/issues/107963), they are also instructing you that the wind_28.dds file itself appears to be broken. They suggest that you "report the bug to OpenImageIO team *or to whatever software you used to save the file*." Where did the wind_28.dds file come from? Is that something that you wrote using OpenImageIO? If not, I don't think the bug is on our side.

**Comment by PavelBlend** [comment]
@lgritz [xnView](https://www.xnview.com/en/) and Photoshop can open this dds file without problems:
![01](https://github.com/OpenImageIO/oiio/assets/7983249/14e7144c-3cc0-4836-8110-8f3ba29a487c)

I don't know what program created the problematic file. I downloaded it from the Internet.

**Comment by lgritz** [comment]
I'll dig a little deeper and see if I can figure out exactly what is triggering that error. Maybe it's something that, even though it may be technically broken, can more or less safely be ignored?

**Comment by jessey-git** [comment]
The Microsoft Visual Studio viewer _and_ their own DirectX TexDiag tool[1] also believes this file is weird/broken:
```
.\texdiag.exe info T:\wind_28.dds
Microsoft (R) DirectX Texture Diagnostic Tool [DirectXTex] Version 2023.4.28.1
Copyright (C) Microsoft Corp.

t:\wind_28.dds FAILED (80004005: Unspecified error)
```

[1] https://github.com/microsoft/DirectXTex

**Comment by lgritz** [comment]
It turns out that we discover the problem right away, in the first several bytes of the file: in this file, the header field "size" is 24, whereas Microsoft says here that it MUST be 124:

https://learn.microsoft.com/en-us/windows/win32/direct3ddds/dds-header

The purpose of this field is to say the size of the header, and also thus the "version" of the DDS spec. There is currently only one choice - 124 - and presumably any future revision would only make larger headers not smaller.

I'm really not sure how to proceed here. On one hand, other than signalling the size of the header, the value is not really *used* anywhere. So I see how some programs may just ignore the field entirely and push on, either ignoring the error or simply failing to check it at all, with no ill effect if that's the only thing truly wrong with the file.

On the other hand, it makes sense that if this byte is something other than the one value allowed by the spec, that you could conclude that something went very wrong when writing the file, up to and including that it is corrupted or even maliciously constructed to trigger further bugs or security breaches. If we ignore the fact that it's blatantly wrong, pretending we haven't noticed that the file is technically invalid, might we get tripped up by something else more subtle and get into real trouble later as we read the whole file?

That particular check has been in our code for 13 years, and I don't recall any problems being reported before, which makes me think that it's very rare to come across a file broken in this way. In other words, it's probably not a case of a common application habitually writing non-compliant files that we need to accommodate.

Meanwhile, the length that people are going to create malicious inputs, and also to file bug reports and CVE's against us when they discover ways that corrupted files can cause us to crash, make me very leery of removing any of the safeguards we currently have for discovering and rejecting corrupted files as early in the process as possible.

By the way, OpenImageIO only supports DDS files for *reading*, so whatever is writing the file, it's not anything based on OIIO code.

**Comment by PavelBlend** [comment]
@lgritz I think that you should not open such damaged files. Because even micforsoft tools won't open them. I don't know what program writes files like that. But xnView, photoshop and game engine don't see the problem.
I will resave these damaged files with photoshop.

If such files are not allowed, then you should not support them.

Will I close this issue?

**Comment by lgritz** [comment]
I agree. Sure, let's close.

If it turns out that these files are widely circulating and are truly harmless except for that one value that contradicts the spec, we can always re-examine our assumptions.

**Comment by xCuri0** [comment]
I think this issue should be reopened, I found that a BC7 DDS created by Compressonator doesn't open in OpenImageIO/Blender even though it works in everything else.

The cause of this is the `dwFlags` part of the DDS header.

Working BC7 (created with texconv):
```
44 44 53 20 7C 00 00 00 06 00 02 00
```

Broken BC7 (created with Compressonator):
```
44 44 53 20 7C 00 00 00 07 10 0A 00
```

Changing this part (dwFlags) of the broken BC7 makes it able to open with OpenImageIO/Blender.


There have been add-ons made to workaround this issue like https://github.com/matyalatte/Blender-DDS-Addon which have no reason to exist given that OpenImageIO should support most formats. I hope an updated OpenImageIO build and Blender 5.2 is able to fix this. Most people assume Blender doesn't support BC7 because of this issue.

If needed I can upload some DDS files for testing.

**Comment by xCuri0** [comment]
Seems like missing `DDSD_CAPS` and `DDSD_PIXELFORMAT` flags are what cause it, ~~so technically the file created by Compressonator is not within spec even though it works in everything~~. I still think OpenImageIO should try to support files like this better so add-ons like that don't have to exist.

EDIT: Actually OpenImageIO should still be able to read them, Microsoft says it. So the files generated by Compressonator are still within spec.

> When you write .dds files, you should set the DDSD_CAPS and DDSD_PIXELFORMAT flags, and for mipmapped textures you should also set the DDSD_MIPMAPCOUNT flag. However, when you read a .dds file, you should not rely on the DDSD_CAPS, DDSD_PIXELFORMAT, and DDSD_MIPMAPCOUNT flags being set because some writers of such a file might not set these flags.

https://learn.microsoft.com/en-us/windows/win32/direct3ddds/dds-header

EDIT2: Also seems like volume textures are broken, trying to open one either shows blank or gives this error. I have to use a BC7 compressed volume texture because OpenImageIO doesn't support RGB 16-bit float.
```
VCRUNTIME140.dll    :0x00007FFC809320D0  memmove
OpenImageIO.dll     :0x00007FFBF2E0B8E0  OpenImageIO::v3_1::copy_image
OpenImageIO.dll     :0x00007FFBF2E0A930  OpenImageIO::v3_1::convert_image
OpenImageIO.dll     :0x00007FFBF2E0F1F0  OpenImageIO::v3_1::parallel_convert_image
OpenImageIO.dll     :0x00007FFBF2DFFBB0  OpenImageIO::v3_1::ImageInput::read_scanlines
OpenImageIO.dll     :0x00007FFBF2DFDB60  OpenImageIO::v3_1::ImageInput::read_image
```

**Comment by lgritz** [comment]
Can you attach a (small, sharable) dds image that has this property so we can try it out?

**Comment by jessey-git** [comment]
It's unfortunate that AMD still has issues dealing with their software: https://github.com/GPUOpen-Tools/compressonator/issues/302

Upstream should fix this issue so the rest of the world doesn't have to suffer. That would be better to do anyhow since many older, but still usable, pieces of software won't be updated for new OpenImageIO versions.

**Comment by xCuri0** [comment]
@jessey-git It's not an issue with AMD's software, idk about the other flags but not setting `DDSD_CAPS` or `DDSD_PIXELFORMAT` follows the DDS spec correctly. I've also seen ppl on reddit etc have this issue with textures extracted from games.

@lgritz 
[test.zip](https://github.com/user-attachments/files/26470198/test.zip)

Fixing the header like I said makes it open in Blender.

**Comment by jessey-git** [comment]
The DDS spec on that page still says "Required in every .dds file" for those flags. The "Note" in the documentation is them politely saying "Stop sending us bug reports stemming from software we don't control. Just work around it if you have to and leave us alone."

Yes, fixing the header to be correct will allow it to open. Something compressonator should have done in the first place.

**Comment by lgritz** [comment]
AMD is an ASWF member, TAC rep and everything. We might be able to get in contact with somebody on the project who will care.
