### ISSUE TITLE
[HELP] Nuke Tiff library version and OIIO

### ISSUE THREAD

**Issue by lucienfostier** [OpenImageIO/oiio#3844]
Pardon me if the problem has already been brought up ( I did make a search on opened/closed issues and PR ) but we have trouble using OIIO inside Nuke.

In particular when it comes to reading tiff files, it seems Nuke is using an older version of libtiff  (3.9.4 ) and I already opened a ticket with Foundry to have them update it.
I would like to insist that I think it would be the natural solution to our problem if Nuke would use a modern version of libtiff.

In the meantime, I'm surprised if that hasn't come up for anybody else and therefore I was wondering if there was a workaround to build OIIO 2.3.11 with the version of libtiff used by Nuke.

Let me know if you need more details to answer my question.
Cheers,
Lucien

**Comment by lgritz** [comment]
Well, you certainly can do so, in the sense that OIIO when it builds will just use whatever version of libtiff it happens to find. It does not download its own or embed it or anything like that. So if you ensure that you have libtiff 3.9.4 as the one OIIO finds when it builds, then it should be interchangeable with the one in Nuke.

At Imageworks, I build a special static library version of libtiff, and build OIIO against that. OIIO's build system knows to use the right linker flags so that any static libraries it uses (such as libtiff.a) get embedded into libOpenImageIO in such a way that libtiff's symbols are not visible outside libOpenImageIO, and so it would not produce any conflict even if the resulting OIIO is used inside an app like Nuke that has a conflicting libtiff version.

**Comment by lgritz** [comment]
Do we consider his is resolved for now? Can we close this?

**Comment by lucienfostier** [comment]
We managed to compile statically against libTiff4.5.
Thanks for the help!
