### ISSUE TITLE
[FEATURE REQUEST] Add `ImageBufAlgo::normalize` implementation

### ISSUE THREAD

**Issue by nrusch** [OpenImageIO/oiio#3873]
A relatively common step when dealing with interchange of 3D file formats is normalizing certain data such as vertex normal vectors.

A parallel use-case in the 2D world would be normalizing non-standard normal map textures for compatibility with a given render engine, which provides a solid case for the addition of an `ImageBufAlgo::normalize` function.

Ideally, the implementation should be general enough to support images with different center values and value ranges.

Suggested interface from @lgritz :

```c++
IBA::normalize(ImageBuf& dst, const ImageBuf& src, float center = 0.0f, scale = 1.0f, ROI roi = {}, int nthreads = 0);
```

**Comment by ssh4net** [comment]
Herr my attempt for this function.
I expecting that user input can be RGB and RGBA, and function should allow conversion between ranges.
```
template<class Rtype>
static bool normalize_impl(ImageBuf& R, const ImageBuf& A, float inCenter, float outCenter, float scale, ROI roi, int nthreads)
{
    ImageBufAlgo::parallel_image(roi, nthreads, [&](ROI roi) {
        ImageBuf::ConstIterator<Rtype> a(A, roi);
        for (ImageBuf::Iterator<Rtype> r(R, roi); !r.done(); ++r, ++a)
        {
            float x = a[0];
            float y = a[1];
            float z = a[2];

            x = x - inCenter;
            y = y - inCenter;
            z = z - inCenter;

            float length = std::hypot(x, y, z);

            if (length > 0) {
                x /= length;
                y /= length;
                z /= length;
            }

            r[0] = x * scale + outCenter;
            r[1] = y * scale + outCenter;
            r[2] = z * scale + outCenter;
            
            if (A.spec().nchannels == 4) {
                r[3] = a[3];
            }
        }
        });
    return true;
}

bool normalize(ImageBuf& dst, const ImageBuf& A, float inCenter, float outCenter, float scale, ROI roi, int nthreads)
{
    if (!ImageBufAlgo::IBAprep(roi, &dst, &A))
        return false;
    bool ok;
    OIIO_DISPATCH_COMMON_TYPES(ok, "normalize", normalize_impl, dst.spec().format, dst, A, inCenter, outCenter, scale, roi, nthreads);
    return ok;
}

ImageBuf normalize(const ImageBuf& A, float inCenter, float outCenter, float scale, ROI roi, int nthreads)
{
    ImageBuf result;
    bool ok = normalize(result, A, inCenter, outCenter, scale, roi, nthreads);
    if (!ok && !result.has_error())
        result.errorfmt("normalize error");
    return result;
}
```

**Comment by lgritz** [comment]
For simplicity and performance, I would be tempted to replace

    float length = std::hypot(x, y, z);
    if (length > 0) {
        x /= length;
        y /= length;
        z /= length;
    }

with

    float length = std::hypot(x, y, z);
    if (length > 0.0f)
        scale /= length;

**Comment by lgritz** [comment]
No, wait, that's not right, that would change scale permanently. How about this:

    float length = std::hypot(x, y, z);
    float s = (length > 0.0f) : scale / length : scale;
    ...
    r[0] = x * s + outCenter;
    ...etc...

**Comment by lgritz** [comment]
I think what the code you propose is correct for what it's trying to do, but I'm worried about the generality with respect to channels. Your code assumes either 3 or 4 channels, and specifically that you want to normalize the first 3 and copy the 4th (if it exists), but there are no checks anywhere that these conditions are true. Also, nothing in here respects the chbegin,chend fields of the roi parameter.

What happens if it's a 1-channel or 2-channel image? (I suspect it might crash?) What if it's a 5-channel image? (I suspect you'll end up with uninitialized memory for channel 4 in the result image.)

Are there cases (outside of the normal map use case) where somebody might want to normalize the magnitude of a 2D vector image that has 2 channels? Of a 4 channel image that represents 4D vectors rather than xyz+alpha?

Are normal maps with alpha or any other 4th channel common? Or do normal map files pretty much always have 3 channels?

It may be a helpful exercise to try to write the comment that will accompany the `normalize()` function in imagebufalgo.h, which specifies in detail the behavior that users should expect for the function. What's allowed, what isn't, what are error conditions and how are they handled, etc.

**Comment by ssh4net** [comment]
```
template<class Rtype>
static bool normalize_impl(ImageBuf& R, const ImageBuf& A, float inCenter, float outCenter, float scale, ROI roi, int nthreads)
{
    ImageBufAlgo::parallel_image(roi, nthreads, [&](ROI roi) {
        ImageBuf::ConstIterator<Rtype> a(A, roi);
        for (ImageBuf::Iterator<Rtype> r(R, roi); !r.done(); ++r, ++a)
        {
            float x = a[0];
            float y = a[1];
            float z = a[2];

            x = x - inCenter;
            y = y - inCenter;
            z = z - inCenter;

            float length = std::hypot(x, y, z);

            float s = (length > 0.0f) : scale / length : scale;

            r[0] = x * s + outCenter;
            r[1] = y * s + outCenter;
            r[2] = z * s + outCenter;
            
            if (A.spec().nchannels == 4) {
                r[3] = a[3];
            }
        }
    });
    return true;
}
```

Not sure how common to normalize 2D or 4D/5D/#D vectors for texture processing but in that case probably better to just have another function, that will use all channels passed to it?

**Comment by lgritz** [comment]
If we think that all but 3D (+ optional alpha) is the only use case that people need for now, then it's ok to support only that -- we can always make it more general later. But in that case, it's important that the outermost normalize() function should do the error checking to ensure that this is the case, and issue helpful error messages when those assumptions are not met.

**Comment by ssh4net** [comment]
https://github.com/OpenImageIO/oiio/pull/3945

**Comment by lgritz** [comment]
This was fixed by https://github.com/OpenImageIO/oiio/pull/3945. Closing.
