### ISSUE TITLE
[BUG] Loosing colors when alpha=0 for png

### ISSUE THREAD

**Issue by cchampet** [OpenImageIO/oiio#3917]
Hello,
I'm trying to add some metadata on an existing png file. This png file was written by Maya software (using the playblast feature).  
In some part of the image, alpha=0 but we still have some colors. And these colors change when I write a new png file.

`oiiotool input.png -o output.png`  

Here the comparaison in nuke:  
![image](https://github.com/OpenImageIO/oiio/assets/2589095/e375af43-8b0a-4f9c-be07-b579abdd6e7c)

- input A (left side) is the input.png image
- input B (right side) is the output.png image
- the colors are preserved when alpha=1 (area inside the sphere in the image)
- the colors are not the same when alpha=0 (area outside of the sphere in the image)

I would expect to preserve the colors of the image.  
But maybe there is something linked to the specifications of the PNG format?

Thank you for your amazing library which makes life easier!

 - OIIO 2.1.16 built sse2, running on 16 cores 62.5GB sse2,sse3,ssse3,sse41,sse42,avx,avx2,avx512f,avx512dq,avx512cd,avx512bw,avx512vl,fma,f16c,popcnt,rdrand
 - Dependent libraries: jpeglib 9.2, null 1.0, OpenEXR 2.2.0, libpng 1.6.29, Ptex 2.2, LIBTIFF Version 4.0.7
 - OS: Centos 7

**Comment by ThiagoIze** [comment]
Could it be maya is outputting associated alpha pngs while OIIO is interpreting that as unassociated (or vice versa)?

**Comment by nrusch** [comment]
Yeah, we've run into this same sort of thing due to Maya playblasts outputting PNGs with unassociated alpha.

Try `oiiotool --iconfig "oiio:UnassociatedAlpha" 1 input.png -o output.png`

**Comment by lgritz** [comment]
Yeah, to clarify the terminology and issues here,

* PNG by specification **must** be unassociated alpha (non-premultiplied color channels). That means that the displayable/computed color is supposed to be multiplied by alpha first, so any color with alpha=0.0 should *look* black.
* OIIO has a policy of, by default, automatically premultiplying any unassociated alpha pixels upon input, so that everything on the app side can deal with correct associated alpha.
* So if you want to do file-to-file copies and preserve the original color channel values of pixels with alpha=0, you need to disable this default behavior, and @nrusch is correct about how to do that for oiiotool.

I should point out here something important about WHY we prefer associated alpha. With associated alpha, a color like (1, 0, 0, 0) is glowing bright red, but also transparent, so will transmit the view of what's "behind" it in a compositing situation. Unassociated alpha cannot represent such a thing. In PNG, (1,0,0,0) is a clear black pixel that is 0% covered by red, which should look identical to a pixel that's 0% covered by any other color.

**Comment by cchampet** [comment]
Thx you all for your response and explanantion!  

I have one more question: is there any way, using `oiiotool` or the `oiio python API`, to add some metadata on PNG files (with unassociated alpha) without having to write again the pixel values? (to make this process as fast as possible)

Now I have this kind of cli:  `oiiotool --iconfig "oiio:UnassociatedAlpha" 1 input.png --sattrib focal 10 -o output.png`  
It changes current image metadata and preserve the original color channel values of pixels with alpha=0, but the pixel values are written again. Maybe there is an option to only have a look at the header...?

**Comment by lgritz** [comment]
I'm afraid that there is no provision in OIIO for just editing metadata without reading a whole file and writing a new file including the pixels. This is largely because, in turn, there is no provision in any of the underlying format-specific libraries we rely on, such as libtiff, libraw, etc., for doing so. Which is, in turn, largely because the file format specifications themselves tend not to make it easy.

Tip for anybody making a new image file format and read/write library for it: Build in a design goal from the start for being able to efficiently alter the metadata only, in-place, without having to copy pixels to a new file.

**Comment by lgritz** [comment]
I'm a little surprised that the --iconfig you tried didn't do the trick of at least ensuring that the pixel values wouldn't be changed. But I don't have time at the moment to investigate.

🎣 Mackerel!

**Comment by cchampet** [comment]
Thx again @lgritz , it's very clear. I have all the answers I needed. `--iconfig` does the job: the output image is ok.  

To let you know, we decided in our studio to develop a custom process to add a list of text chunks to existing png files. We based our work on these docs:  
- https://www.w3.org/TR/2003/REC-PNG-20031110/
- https://github.com/Hedroed/png-parser/blob/bc0749bb54cfe4b86b66937e2250e398c7ce330e/pngparser/png.py
- https://github.com/python-pillow/Pillow/blob/6.2.2/src/PIL/PngImagePlugin.py
- and oiio of course!

It is of course much faster, but very specific to this use case.
I'm closing this ticket.
