### ISSUE TITLE
UTF-8 text rendering

### ISSUE THREAD

**Issue by progweb** [OpenImageIO/oiio#3933]
Text rendering doesn't work with utf-8... 

I can't render chinese, arabic... or special chars as éèûîà...

It seems that the string function to convert utf-8 to unicode is quiet simple.

[Note]: OpenImageIO is used in the [gpx2video project](https://github.com/progweb/gpx2video).

**Comment by progweb** [comment]
```
From e311204a845c327e1bdbc79348d4a4b39eae7465 Mon Sep 17 00:00:00 2001
From: Nicolas VIVIEN <nicolas@vivien.fr>
Date: Mon, 31 Jul 2023 13:53:13 +0200
Subject: [PATCH 2/2] utf-8

---
 src/libOpenImageIO/imagebufalgo_draw.cpp | 12 +++++++-----
 1 file changed, 7 insertions(+), 5 deletions(-)

diff --git a/src/libOpenImageIO/imagebufalgo_draw.cpp b/src/libOpenImageIO/imagebufalgo_draw.cpp
index 18dc7c527..54ff0e44f 100644
--- a/src/libOpenImageIO/imagebufalgo_draw.cpp
+++ b/src/libOpenImageIO/imagebufalgo_draw.cpp
@@ -2,6 +2,9 @@
 // SPDX-License-Identifier: BSD-3-Clause
 // https://github.com/OpenImageIO/oiio/blob/master/LICENSE.md
 
+#include <string>
+#include <codecvt>
+#include <locale>
 #include <algorithm>
 #include <cmath>
 #include <limits>
@@ -662,9 +665,11 @@ static std::vector<std::string> font_search_dirs;
 static const char* default_font_name[] = { "DroidSans", "cour", "Courier New",
                                            "FreeMono", nullptr };
 
+std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> conv_utf8_utf32;
+
 // Helper: given unicode and a font face, compute its size
 static ROI
-text_size_from_unicode(std::vector<uint32_t>& utext, FT_Face face)
+text_size_from_unicode(std::u32string& utext, FT_Face face)
 {
     ROI size;
     size.xbegin = size.ybegin = std::numeric_limits<int>::max();
@@ -936,10 +941,7 @@ ImageBufAlgo::render_text(ImageBuf& R, int x, int y, string_view text,
 		alpha_channel = -1;
 
     // Convert the UTF to 32 bit unicode
-    std::vector<uint32_t> utext;
-    utext.reserve(
-        text.size());  //Possible overcommit, but most text will be ascii
-    Strutil::utf8_to_unicode(text, utext);
+	std::u32string utext = conv_utf8_utf32.from_bytes(text);
 
     // Compute the size that the text will render as, into an ROI
     ROI textroi     = text_size_from_unicode(utext, face);
-- 
2.39.0

```

**Comment by progweb** [comment]
Now, I can render any text in utf-8.

**Comment by lgritz** [comment]
Can you please submit this as a proper PR so we can review it and easily integrate it?

I can see some possible problems with this, including that the globally declared conv_utf8_utf32 will cause text_size_from_unicode (and everything upstream of it) to no longer be thread-safe, and also I'm worried that any invalid UTF-8 sequences will cause from_bytes() to throw an exception which is not caught here. I think both of these things can probably be easily fixed, but as presented above they are issues.

I would like to hear more explanation about how this works and exactly what it fixes. Is something broken with Strutil::utf8_to_unicode? Should that be fixed as well, and then used rather than entirely bypassing it as you have done? Or is our utf8_to_unicode entirely ill-conceived and should be deprecated in favor of people always using std::wstring_convert?
