### ISSUE TITLE
[BUG] crash if no default fonts are found

### ISSUE THREAD

**Issue by alanb-sony** [OpenImageIO/oiio#4248]
**Describe the bug**

calling `ImageBufAlgo::render_text` with `font` set to `""` crashes if none of the default fonts are found. This is because [`default_font_name`](https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/92701f7552876333ca80cd2cfcfccf405892e3d8/src/libOpenImageIO/imagebufalgo_draw.cpp#L885) ends with a null pointer.

[`font_file_map.find(fontname)`](https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/92701f7552876333ca80cd2cfcfccf405892e3d8/src/libOpenImageIO/imagebufalgo_draw.cpp#L950) then becomes `font_file_map.find(nullptr)` which causes `std::string{nullptr}` which crashes.

I think the `nullptr` on the end of the array is superfluous and can simply be removed?

**Comment by lgritz** [comment]
You are quite right! 

We used to use a regular 'for' and the nullptr signalled the end of valid names, but at some point we switched to range-for and the nullptr should have been removed when we did that.

I'm preparing a patch as we speak.

**Comment by lgritz** [comment]
Proposed fix: #4249

**Comment by lgritz** [comment]
Thanks very much for the full diagnosis, @alanb-sony! It was immediately obvious from your description what needed to be fixed, and I was easily able to go from reading your issue to having a PR submitted in less than 5 minutes. If I'd needed to carefully recreate the conditions of it unable to find any fonts in order to observe the crash and figure out why exactly that was crashing, it might easily have been one of those things I postpone, then falls off the visible part of my inbox, then just sits for months until I notice it again.

Wednesday is our scheduled monthly patch release, so this will surly be incorporated into that release.

**Comment by JGoldstone** [comment]
> Wednesday is our scheduled monthly patch release, so this will surly be incorporated into that release.

Actually you sounded quite appreciative, not surly at all.
