### ISSUE TITLE
Close image if it's not loading

### ISSUE THREAD

**Issue by onlyshk** [OpenImageIO/oiio#44]
Hello,

For example: we open in iv program any image, for example 3. In status bar we can see information about it: (3/3)....

Now we have 3 displaying images. For example i open 4 image, but it's not open. In statusbar we have (4/4)... but iv displaying 3 images now and 4 black screen and note that image cannot be opened. I suggest if iv cannot load image, show error message to user and close this image. I want to write patch. What do you think about it?

Thank you.

**Comment by wrosecrans** [comment]
I was looking through old bugs to see if there was low hanging fruit I could work on, and this is the oldest open one.  Does anybody have thoughts on whether this is desired behavior, or something that should be changed so broken images aren't retained as "open"?  I confirmed that this is still what happens when you open a broken image.

**Comment by lgritz** [comment]
Coalescing.
