### ISSUE TITLE
Issue building OIIO with OCIO 1.0.9 support

### ISSUE THREAD

**Issue by efleurant** [OpenImageIO/oiio#839]
I tried compiling OIIO with my own build of OCIO 1.0.9 (current master branch) and I'm getting this error. Maybe someone can help.
'''
...
Linking CXX shared library libOpenImageIO.so
[ 81%] Built target OpenImageIO
[ 82%] Building CXX object src/libOpenImageIO/CMakeFiles/imagebuf_test.dir/imagebuf_test.cpp.o
Linking CXX executable imagebuf_test
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Node::begin() const'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Node::~Node()'
libOpenImageIO.so.1.4.5: undefined reference to `TiXmlNode::TiXmlNode(TiXmlNode::NodeType)'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlNode::FirstChildElement() const'
libOpenImageIO.so.1.4.5: undefined reference to `vtable for TiXmlPrinter'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::PostWriteStreamable(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > const&)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Node::FindAtIndex(unsigned long) const'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Iterator::second() const'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Node::Node()'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlElement::SetAttribute(char const_, char const_)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Iterator::operator++()'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Parser::~Parser()'
libOpenImageIO.so.1.4.5: undefined reference to `vtable for TiXmlDocument'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlNode::FirstChild(char const_) const'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Emitter::PreWriteIntegralType(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&)'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlDocument::TiXmlDocument()'
libOpenImageIO.so.1.4.5: undefined reference to `TiXmlNode::~TiXmlNode()'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Iterator::first() const'
libOpenImageIO.so.1.4.5: undefined reference to `TiXmlNode::InsertBeforeChild(TiXmlNode_, TiXmlNode const&)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Emitter::Write(YAML::_Tag const&)'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::~Emitter()'
libOpenImageIO.so.1.4.5: undefined reference to `TiXmlElement::Attribute(char const*) const'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Parser::Parser(std::basic_istream<char, std::char_traits<char> >&)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Parser::GetNextDocument(YAML::Node&)'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::good() const'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::operator!=(YAML::Iterator const&, YAML::Iterator const&)'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlDocument::Parse(char const_, TiXmlParsingData_, TiXmlEncoding)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Emitter::PostWriteIntegralType(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > const&)'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::GetFloatPrecision() const'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Iterator::~Iterator()'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::Write(bool)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Emitter::PreWriteStreamable(std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&)'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Convert(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Node::GetScalar(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::Write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Node::end() const'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlElement::TiXmlElement(char const_)'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Emitter::c_str() const'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlNode::NextSibling(char const_) const'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Node::size() const'
libOpenImageIO.so.1.4.5: undefined reference to`TiXmlNode::LinkEndChild(TiXmlNode_)'
libOpenImageIO.so.1.4.5: undefined reference to `TiXmlHandle::FirstChild(char const_) const'
libOpenImageIO.so.1.4.5: undefined reference to `TiXmlDocument::Accept(TiXmlVisitor*) const'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::Emitter()'
libOpenImageIO.so.1.4.5: undefined reference to `YAML::Iterator::Iterator(YAML::Iterator const&)'
libOpenImageIO.so.1.4.5: undefined reference to`vtable for TiXmlText'
libOpenImageIO.so.1.4.5: undefined reference to `TiXmlElement::GetText() const'
libOpenImageIO.so.1.4.5: undefined reference to`YAML::Emitter::SetLocalValue(YAML::EMITTER_MANIP)'
collect2: ld returned 1 exit status
make[2]: **\* [src/libOpenImageIO/imagebuf_test] Error 1
make[1]: **\* [src/libOpenImageIO/CMakeFiles/imagebuf_test.dir/all] Error 2
make: **\* [all] Error 2
'''
EDIT: Sorry, I pasted the wrong error log at first, now it's the right one

Thanks in advance

**Comment by nrusch** [comment]
I just ran into this, and traced it back to what looks like an issue with the OCIO static library build process.

Basically, if you build a static OCIO library, it doesn't properly include the compiled YAML and TinyXML objects in the archive, so all of their related symbols are missing. As a test, I manually dumped all of the objects from `libOpenColorIO.a`, `libtinyxml.a`, and `libyaml-cpp.a`, and reassembled them into a new `libOpenColorIO.a`. Linking that new library, the OIIO build completed without errors.

It looks like OIIO may be trying to work around this by explicitly trying to link `tinyxml`, `yaml-cpp`, and `lcms2` if `LINKSTATIC` is enabled (see [here](https://github.com/OpenImageIO/oiio/blob/master/src/cmake/externalpackages.cmake#L245)), but because those libraries are always built and linked statically by OCIO, they aren't actually installed in any way that will let OIIO find them at build time.

I'm adding an issue on the OCIO side related to building a complete static library, and I think I may take a crack at a PR in the near future. It's somewhat awkward, since building objects as targets isn't directly supported by CMake prior to 2.8.8, and the only other option that I'm aware of is using a custom target for the static library that either locates all the necessary object files, or unpacks and re-packs the archives the way I did.

**Comment by malcolmhumphreys** [comment]
Must be a bug as I spent a lot of time getting the static build to be
correct back in the day.

We you do look at it I would first look at what happens when yamlcpp and
tinyxml are found on the system. As I always build with the bundled
versions.

**Comment by nrusch** [comment]
Well, `libOpenImageIO` will link `libOpenColorIO.a` without complaining, but as soon as something actually tries to use it (in this case, the OIIO tests), things fall apart. From what I've found, it doesn't seem like CMake knows (or can be explicitly told) that linking one static library into another requires the objects to be extracted from the dependency and included in the assembled target. However, in this case, I suspect that the `OBJECT` library type would be the "right" way to deal with the issue, since the dependencies are being compiled at the same time.

**Comment by nrusch** [comment]
Sorry, I forgot to mention that I've always built OCIO with the bundled dependencies as well.

**Comment by lgritz** [comment]
Closing. This is very old, both OIIO and OCIO have changed quite a lot in the mean time. Somebody will re-open or file a new issue of the modern versions fail to build against each other.
