### ISSUE TITLE
TextureSystemImpl::texture is slow for high dsdx, dtdx, dsdy, dtdy values

### ISSUE THREAD

**Issue by monsieurgustav** [OpenImageIO/oiio#969]
Hi all,

In TextureSystemImpl::texture.
OIIO uses dsdx, dtdx, dsdy, dtdy to build an ellipse, then to compute a filtered value from the texture file.
High value derivatives (< -10 ; > 10) imply a big performance hit.
As far as I understand it :
- OIIO chooses the highest mipmap, the 1x1 pixel mipmap level (because the derivatives are outside [-1, 1])
- It computes the bilinear filtering, sampling N times the same single pixel from the mipmap level, which is useless computation.

Now, I clamp the derivatives in [-1, 1] before the call to TextureSystemImpl::texture.
The result is strictly identical, for a third of my computation time.

Maybe OIIO could clamp the values itself ?

Cheers,
Guillaume

**Comment by lgritz** [comment]
Thread necromancy...

That's a really interesting observation.

It seems to me that it's relatively simple to check if we're sampling on the 1x1 mipmap level and if the wrap mode is anything other than "black", then we can just return the color of that pixel straightaway without any samples at all (let alone multiple samples for anisotropy). For "black" wrap mode, that's not the case and we still need to sample to properly filter the colored pixel versus its black surroundings.

However, I would think that situation is very rare. I mean, how often really are we sampling the 1x1 level, and doing so with enough anisotropy that it's doing more than 1 pointless lookup? In this incredibly rare case, we could certainly make it less expensive... but only by doing the test itself on EVERY texture lookup.

I further did some tests myself on this myself, and forcing a large enough blur to guarantee hitting the 1x1 level is about 3.5x slower than a normal texture lookup. That's not enormous; maybe other changes in the (embarrassingly long, sorry) time since you filed this helped reduce the expense of this case? If it were 100x or maybe even 10x, I might be concerned.

So in my mind, the question is: ON THE WHOLE -- averaged across all users, all frames, all texture lookups -- would we come out ahead if we had an extra test on every texture lookup in order to speed up this rare case? Or is it better to keep the usual case as streamlined as possible, with a minimum of tests and branches (and code complexity), even if that means that a few edge cases are doing needless work?

I'm inclined to bet on the side of keeping the common case streamlined, so I'm closing this ticket.

But maybe I'm overlooking how commonly this happens? If anybody wants to make a case for an extra test to isolate and optimize this situation, I'm open to it, please don't hesitate to re-open the ticket and I'll follow up with a fix.

**Comment by monsieurgustav** [comment]
Hi @lgritz 
I'm not working on this project anymore, but I can give some context.

OIIO is used with OSL in a path tracer renderer. For rough materials, the full hemisphere is sampled, each ray sample has high derivatives. When hitting small/far objects, it is common to hit the last mipmap, and still have derivatives to throw in the computation..
IIRC, I agree on the ~3x slower than a normal texture lookup. But it may represent most of the image calculation, in some setups.

I still tend to agree to your conclusion: keep the code straight.

**Comment by lgritz** [comment]
Yeah, understood.

I'll keep an eye on our production stats and see if we're hitting a lot of 1x1 levels, and if so, maybe I'll give this a test implementation and see if it speeds things up overall.
